-- ─── FISIOLOGIA VEGETAL — PAULILO, VIANA & RANDI (UFSC/UAB, 2015) ─────────────
-- Nutrição mineral, fixação biológica de N, relações hídricas, fitohormônios
-- ─────────────────────────────────────────────────────────────────────────────

insert into public.conhecimento (titulo, tipo, cultura, conteudo, fonte, tags) values

('UFSC/Paulilo — Funções e sintomas de deficiência dos nutrientes essenciais (Tabela 2.2)',
 'referencia', 'all',
 'Síntese das funções bioquímicas e sintomas de deficiência por nutriente: NITROGÊNIO — parte de proteínas, ácidos nucleicos, hormônios (auxinas, citocininas) e clorofila; deficiência = folhas amareladas (clorose geral), baixo crescimento. FÓSFORO — açúcares fosfatados, DNA/RNA, fosfolipídeos, ATP; deficiência = verde intenso das folhas, manchas necróticas, folhas malformadas. POTÁSSIO — ativa enzimas da fotossíntese e respiração, síntese de amido e proteínas; deficiência = folhas velhas com clorose seguida de lesões necróticas nas bordas. ENXOFRE — aminoácidos cisteína e metionina, proteínas; deficiência = clorose nas folhas incluindo tecidos em volta dos feixes vasculares (não móvel = sintoma em folhas jovens). CÁLCIO — mensageiro secundário em hormônios, formação do fuso mitótico, lamela média; deficiência = folhas jovens deformadas e necróticas, morte dos meristemas. MAGNÉSIO — integrante da clorofila, estabiliza ribossomos, ativa enzimas; deficiência = clorose internerval nas folhas (regiões entre as nervuras). FERRO — catálise de fotossíntese, fixação de N e respiração; deficiência = clorose internerval nas folhas jovens, podendo tornar-se brancas em deficiência severa. BORO — alongamento de células radiculares, metabolismo de ácidos nucleicos; deficiência = necrose do meristema. COBRE — cofator de enzimas oxidativas; deficiência = baixo crescimento, folhas jovens deformadas e caem precocemente (especialmente Citrus). ZINCO — ativa enzimas, síntese de triptofano → precursor de auxinas; deficiência = encurtamento de internódios, folhas pequenas. MANGANÊS — cofator de enzimas (descarboxilase, desidrogenases), complexo liberador de O₂ na fotossíntese; deficiência = manchas verde-acinzentadas na base das folhas jovens de cereais, clorose internerval.',
 'Paulilo, M.T.S.; Viana, A.M.; Randi, A.M. (2015). Fisiologia Vegetal. UFSC/UAB, Florianópolis.',
 '{nutrientes, deficiência, N, P, K, S, Ca, Mg, Fe, B, Cu, Zn, Mn, funções bioquímicas, sintomas, tabela}'),

('UFSC/Paulilo — Fixação biológica do N₂: bioquímica da dinitrogenase',
 'artigo', 'all',
 'Apenas procariotos (bactérias e cianobactérias) contêm a enzima dinitrogenase, capaz de quebrar a ligação tripla do N₂ atmosférico. A enzima dinitrogenase é formada por duas subunidades: uma ferroproteína e uma molibdênio-ferroproteína. Reação de fixação: 8H⁺ + 8e⁻ + N₂ + 16 ATP → 2 NH₃ + H₂ + 16 ADP + 16 Pi. O doador de H⁺ e elétrons é o NADH produzido pelo Ciclo de Krebs do bacterioide; a ferredoxina faz a transferência para a dinitrogenase. O carboidrato (fotossintato das folhas) entra no bacterioide, passa pela glicólise e Ciclo de Krebs, gerando NADH → cadeia respiratória → ATP. Organismos fixadores simbiióticos com leguminosas: Rhizobium, Bradyrhizobium, Azorhizobium. Fixadores em não-leguminosas: Frankia (Casuarina, Alnus). Fixadores de vida livre: cianobactérias Anabaena e Nostoc. Processo de nodulação: raízes liberam flavonoides → atraem bactérias → infecção pelo pelo radicular → canal de infecção → bacterioide nas células do córtex → conexão vascular para distribuição de N fixado.',
 'Paulilo, M.T.S.; Viana, A.M.; Randi, A.M. (2015). Fisiologia Vegetal. UFSC/UAB, Florianópolis.',
 '{fixação biológica, N, dinitrogenase, rhizobium, bradyrhizobium, nodulação, FBN, bacterioide, ATP, ferredoxina}'),

('UFSC/Paulilo — Relações hídricas: funções da água e mecanismo estomático',
 'artigo', 'all',
 'Funções fisiológicas da água na planta: transporte de substâncias (raiz → folha e vice-versa); expansão de células meristemáticas por turgidez; sustentação de órgãos (turgor celular, como um balão de borracha); refrigeração por evaporação (sem transpiração, folha aquece 10-15°C acima do ar); isolante térmico contra variações bruscas; movimento de estômatos e folíolos (Mimosa pudica). Para atividade metabólica normal, células devem conter pelo menos 65% de água. Mecanismo estomático: abertura por acúmulo de K⁺ e sacarose nas células-guarda — o fluxo de K⁺ está acoplado à saída de H⁺ via H⁺-ATPase, criando diferença de potencial eletroquímico que ativa canais de K⁺; luz azul estimula H⁺-ATPase; luz vermelha estimula degradação de amido → sacarose (segundo sinal). Fechamento por estresse hídrico: falta de água → produção de ABA → fechamento estomático. Os estômatos podem abrir e fechar no escuro seguindo um ritmo circadiano. Estômatos abertos = troca de CO₂, O₂ e vapor d''água entre o espaço interno da folha e a atmosfera.',
 'Paulilo, M.T.S.; Viana, A.M.; Randi, A.M. (2015). Fisiologia Vegetal. UFSC/UAB, Florianópolis.',
 '{água, relações hídricas, estômato, K, ABA, turgidez, transpiração, abertura, fechamento, ritmo circadiano}'),

('UFSC/Paulilo — Fitohormônios: cinco grupos, locais de síntese e efeitos fisiológicos',
 'artigo', 'all',
 'Cinco grupos de fitohormônios descobertos: AUXINAS (AIA — ácido indol-3-acético, precursor: triptofano): síntese em meristemas apicais, folhas jovens, embriões; transporte basípeto via células parenquimáticas adjacentes ao xilema; efeitos = alongamento celular (hipótese do crescimento ácido: AIA ativa H⁺-ATPase → abaixa pH da parede → ativa expansinas → amolece celulose → entrada de K⁺ e H₂O → elongação); dominância apical; enraizamento de estacas. GIBERELINAS (GA₃; precursor: ácido mevalônico): síntese em tecidos jovens e sementes; transporte via xilema e floema; efeitos = elongação do caule, germinação, florescimento de dias longos. CITOCININAS (síntese de ATP/ADP + isopentenil): síntese em ápices radiculares; transporte via xilema (raiz → parte aérea); efeitos = divisão celular, retardam senescência, quebra de dominância apical (interação com auxinas), abertura estomática (antagonista ao ABA). ETILENO (hidrocarboneto gasoso; precursor: metionina): síntese em todos os tecidos, especialmente meristemas e frutos; transporte por difusão; efeitos = amadurecimento de frutos, senescência, abscisão foliar, resposta ao estresse. ABA (ácido abscísico, 15C; síntese de zeaxantina): síntese aumenta em estresse hídrico; transporte folha→raiz via floema e raiz→parte aérea via xilema; efeitos = fechamento estomático, dormência de sementes e gemas, tolerância ao estresse.',
 'Paulilo, M.T.S.; Viana, A.M.; Randi, A.M. (2015). Fisiologia Vegetal. UFSC/UAB, Florianópolis.',
 '{auxina, AIA, giberelina, citocinina, etileno, ABA, ácido abscísico, fitohormônios, crescimento, senescência, amadurecimento, estresse}');
