-- ─── PLANT NUTRITION AND SOIL FERTILITY MANUAL — J. BENTON JONES JR. (CRC, 2012) ─
-- Deficiency/excess symptoms, nutrient mobility, soil pH, hidden hunger
-- ─────────────────────────────────────────────────────────────────────────────

insert into public.conhecimento (titulo, tipo, cultura, conteudo, fonte, tags) values

('Jones/CRC — Deficiency and excess symptoms for all essential elements (Table 3.6)',
 'referencia', 'all',
 'MAJOR ELEMENTS — deficiency (D) and excess/toxicity (E) symptoms: NITROGEN D: light green leaves; older leaves turn yellow then brown and die; slow growth; early maturity. N E: dark green succulent growth; susceptible to disease/insects/drought; lodging; blossom abortion. AMMONIUM TOXICITY: carbohydrate depletion; lesions on stems; downward leaf cupping; decay of conductive tissue at stem base; blossom-end rot; Mg deficiency symptoms. PHOSPHORUS D: slow stunted growth; purple coloration on underside of older leaves. P E: visual signs of Zn, Fe, or Mn deficiency; may interfere with Ca nutrition. POTASSIUM D: edges of older leaves burned (scorch); plants lodge easily; sensitive to disease; poor fruit/seed quality. K E: Mg and possibly Ca deficiency symptoms (cation imbalance). CALCIUM D: growing root and leaf tips turn brown and die; leaf edges ragged (emerging leaves stick together); blossom-end rot on fruits. Ca E: Mg deficiency; extreme excess causes K deficiency. MAGNESIUM D: older leaves turn yellow with interveinal chlorosis; slow growth. Mg E: Ca or K deficiency symptoms. SULFUR D: overall light green color; older leaves turn light green to yellow. S E: premature leaf senescence. MICRONUTRIENTS: BORON D: abnormal meristem development; apical growing points die; flowers and fruit abort; brittle stems. B E: leaf tips and margins turn brown and die. CHLORINE D: young leaves chlorotic; plants wilt easily. Cl E: premature yellowing of lower leaves; burning of margins; leaf abscission; wilting. COPPER D: slow stunted growth; young leaves distorted; growing points die. Cu E: Fe deficiency induced; stunted roots. IRON D: interveinal chlorosis on emerging/young leaves; entire plant may turn light green when severe. Fe E: bronzing of leaves with tiny brown spots. MANGANESE D: interveinal chlorosis of young leaves; plants remain generally green; stunting when severe. Mn E: older leaves show brown spots surrounded by chlorotic zones. MOLYBDENUM D: similar to N deficiency; older and middle leaves become chlorotic first; leaf margins rolled; growth and flower formation restricted; cauliflower whiptail symptom. ZINC D: upper leaves show interveinal chlorosis with whitening; small distorted leaves forming rosettes. Zn E: Fe deficiency symptoms develop.',
 'Jones, J.B. Jr. (2012). Plant Nutrition and Soil Fertility Manual. 2nd ed. CRC Press/Taylor & Francis, Boca Raton.',
 '{deficiência, toxicidade, sintomas, N, P, K, Ca, Mg, S, B, Cl, Cu, Fe, Mn, Mo, Zn, excesso, tabela, diagnose visual}'),

('Jones/CRC — Mobilidade de nutrientes na planta: onde esperar sintomas de deficiência',
 'artigo', 'all',
 'Classificação dos nutrientes pela mobilidade no floema, que determina em qual parte da planta surgem os sintomas de deficiência: MUITO MÓVEIS (sintomas em folhas velhas): Mg, N, P e K — são redistribuídos das folhas velhas para folhas jovens e frutos em desenvolvimento. LEVEMENTE MÓVEL: S. IMÓVEIS (sintomas em folhas jovens e pontos de crescimento): Cu, Fe, Mo e Zn. MUITO IMÓVEIS (sintomas severos em meristemas e frutos): B e Ca — movimento mínimo do restante da planta para frutos em desenvolvimento → blossom-end rot em Ca e B. Aplicação prática: sintoma em folha velha = deficiência de nutriente móvel (N, P, K, Mg); sintoma em folha nova ou meristema = nutriente imóvel (Ca, B, Fe, Zn, Cu). Com a maturação da planta: conteúdo de N, P e K nas folhas DECLINA (redistribuição para grãos); Ca e Mg nas folhas AUMENTAM (não redistribuídos). Esta dinâmica temporal é crítica para a interpretação de análise foliar: o momento e o órgão amostrado determinam a validade do resultado. Transporte ascendente (raiz → folha): principalmente via xilema; descendente: via floema. Taxa de transporte no xilema: 10–100 cm/h; floema: consideravelmente menor. Transpressão impulsiona principalmente Ca e B para folhas — frutos com baixa transpiração recebem pouco Ca mesmo com oferta adequada no solo.',
 'Jones, J.B. Jr. (2012). Plant Nutrition and Soil Fertility Manual. 2nd ed. CRC Press/Taylor & Francis, Boca Raton.',
 '{mobilidade, floema, xilema, N, P, K, Mg, Ca, B, Fe, Zn, Cu, Mo, S, redistribuição, diagnose foliar, folha velha, folha jovem}'),

('Jones/CRC — Efeito do pH do solo na disponibilidade de nutrientes',
 'artigo', 'all',
 'pH ótimo do solo mineral para crescimento da maioria das culturas: 5,5 a 6,5. ABAIXO DE pH 5,5: disponibilidade de P e Mg DECLINA; concentração de Al, Mn (e em alguns solos Cu) avança para a faixa tóxica; P se precipita com Al → complexos insolúveis de Al-P. ACIMA DE pH 6,5: disponibilidade de Cu, Mn, Fe e Zn DECLINA; interação entre Ca, Mg e K começa a prejudicar absorção radicular de Mg e K; disponibilidade de P também declina progressivamente em pH alcalino. pH de solos orgânicos: ótimo entre 5,4–6,0 (disponibilidade declina acima de pH 6,4). Implicação prática de supercalagem: pH > 6,5 induz deficiências de micronutrientes catiônicos (Fe, Mn, Zn, Cu) mesmo com boa fertilidade global. A rizosfera (zona de 1–2 mm ao redor da raiz) tem pH 1 unidade abaixo do solo circundante devido à liberação de H⁺ pela respiração radicular — isso facilita absorção de P e micronutrientes em solos ligeiramente ácidos. Plantas "Fe-eficientes" podem acidificar a rizosfera e liberar sideróforos para quelar Fe.',
 'Jones, J.B. Jr. (2012). Plant Nutrition and Soil Fertility Manual. 2nd ed. CRC Press/Taylor & Francis, Boca Raton.',
 '{pH, disponibilidade, Al, Mn, Fe, Zn, Cu, P, Mg, rizosfera, calagem, supercalagem, acidez, alcalinidade}'),

('Jones/CRC — Hidden hunger (fome oculta): conceito, exemplos e implicações',
 'artigo', 'all',
 'Hidden hunger (fome oculta) é a condição em que uma deficiência nutricional não produz sintomas visuais, mas reduz o crescimento, a produtividade e a qualidade do produto. Conceito central: a planta parece se desenvolver normalmente, mas a análise foliar ou de tecido revela concentração abaixo do nível crítico. Consequências documentadas: em grãos = menor produtividade e qualidade do grão do que o esperado; em frutas = blossom-end rot, anomalias internas, menor vida pós-colheita e qualidade de transporte; em milho = deficiência de K que não é evidente até a maturidade, quando as plantas acamam facilmente. Exemplos adicionais: deficiência de Cl em trigo aumenta susceptibilidade ao "take-all" (doença radicular); Si insuficiente em arroz = falta de resistência dos colmos e suscetibilidade a fungos. Alto N na planta = sensível a estresse hídrico e infestação por insetos/doenças. Detecção: análise foliar ou de tecido antes do surgimento de sintomas. Diagnose reativa (apenas sintomas visuais) significa produção já perdida, não recuperável. Fator multiplicador: se 5 fatores cada um a 90% de suficiência → rendimento final = 90^5 = 59% do máximo (não 90%).',
 'Jones, J.B. Jr. (2012). Plant Nutrition and Soil Fertility Manual. 2nd ed. CRC Press/Taylor & Francis, Boca Raton.',
 '{hidden hunger, fome oculta, sintoma subclínico, análise foliar, produtividade, K, Cl, Si, acamamento, diagnose precoce}');
