-- ─── SOIL FERTILITY AND FERTILIZERS — HAVLIN, TISDALE, NELSON & BEATON (8ª ED, 2017) ─
-- Deficiência e toxicidade de macro e micronutrientes, mobilidade, pH do solo
-- ─────────────────────────────────────────────────────────────────────────────

insert into public.conhecimento (titulo, tipo, cultura, conteudo, fonte, tags) values

('Havlin et al. — Mobilidade de nutrientes e localização dos sintomas de deficiência',
 'artigo', 'all',
 'Entender a mobilidade dos nutrientes no floema é essencial para identificar onde surgirão os sintomas de deficiência. NUTRIENTES MÓVEIS (sintomas nas folhas velhas/basais primeiro — redistribuídos das folhas velhas para tecidos jovens): N, P, K, Mg e Mo. NUTRIENTES IMÓVEIS (sintomas nas folhas jovens/pontos de crescimento primeiro): Ca, Fe, Mn, Zn, Cu e Ni. MOBILIDADE VARIÁVEL com espécie: S, Cl e B — dificulta identificar pelo padrão de localização. Implicação diagnóstica crítica: Sintoma em folha velha = suspeitar de N, P, K, Mg ou Mo. Sintoma em folha nova, meristema ou ponto de crescimento = suspeitar de Ca, Fe, Mn, Zn, Cu, Ni. B imóvel em milho, algodão, soja, feijão, trigo, sorgo, beterraba; B móvel em maçã, pereira, cenoura, repolho, couve-flor, brócolis. Blossom-end rot (podridão apical) em tomate e pimenta = Ca imóvel + baixa transpiração nos frutos = Ca não chega. Raízes curtas e escurecidas = sinal clássico de deficiência de Ca na zona radicular. Nodulação ruim em leguminosas = pode indicar deficiência de Ca na raiz (tecido do nódulo fica branco-acinzentado ao invés de rosa/vermelho).',
 'Havlin, J.L.; Tisdale, S.L.; Nelson, W.L.; Beaton, J.D. (2017). Soil Fertility and Fertilizers: An Introduction to Nutrient Management. 8th ed. Pearson.',
 '{mobilidade, floema, Ca, Fe, Mn, Zn, Cu, Ni, N, P, K, Mg, Mo, B, S, Cl, folha velha, folha nova, meristema, diagnose}'),

('Havlin et al. — Sintomas de deficiência de macronutrientes: P, K, Ca, Mg e S',
 'referencia', 'all',
 'FÓSFORO (D): crescimento lento e raquítico; folhas com coloração verde-escuro → verde-acinzentado a verde-azulado metálico → coloração roxa nas bordas das folhas velhas progredindo para toda a folha (acúmulo de açúcares e síntese de antocianina); folhas velhas necróticas em deficiência severa. Atenção: sintomas de P em plantas jovens em solos frios e úmidos mesmo com P disponível — baixa difusão + sistema radicular pequeno. Aplicação inicial no sulco (starter) previne. P é redistribuído de folhas velhas para grãos na fase reprodutiva. POTÁSSIO (D): bordas das folhas velhas queimadas (escorch); plantas acamam facilmente; sensíveis a doenças; qualidade de grãos/frutos comprometida. Soja e algodão: manchas brancas nas bordas das folhas. Milho: clorose e necrose das bordas das folhas velhas. CÁLCIO (D): pontas e bordas das folhas jovens cloróticas, sem cor, necróticas (die-back ou tip-burn); em milho — mucilagem nas pontas folha fazendo folhas colarem; raízes curtas, escurecidas e mortas; nodulação ruim em leguminosas (nódulos brancos/acinzentados ao invés de rosa); blossom-end rot em tomate e pimenta; bitter pit em maçã; black heart em amendoim/aipo; cavidade em cenoura. MAGNÉSIO (D): clorose internerval nas folhas velhas (nervuras verdes, entre-nervuras amarelas); em algodão: folhas velhas com coloração avermelhado-púrpura → marrom → necrótica. ENXOFRE (D): crescimento reduzido; plantas raquíticas, caule fino, cloróticas; S pode aparecer em folhas velhas (baixo N) ou novas (N adequado); crucíferas: cor avermelhada na face inferior das folhas, folhas curvadas para dentro; flores pálidas e sementes deficientes.',
 'Havlin, J.L.; Tisdale, S.L.; Nelson, W.L.; Beaton, J.D. (2017). Soil Fertility and Fertilizers: An Introduction to Nutrient Management. 8th ed. Pearson.',
 '{P, K, Ca, Mg, S, deficiência, sintomas, folha velha, clorose, necrose, blossom-end rot, acamamento, antocianina, milho, soja, tomate}'),

('Havlin et al. — Sintomas de deficiência e toxicidade de micronutrientes',
 'referencia', 'all',
 'FERRO (D): clorose internerval nas folhas jovens (Fe imóvel); progride para toda a folha que fica branca em deficiência severa. Fe tóxico: manchas bronzeadas nas folhas (> 300 ppm Fe). Suficiência: 50-250 ppm Fe foliar; deficiência em < 50 ppm. pH acima de 6,5 reduz disponibilidade acentuadamente — para cada unidade de aumento de pH, Fe³⁺ no solo diminui mil vezes. ZINCO (D): áreas verde-claras, amarelas ou brancas entre as nervuras de folhas jovens; necrose nas áreas cloróticas; encurtamento de internódios → roseta de folhas pequenas no ápice; em milho = faixas brancas características entre a nervura central e a borda da folha; em cereais = depressão do perfilhamento, nervura central na base de folhas jovens clorótica. Deficiência < 10-20 ppm Zn foliar; toxicidade > 400 ppm. MANGANÊS (D): clorose internerval em folhas jovens (Mn imóvel), pode ser confundida com Fe; gray speck em aveia; marsh spot em ervilha; speckled yellows em beterraba. Mn tóxico: em solos ácidos e mal drenados; > 500-1000 ppm Mn → crinkle leaf no algodão; calagem corrige. BORO (D): B imóvel em milho, soja, feijão, trigo, algodão, beterraba → meristemas afetados, folhas jovens deformadas e pálidas; B reduz esterilidade masculina em gramíneas; em leguminosas = roseta de folhas novas + nodulação deficiente; frutos e tubérculos apodrecem internamente. Suficiência: 6-18 ppm (monocots), 20-60 ppm (dicots); toxicidade > 200 ppm. MOLIBDÊNIO (D): semelhante a N; folhas velhas e medianas ficam cloróticas; margens das folhas enroladas; crescimento e florescimento restritos; em couve-flor = whiptail (folha reduzida à nervura central).',
 'Havlin, J.L.; Tisdale, S.L.; Nelson, W.L.; Beaton, J.D. (2017). Soil Fertility and Fertilizers: An Introduction to Nutrient Management. 8th ed. Pearson.',
 '{Fe, Zn, Mn, B, Mo, micronutrientes, deficiência, toxicidade, clorose, roseta, internódio, milho, soja, brassica, whiptail, imobilidade}'),

('Havlin et al. — Conceito de nível crítico, luxúria e fome oculta (hidden hunger)',
 'artigo', 'all',
 'Definições de status nutricional da planta: DEFICIENTE = concentração do elemento baixa o suficiente para limitar severamente o rendimento, com sintomas visíveis. Com deficiências moderadas, sintomas podem não ser visíveis mas rendimento ainda é reduzido (fome oculta). FAIXA CRÍTICA = concentração abaixo da qual ocorre resposta ao nutriente adicionado (abaixo do nível ótimo). Varia entre plantas e nutrientes. SUFICIÊNCIA = faixa de concentração onde o rendimento é máximo — independe da concentração. CONSUMO DE LUXO = absorção de nutriente acima do necessário para o rendimento máximo; elemento acumulado em excesso pode reduzir rendimento por toxicidade direta ou por antagonismo (reduz concentração de outro nutriente). Efeito Steenberg: em deficiência severa, quando o nutriente é fornecido, o rendimento cresce mais rápido que a concentração do nutriente na planta → queda transitória na concentração por diluição (a planta cresce mais do que o nutriente se concentra). Princípio do mínimo (Liebig): o rendimento é proporcional ao nutriente mais limitante — uma vez corrigido, o rendimento sobe até o limite do próximo nutriente limitante. Este princípio se aplica também a outros fatores além dos nutrientes (água, luz, temperatura). Diagnóstico correto requer: análise foliar + análise de solo + histórico de manejo — sintomas visuais isolados são insuficientes e frequentemente já indicam perdas de rendimento irreversíveis.',
 'Havlin, J.L.; Tisdale, S.L.; Nelson, W.L.; Beaton, J.D. (2017). Soil Fertility and Fertilizers: An Introduction to Nutrient Management. 8th ed. Pearson.',
 '{nível crítico, suficiência, consumo de luxo, fome oculta, hidden hunger, Liebig, Lei do Mínimo, Steenberg, diagnose, rendimento}');
