-- ─── HAVLIN et al. — CICLO DO N, PERDAS E MICRONUTRIENTES PARA FBN ───────────
-- Soil Fertility and Fertilizers, 8ª ed. (2017) — N cycle, N losses, BNF
-- ─────────────────────────────────────────────────────────────────────────────

insert into public.conhecimento (titulo, tipo, cultura, conteudo, fonte, tags) values

('Havlin et al. — Ciclo do nitrogênio: transformações e perdas no solo',
 'artigo', 'all',
 'Ciclo do N no sistema solo-planta-atmosfera — principais transformações: (1) ADIÇÃO: resíduos vegetais/animais, FBN por leguminosas e organismos de vida livre, descargas elétricas, adubos industriais. (2) MINERALIZAÇÃO: N orgânico → NH₄⁺ por microorganismos; mineralização líquida libera aprox. 40 kg N/ha/ano em solos com bom teor de MO. (3) NITRIFICAÇÃO: NH₄⁺ → NO₂⁻ (por Nitrosomonas) → NO₃⁻ (por Nitrobacter); aeróbia; acidifica o solo (cada mol de NH₄⁺ nitrificado gera 2 H⁺). (4) IMOBILIZAÇÃO: microorganismos convertem N mineral de volta a N orgânico (C:N alto > 30 → imobilização predomina). (5) DENITRIFICAÇÃO: NO₃⁻ → NO → N₂O → N₂; requer anaerobiose (> 80% dos poros saturados com água) + NO₃⁻ + C disponível; bactérias Pseudomonas, Bacillus, Paracoccus; perda de 10-40% do N aplicado em solos mal drenados. (6) VOLATILIZAÇÃO: NH₄⁺ → NH₃ gasoso; ocorre em pH > 7 ou em superfície com resíduos; perdas de até 30% com ureia de superfície; NBPT (inibidor de urease) reduz perdas. (7) LIXIVIAÇÃO: NO₃⁻ (ânion, não retido em CTC) lixivia facilmente com água; perdas de 10-30% do N aplicado em solos bem drenados, 30-40% em sistemas de drenagem artificial (drenos). Vias de perda a evitar: ureia na superfície sem incorporação (volatilização) + solos encharcados (desnitrificação) + altas doses únicas em solos arenosos (lixiviação).',
 'Havlin, J.L.; Tisdale, S.L.; Nelson, W.L.; Beaton, J.D. (2017). Soil Fertility and Fertilizers: An Introduction to Nutrient Management. 8th ed. Pearson.',
 '{N, nitrogênio, ciclo, mineralização, nitrificação, desnitrificação, volatilização, lixiviação, ureia, NBPT, denitrificação, NH3, NO3}'),

('Havlin et al. — FBN por leguminosas: micronutrientes críticos e fatores limitantes',
 'artigo', 'all',
 'Fixação Biológica de N₂ (FBN) global: 130-180 milhões t N/ano, com ~50% fixado por Rhizobia em simbiose com leguminosas. MICRONUTRIENTES CRÍTICOS PARA FBN: MOLIBDÊNIO é o mais importante — Mo é componente da nitrogenase (enzima que fixa N₂) e a planta exige mais Mo quando dependente de FBN do que quando usa N mineral. Deficiência de Mo = deficiência de FBN mesmo com boa nodulação. BORO — afeta desenvolvimento dos nódulos e estabilidade da parede celular. FERRO — componente da ferroproteína (subunidade da nitrogenase); deficiência reduz FBN. COBRE — afeta nodulação. COBALTO — Co é essencial para Rhizobium; dose mínima no solo 0,01 ppm; apenas 10 ppb Co ativa FBN em alfafa. FATORES QUE LIMITAM FBN: acidez do solo (Al³⁺ inibe crescimento de Rhizobium; calagem para pH 5,5-6,0 é fundamental); deficiência de Ca e H₂PO₄⁻ em solos ácidos limita crescimento do Rhizobium; N mineral elevado inibe formação de nódulos; fungicidas sistêmicos afetam cepa de rizóbio. Inoculação eficiente mesmo em solos com N disponível aumenta produtividade. Pequena dose de N na semeadura (starter) pode beneficiar a leguminosa jovem antes de os rizóbios se estabelecerem. Milho após soja tem valor de N-fertilizante equivalente a 20-30 kg N/ha por efeito da soja antecedente.',
 'Havlin, J.L.; Tisdale, S.L.; Nelson, W.L.; Beaton, J.D. (2017). Soil Fertility and Fertilizers: An Introduction to Nutrient Management. 8th ed. Pearson.',
 '{FBN, fixação biológica, Mo, molibdênio, B, Fe, Co, cobalto, rhizobium, bradyrhizobium, acidez, nodulação, soja, leguminosa, N}'),

('Havlin et al. — Perdas de N por volatilização de NH₃: ureia, fatores e manejo',
 'protocolo', 'all',
 'Volatilização de NH₃ é uma das principais causas de baixa eficiência do N em aplicações superficiais. MECANISMO: ureia → hidrólise por urease → NH₄⁺ + OH⁻ → aumento de pH local → NH₄⁺ ↔ NH₃ + H⁺; em pH > 7 o equilíbrio favorece NH₃ gasoso. FATORES QUE AUMENTAM PERDAS: pH do solo > 7 (solos calcários); temperatura alta (acima de 25°C a hidrólise é rápida — 2-3 dias); umidade próxima à capacidade de campo (máxima atividade de urease); palha na superfície (eleva umidade local e tem alta atividade de urease); vento (remove o NH₃ da superfície). MAGNITUDE DAS PERDAS: ureia superficial = até 30% do N aplicado em culturas anuais; em sistemas de plantio direto com palha = perdas ainda maiores; sulfato de amônio em solos calcários = até 50% de perdas. ESTRATÉGIAS DE MANEJO: incorporação física da ureia no solo (reduz 60-70% das perdas); uso de inibidor de urease NBPT (n-butil-tiofosfórico triamida) — reduz perdas em 30-50%; aguardar chuva de 6-12 mm em 3-6 dias após aplicação incorpora o N; aplicar em condições de solo frio ou seco quando possível; preferir sulfato de amônio ou urease + NBPT em plantio direto. Nitrato de amônio e sulfato de amônio são iguais ou superiores à ureia em condições desfavoráveis (pouca umidade, alta palha, altas temperaturas).',
 'Havlin, J.L.; Tisdale, S.L.; Nelson, W.L.; Beaton, J.D. (2017). Soil Fertility and Fertilizers: An Introduction to Nutrient Management. 8th ed. Pearson.',
 '{N, ureia, volatilização, NH3, NBPT, urease, plantio direto, temperatura, pH, palha, inibidor de urease, eficiência}');
