-- ─── MARSCHNER'S MINERAL NUTRITION OF HIGHER PLANTS — 3ª ED. (2012) ────────
-- Estratégias de absorção de Fe, toxicidade de Al/Mn, rizosfera, Zn, Mo
-- ─────────────────────────────────────────────────────────────────────────────

insert into public.conhecimento (titulo, tipo, cultura, conteudo, fonte, tags) values

('Marschner — Estratégias I e II de absorção de ferro: dicots/leguminosas vs. gramíneas',
 'artigo', 'all',
 'Plantas desenvolveram duas estratégias distintas para absorver Fe do solo: ESTRATÉGIA I (dicotiledôneas e monocots não-gramíneas — soja, feijão, tomate, girassol, eucalipto): em deficiência de Fe → (1) maior acidificação da rizosfera por H⁺-ATPase (excreção de prótons) → dissolve Fe(III) insolúvel; (2) ativação da redutase férrica (FRO2) → reduz Fe³⁺ → Fe²⁺ solúvel; (3) aumento de formação de células de transferência na rizoderme (maior superfície de absorção); (4) liberação de compostos fenólicos quelantes (ácido cafeico) e ácido cítrico. Absorção de Fe²⁺ por transportadores IRT1. Sintoma em folhas jovens (Fe imóvel). ESTRATÉGIA II (gramíneas — milho, trigo, arroz, sorgo, cevada): em deficiência de Fe → síntese e liberação de fitossideróforos (ácidos mugineicos derivados de L-metionina → nicotianamina → ácido desoximugineico) → quelam Fe³⁺ com constante de estabilidade 10³³ → complexo Fe³⁺-fitossideróforo absorvido por simportadores específicos (família YSL, maize Yellow Stripe 1). Liberação de fitossideróforos segue ritmo circadiano (máximo nas primeiras horas após o amanhecer). Implicação prática: soja (Estratégia I) é muito sensível à clorose de Fe em solos calcários (pH alto) porque a alta solubilidade de calcário neutraliza a acidificação da rizosfera. Milho (Estratégia II) é relativamente mais tolerante. Aplicar Fe-EDTA ou Fe-EDDHA quelado para soja em solos com pH > 7.',
 'Marschner, H. (Ed.) (2012). Marschner''s Mineral Nutrition of Higher Plants. 3rd ed. Academic Press, London.',
 '{Fe, ferro, clorose, Estratégia I, Estratégia II, fitossideróforo, soja, milho, rizosfera, pH, calcário, FRO, IRT, YSL, mugineic acid}'),

('Marschner — Toxicidade de Al e Mn em solos ácidos: mecanismos e sintomas',
 'artigo', 'all',
 'TOXICIDADE DE ALUMÍNIO (Al³⁺): Em solos abaixo de pH 5,0-5,5, Al³⁺ solúvel é a principal causa de inibição do crescimento radicular. Al³⁺ inibe elongação celular na zona de transição raiz/ápice. Sintoma típico: raízes curtas, grossas, pardacentas, com pouco ramificação → deficiência secundária de Ca (imóvel), P, K e micronutrientes na subsuperfície. Mecanismo: Al³⁺ compete com Ca²⁺ na plasmálema; bloqueia canais de Ca²⁺; inibe divisão celular. Tolerância: espécies resistentes (trigo, sorgo, cevada resistentes) liberam malato e/ou citrato pelos ápices radiculares via canais ALMT e MATE → quelam Al³⁺ externamente antes de entrar na célula. Calagem eleva pH e precipita Al(OH)₃ insolúvel — principal estratégia de manejo. Gesso agrícola reduz Al³⁺ por formação de AlSO₄⁺ (não tóxico) e fornece Ca para subsuperfície. TOXICIDADE DE MANGANÊS (Mn²⁺): Ocorre em solos ácidos (pH < 5,5) e/ou mal drenados (condições redutoras convertem Mn⁴⁺ → Mn²⁺ solúvel). Mn²⁺ > 500-1.000 ppm no tecido foliar = tóxico para culturas sensíveis. Sintomas: manchas intervenais com necrose nas folhas jovens; em dicots (feijão, soja, algodão) = deformação de folhas jovens ("crinkle leaf") similar a deficiência de Ca; Mn tóxico inibe absorção de Fe, Mg, Zn → deficiências induzidas. Liming corrige Mn tóxico. Alta suprimento de Mg pode atenuar toxicidade de Mn.',
 'Marschner, H. (Ed.) (2012). Marschner''s Mineral Nutrition of Higher Plants. 3rd ed. Academic Press, London.',
 '{Al, alumínio, toxicidade, Mn, manganês, acidez, raiz, crinkle leaf, pH, calagem, gesso, malato, citrato, ALMT, MATE, soja, feijão}'),

('Marschner — Zinco e Molibdênio: funções, deficiência e rizosfera',
 'artigo', 'all',
 'ZINCO (Zn²⁺) — funções: detoxificação de radicais superóxido (superóxido dismutase); integridade de membranas; síntese de proteínas; síntese do fitohormônio AIA (auxina) — Zn é cofator da enzima que sintetiza triptofano (precursor de AIA). Deficiência de Zn → menor AIA → internódios curtos → roseta no ápice. Em solos com pH alto (calagem excessiva): Zn²⁺ precipita e adsorve em CaCO₃, óxidos de Fe/Al → disponibilidade cai 30 vezes por unidade de pH entre 5-7. Sob deficiência de Zn: raízes liberam mais fitossideróforos (gramíneas) e ácidos orgânicos → mobilizam Zn do solo. Em milho com deficiência severa de Zn = faixas brancas entre nervura central e borda das folhas jovens; encurtamento de internódios; folhas pequenas. Nível foliar suficiente: 25-150 ppm Zn; deficiência < 15-20 ppm; toxicidade > 400 ppm. MOLIBDÊNIO (Mo) — funções: componente da nitrogenase (FBN em leguminosas) e da redutase de nitrato (assimilação de N em todas as plantas). Deficiência de Mo = sintomas similares a N (clorose folhas velhas); em couve-flor = "whiptail" (folha reduzida à nervura). Mo disponibilidade AUMENTA com pH crescente — oposto dos demais micronutrientes. Deficiência comum em solos muito ácidos (pH < 5,5). Calagem + Mo foliar (12-25 g Mo/ha) resolve. Leguminosas precisam de mais Mo que gramíneas (nitrogenase consome mais Mo que redutase de nitrato).',
 'Marschner, H. (Ed.) (2012). Marschner''s Mineral Nutrition of Higher Plants. 3rd ed. Academic Press, London.',
 '{Zn, zinco, Mo, molibdênio, auxina, AIA, nitrogenase, redutase de nitrato, pH, calagem, fitossideróforo, milho, feijão, leguminosa, FBN}'),

('Marschner — Rizosfera: pH, exsudatos radiculares e mobilização de nutrientes',
 'artigo', 'all',
 'A rizosfera é a zona de solo imediatamente ao redor das raízes (1-2 mm) com propriedades físico-químicas distintas do solo em massa. pH da rizosfera pode diferir até 2 unidades do pH do solo — determinado principalmente pelo desequilíbrio entre cátions e ânions absorvidos: absorção > cátions → planta libera H⁺ → pH cai na rizosfera; absorção > ânions → planta libera OH⁻/HCO₃⁻ → pH sobe. Plantas fertizadas com NH₄⁺ acidificam a rizosfera; com NO₃⁻ tendem a elevar. Exsudatos radiculares importantes para mobilização de nutrientes: (1) ÁCIDO CÍTRICO e MÁLICO → quelam P ligado a Fe/Al, mobilizando P em solos ácidos; (2) FITOSSIDERÓFOROS (gramíneas) → quelam Fe³⁺, Zn²⁺, Cu²⁺ com alta afinidade; liberação máxima nas primeiras horas após amanhecer (ritmo circadiano) na zona sub-apical; (3) COMPOSTOS FENÓLICOS → redução de Fe³⁺ → Fe²⁺ (Estratégia I). Raízes cluster (lupino, proteáceas) sob deficiência de P = exsudação massiva de ácido cítrico em pulsos curtos → mobilização de P de até 1.000x maior que raízes normais. Microorganismos rizosféricos decompõem exsudatos rapidamente (meia-vida 6-12h para ácidos orgânicos) → a zona exatamente atrás do ápice radicular, onde a densidade microbiana é baixa, é o local mais eficiente de exsudação. Micorrizas ampliam ainda mais a rizosfera funcional.',
 'Marschner, H. (Ed.) (2012). Marschner''s Mineral Nutrition of Higher Plants. 3rd ed. Academic Press, London.',
 '{rizosfera, exsudatos, pH, citrato, malato, fitossideróforo, P, Fe, Zn, NH4, NO3, micorriza, cluster root, acidificação}');
