-- ─── MARSCHNER'S MINERAL NUTRITION — BORO, MICORRIZAS E FÓSFORO ──────────────
-- 3ª Ed. (2012) — B function/deficiency/toxicity by crop; AM/ECM mycorrhizae; P acquisition
-- ─────────────────────────────────────────────────────────────────────────────

insert into public.conhecimento (titulo, tipo, cultura, conteudo, fonte, tags) values

('Marschner — Boro (B): funções, deficiência por cultura e toxicidade',
 'artigo', 'all',
 'BORO (B) — FUNÇÕES PRIMÁRIAS: B forma ésteres com cis-dióis em polissacarídeos pécticos da parede celular (apiose do Rhamnogalacturonano II, RGII). A formação de dímeros B-dRGII cross-linked é a função central de B; sua ausência leva a parede celular com poros maiores, inibição de elongação celular e cascata de defeitos metabólicos secundários. B estabiliza membranas plasmáticas (formação de rafts de glicoesfingolipídeos). Em leguminosas, B é essencial para infecção por Rhizobium, organogênese de nódulos e maturação de bacteroides. REQUERIMENTO: dicotiledôneas requerem 20-70 ppm B foliar vs. gramíneas 5-10 ppm (teor de pectina na parede celular é maior em dicots). Concentração crítica de deficiência: trigo e milho = 5-10 ppm B foliar; soja, algodão, alfafa = 20-50 ppm; beterraba, cenoura = 50-100 ppm. DEFICIÊNCIA POR CULTURA: folhas jovens e meristemas são os primeiros afetados (B imóvel em maioria das culturas). Meristema apical para de crescer → roseta de folhas pequenas e deformadas. Internódios curtos ("bushy appearance"). Flores e frutos abortam — B crítico para crescimento do tubo polínico e viabilidade do pólen. Em milho: atraso de espigamento, anteras estéreis, grãos pequenos e sem amido. Em algodão: elongação das fibras do ovário cessa a partir da antese (B controla extensão de células epidérmicas). Em beterraba: coração podre e crown rot (Fig. 7.34). Em fruteiras: cortiça interna (internal cork) em maçã; rachadura em citrus. Em leguminosas: nodulação deficiente, nódulos com parede celular alterada, semente com menor viabilidade. TOXICIDADE DE B: clorose e necrose nas margens e ápices das folhas mais velhas (B acumula no xilema conforme transpiração). Concentrações críticas de toxicidade: milho 100 ppm; trigo 100-270 ppm; algodão 330 ppm; pepino 400 ppm; abóbora 1.000 ppm. Tolerância é determinada principalmente por transportadores de efluxo (família BOR) nas raízes. FONTES E MANEJO: bórax (borato de sódio, 10% B), ácido bórico — aplicar 0,3 a 3 kg B/ha solo ou foliar (atenção: janela estreita entre deficiência e toxicidade). B lixivia facilmente em solos arenosos com alta precipitação.',
 'Marschner, H. (Ed.) (2012). Marschner''s Mineral Nutrition of Higher Plants. 3rd ed. Academic Press, London.',
 '{B, boro, parede celular, pectina, RGII, meristema, nodulação, Rhizobium, milho, soja, algodão, beterraba, toxicidade, boro foliar}'),

('Marschner — Micorrizas arbusculares (AM) e ectomicorrizas (ECM): nutrição de P e Zn',
 'artigo', 'all',
 'MICORRIZAS (Marschner Cap. 15): ~83% das plantas dicot e monocot são micorrízicas; todas as gimnospermas são ECM. Não formam micorriza: Cruciferae (brássicas), Chenopodiaceae e algumas Proteaceae (formam cluster roots). TIPOS: AM (Endomicorriza Arbuscular, antiga VAM) — Glomeromycota; Glomus, Acaulospora, Gigaspora — penetram células corticais via arbúsculos e hifas intercalares; hifas externas se estendem para além da rizosfera. ECM (Ectomicorriza) — Basidiomycetes/Ascomycetes; formam manto fúngico e rede de Hartig entre células corticais; predominam em Pinaceae, Betulaceae, Fagaceae; hifas externas (rizomorfos) podem chegar a > 10 cm do eixo radicular. MECANISMO DE AUMENTO DE P: hifas AM (diâmetro 1-12 μm) acessam poros do solo inacessíveis às raízes; zona de depleção de P se estende até 11 cm da rizoplana vs. 1-2 cm em raízes não-micorrízicas (Li et al., 1991). Taxa de absorção de P por unidade de comprimento radicular = 2-3x maior em plantas micorrízicas. P transportado nas hifas como polifosfato (poli-P) em vacúolos móveis → hidrolisado por fosfatase nos arbúsculos. AM também absorvem P orgânico via fosfatases ácidas externas. CUSTO CARBÔNICO: AM = 4-20% do carbono fixado; respiração raiz+fungo pode ser 20-30% maior que raízes não-micorrízicas. ECM em florestas de Douglas-fir = 60-70% de fotoassimilados alocados abaixo do solo. COLONIZAÇÃO vs. ADUBAÇÃO: colonização por AM é reduzida com altos teores de P ou N no solo (solo com P alto → menos necessidade de colonização, mas total de raízes micorrízicas pode ser alto pelo maior crescimento radicular). MICRONUTRIENTES: AM também aumentam absorção de Zn e Cu (baixa mobilidade no solo). Em soja micorrízica: Cu foliar 10 ppm vs. 3 ppm em não-micorrízica; Zn 44 vs. 21 ppm (sem adubação de P). MANEJO: plantio convencional com aração profunda, calagem excessiva ou uso contínuo de defensivos pode reduzir propágulos de AM. Plantio direto favorece AM. Inoculação com AM pode ser benéfica em solos degradados ou em mudas de citrus, fruteiras e espécies florestais.',
 'Marschner, H. (Ed.) (2012). Marschner''s Mineral Nutrition of Higher Plants. 3rd ed. Academic Press, London.',
 '{micorriza, AM, VAM, ECM, ectomicorriza, P, Zn, Cu, hifa, arbúsculo, fosfato, depleção, plantio direto, inoculação, soja, milho, citrus}'),

('Marschner — Manganês (Mn): fotossíntese, toxicidade em solos ácidos e redutores',
 'artigo', 'all',
 'MANGANÊS (Mn) — FUNÇÕES: componente do cluster Mn₄CaO₅ no PS II (fotossíntese — evolução de O₂ pela fotólise da água); ativador de enzimas (descarboxilases, desidrogenases, cinases); envolvido na síntese de clorofila e síntese de aminoácidos aromáticos (shikimato desidrogenase). DEFICIÊNCIA (Mn imóvel → sintomas em folhas jovens): clorose internerval em folhas jovens; PS II é o processo mais sensível a Mn — redução > 50% na evolução de O₂ fotoesintético com queda de Mn em trevo subterrâneo, sem variação proporcional na clorofila. Em trigo e milho: fotossíntese suprimida antes de qualquer sintoma visual. "Gray speck" em aveia; "Marsh spot" em ervilha; "Speckled yellows" em beterraba. TOXICIDADE (solos ácidos com pH < 5,5 e/ou mal drenados): Mn⁴⁺ é reduzido a Mn²⁺ solúvel em condições redutoras (solo encharcado). Mn²⁺ compete com Mg²⁺ pela ligação ao ATP (Mn² se liga 4x mais fortemente → interfere no Mg-ATP como transmissor de energia). A maior parte do Mn²⁺ excessivo é sequestrada nos vacúolos e vesículas de Golgi. Sintoma clássico = "crinkle leaf" no algodão; manchas necróticas com halos cloróticos nas folhas velhas (mais velhas pois Mn se acumula com a transpiração). > 500-1.000 ppm Mn no tecido = tóxico para culturas sensíveis. MICROBIOLOGIA RIZOSFÉRICA: bactérias oxidantes de Mn (Arthrobacter spp.) imobilizam Mn; bactérias redutoras (pseudomonads fluorescentes) liberam Mn²⁺ no solo — o balanço desses grupos controla a disponibilidade de Mn na rizosfera. Calagem eleva pH → precipita Mn como MnO₂ (insolúvel). Mg alto atenua toxicidade de Mn por competição no uptake.',
 'Marschner, H. (Ed.) (2012). Marschner''s Mineral Nutrition of Higher Plants. 3rd ed. Academic Press, London.',
 '{Mn, manganês, fotossíntese, PS II, gray speck, crinkle leaf, toxicidade, acidez, encharcamento, Mg, calagem, rizosfera, aveia, algodão}'),

('Marschner — Cobre (Cu): funções, deficiência e toxicidade em culturas',
 'artigo', 'all',
 'COBRE (Cu) — FUNÇÕES: componente de proteínas de transporte de elétrons em fotossíntese (plastocianina) e respiração (citocromo c oxidase); superóxido dismutase (Cu/Zn-SOD); lacases (lignificação); metaloproteínas envolvidas em detoxificação de etileno. Cu é necessário para a formação de clorofila e para a estabilidade de cloroplastos. DEFICIÊNCIA (Cu imóvel → sintomas em folhas jovens): folhas jovens com coloração azul-esverdeada escura → verde pálido → clorose e enrolamento. Em cereais: "withtipping" — pontas das folhas jovens esbranquiçadas, folhas jovens estreitas e enroladas; redução de perfilhamento; em deficiência severa = grãos murchos ou ausentes. Em trigo: esterilidade das espigas ("blindness"). Cu deficiência aumenta sensibilidade a doenças fúngicas (Fusarium, Gaeumannomyces). Em fruteiras perenes: "exantema" (morte de ponteiros e surgimento de exsudatos gomosos). Concentrações críticas: < 4-5 ppm Cu foliar = deficiência; 5-20 ppm = suficiência; > 30 ppm = potencialmente tóxico para espécies sensíveis. TOXICIDADE: alta dose de Cu (>30 ppm solução ou > 400 ppm no solo) → raízes curtas e marrons, sintomas de deficiência de Fe por antagonismo. Cu tóxico em solos com histórico de calda bordalesa (vinhedos). ECM em coníferas retém Cu excessivo no micélio → aumenta tolerância do hospedeiro. MOBILIDADE: Cu tem mobilidade moderada a baixa no floema; redistribuição de folhas velhas para grãos ocorre durante senescência. Em trigo, o conteúdo de Cu no grão depende da redistribuição das folhas (não da absorção durante enchimento do grão).',
 'Marschner, H. (Ed.) (2012). Marschner''s Mineral Nutrition of Higher Plants. 3rd ed. Academic Press, London.',
 '{Cu, cobre, plastocianina, lignificação, SOD, withtipping, esterilidade, trigo, cereais, toxicidade, ECM, calda bordalesa, Fe, antagonismo}');
