-- ─── HAVLIN et al. — FÓSFORO E POTÁSSIO NO SOLO E NA PLANTA ─────────────────
-- Soil Fertility and Fertilizers, 8ª ed. (2017) — P cycle, soil forms, K functions/deficiency
-- ─────────────────────────────────────────────────────────────────────────────

insert into public.conhecimento (titulo, tipo, cultura, conteudo, fonte, tags) values

('Havlin et al. — Ciclo do P, formas no solo e disponibilidade para as plantas',
 'artigo', 'all',
 'FÓSFORO NO SOLO — FORMAS (em ordem crescente de disponibilidade): (1) P em solução (H₂PO₄⁻ em pH < 7,2; HPO₄²⁻ predomina em pH > 7,2) — 0,001 a 1 ppm; (2) P fracamente adsorvido (lábil) — dessorve rapidamente para a solução; (3) P fortemente adsorvido (não lábil) — superfícies de óxidos de Fe/Al e argilas em solos ácidos; superfícies de CaCO₃ e Ca-P em solos alcalinos; (4) Minerais de P — Ca-P (apatita — solos alcalinos), Fe/Al-P (solos ácidos). Total de P no solo: 0,005 a 0,15%, sem correlação com P disponível. P disponível para a planta = P em solução + P lábil. Difusão do H₂PO₄⁻ no solo = 0,13 mm/dia (10× mais lenta que K⁺ e 23× mais lenta que NO₃⁻) → P deve ser reposto ≈ 10 vezes por dia na solução do solo para atender a demanda de milho com 0,3 ppm P. P É IMÓVEL NO SOLO → adubação em banda (sulco de semeadura) é mais eficiente que a lanço porque coloca P onde as raízes jovens crescem. pH ÓTIMO PARA P: 5,5 a 6,8 — abaixo de 5,5, P precipita com Fe/Al; acima de 6,8-7,0, Ca-P e Mg-P formam-se em solos calcários. FORMAS DE P NAS PLANTAS: absorvido como H₂PO₄⁻ ou HPO₄²⁻; teor foliar 0,1-0,5% MS. Funções: (a) energia (ATP/ADP — cada mol de ATP libera 12.000 cal ao ser hidrolisado); (b) DNA e RNA (código genético, síntese de proteínas); (c) fosfolipídios de membrana; (d) coenzimas (NAD, NADP). DEFICIÊNCIA VISUAL: crescimento reduzido; coloração verde-escura → verde-acinzentado-azulado metálico (acúmulo de açúcares + síntese de antocianinas → cor roxa nas bordas das folhas velhas progredindo para toda a folha); raízes menores; maturação tardia. P frio: solos frios (<15°C) reduzem difusão de P e crescimento radicular → sintomas em plantas jovens mesmo com P disponível → starter P no sulco previne. Micorriza VAM aumenta volume de solo explorado para P — raízes VAM-dependentes têm baixa superfície radicular, poucos pelos radiculares e lenta taxa de crescimento.',
 'Havlin, J.L.; Tisdale, S.L.; Nelson, W.L.; Beaton, J.D. (2017). Soil Fertility and Fertilizers: An Introduction to Nutrient Management. 8th ed. Pearson.',
 '{P, fósforo, ATP, ADP, solo, difusão, adsorção, Fe-P, Al-P, Ca-P, pH, antocianina, imóvel, banda, sulco, VAM, micorriza, starter}'),

('Havlin et al. — Potássio (K): funções na planta, formas no solo e deficiência por cultura',
 'artigo', 'all',
 'POTÁSSIO — FUNÇÕES (K⁺ não é componente de compostos bioquímicos estruturais — age em solução): (1) FOTOSSÍNTESE E ENERGIA: K é essencial para síntese de ATP (fotofosforilação) e atividade de RuBP carboxilase; aumento de K → maior absorção de CO₂ por maior abertura estomática; milho requer 2% de K foliar e alfafa > 3% para fotossíntese ótima. (2) ATIVAÇÃO ENZIMÁTICA: estarch sintase (açúcar → amido em grãos, frutas, tubérculos) e nitrogenase (K melhora suprimento de carboidratos para nódulos de Rhizobium). (3) TRANSLOCAÇÃO DE FOTOASSIMILADOS: cana-de-açúcar com K deficiente tem taxa de translocação na metade do normal (1,25 vs. 2,5 cm/min); K é co-transportador (counterion) do NO₃⁻ no xilema. (4) RELAÇÕES HÍDRICAS: K mantém turgor e regula abertura estomática (influxo de K⁺ nas células guarda → abertura do estoma); plantas com K baixo perdem mais água e são menos resistentes à seca. DEFICIÊNCIA VISUAL (K é móvel → sintomas começam nas folhas velhas): clorose e necrose nas margens/bordas de folhas velhas em gramíneas (milho, sorgo); manchas brancas nas bordas de folhas velhas em alfafa; em algodão e soja: necrose internerval nas folhas velhas. Sintoma adicional crítico: ACAMAMENTO de colmos e tombamento em milho e sorgo (K essencial para resistência mecânica dos colmos) → perdas de colheita. K deficiente aumenta suscetibilidade a fungos (Diaporthe sojae em soja), bactérias e insetos. FORMAS NO SOLO (em ordem de disponibilidade): K solução (1-10 ppm) → K trocável (40-600 ppm) → K não-trocável (50-750 ppm) → K mineral feldspatos/micas (5.000-25.000 ppm). K trocável e K solução equilibram-se rapidamente; K não-trocável equilibra-se lentamente. DIFUSÃO: K se move por difusão até 1-4 mm ao redor da raiz (90% do K absorvido). Solos com argila esmectítica (vermiculita) têm alta BC para K; solos arenosos com caulinita têm baixa BC → K lixivia mais facilmente em arenosos. K⁺ em solução é reduzido por Ca²⁺ e Mg²⁺ em excesso (antagonismo iônico).',
 'Havlin, J.L.; Tisdale, S.L.; Nelson, W.L.; Beaton, J.D. (2017). Soil Fertility and Fertilizers: An Introduction to Nutrient Management. 8th ed. Pearson.',
 '{K, potássio, ATP, estoma, acamamento, fotossíntese, translocação, nitrogenase, RuBP, difusão, trocável, vermiculita, milho, soja, alfafa, seca}'),

('Havlin et al. — Enxofre (S): funções, formas no solo e deficiência nas culturas',
 'artigo', 'all',
 'ENXOFRE (S) — FUNÇÕES: constituinte de aminoácidos sulfurados (cisteína, metionina) e proteínas; componente de coenzimas (CoA, tiamina, biotina); ativação de enzimas que requerem grupos -SH; constituinte de glucosinolatos em Brassicaceae (responsáveis pelo sabor pungente). S é componente de ferredoxina (transporte de elétrons em fotossíntese e FBN). MOBILIDADE: S varia entre espécies — pode ser móvel (sintomas em folhas velhas) ou imóvel (sintomas em folhas novas) dependendo da situação nutricional de N. Quando N é adequado, planta exige mais S para síntese de aminoácidos S → sintomas em folhas jovens. Quando N é limitante, S redistribuído das folhas velhas. FORMAS NO SOLO: (1) S orgânico (50-95% do total em solos de clima úmido) — mineralizado a SO₄²⁻ por micro-organismos; (2) S mineral adsorvido em óxidos de Al/Fe (em solos ácidos) ou precipitado como CaSO₄ (gesso) em solos áridos; (3) SO₄²⁻ em solução. SO₄²⁻ é um ânion relativamente móvel — pode lixiviar no perfil. Gesso agrícola (CaSO₄.2H₂O) = 17% S — correto para solos com tendência de toxicidade de Al no subsolo (S facilita lixiviação de Ca e reduz Al trocável em camadas abaixo de 30 cm). DEFICIÊNCIA: crescimento reduzido; plantas raquíticas; clorose generalizada (verde pálido); em crucíferas = cor avermelhada na face inferior das folhas jovens, folhas curvadas para dentro; flores pálidas; sementes com menor teor de proteína e óleo. Diagnose: quando solo tem menos de 10-12 ppm S-SO₄ no perfil até 30 cm de profundidade (solos arenosos e solos com baixo teor de MO são os mais deficientes em S). Em plantio direto com baixa mineralização → S pode tornar-se limitante.',
 'Havlin, J.L.; Tisdale, S.L.; Nelson, W.L.; Beaton, J.D. (2017). Soil Fertility and Fertilizers: An Introduction to Nutrient Management. 8th ed. Pearson.',
 '{S, enxofre, cisteína, metionina, aminoácido, gesso, sulfato, lixiviação, Brassica, crucífera, deficiência, solo, MO, mineralização}'),

('Havlin et al. — Cálcio e Magnésio: funções, sintomas de deficiência e antagonismos',
 'artigo', 'all',
 'CÁLCIO (Ca²⁺) — FUNÇÕES: estrutura da parede celular (pectato de Ca²⁺ cross-links); segundo mensageiro em respostas a estresses (Ca-calmodulina); estabilidade de membranas plasmáticas; germinação do grão de pólen e crescimento do tubo polínico; Ca torna membranas menos permeáveis. Ca é MUITO IMÓVEL no floema → sintomas sempre em folhas jovens, meristemas, frutos e raízes com baixa transpiração. SINTOMAS DE DEFICIÊNCIA: pontas e bordas de folhas jovens cloróticas e necróticas; em milho = mucilagem entre folhas jovens que ficam coladas; raízes curtas e escuras (necroses radiculares precoces); nodulação deficiente em leguminosas (nódulos brancos × rosa); blossom-end rot em tomate, pimenta, melão = Ca não chega aos frutos em rápido crescimento por baixa transpiração (frutos recebem Ca quase exclusivamente pelo xilema); bitter pit em maçã; black heart em amendoim e aipo; cavity em cenoura. MAGNÉSIO (Mg²⁺) — FUNÇÕES: centro da molécula de clorofila (Mg-porfirina); ativador de enzimas ATP-dependentes (Mg²⁺ forma complexo com ATP → Mg-ATP é o substrato real para cinases e ATPases); co-fator da RuBP carboxilase; carreador de P no floema (Mg-fosfato). Mg é MÓVEL → sintomas em folhas velhas. SINTOMAS DE DEFICIÊNCIA: clorose internerval em folhas velhas (nervuras verdes, espaços entre-nervuras amarelos ou avermelhados); em algodão = cor avermelhada-purpúrea progredindo para marrom e necrose em folhas velhas. Antagonismos importantes: excesso de K⁺ → reduz absorção de Mg²⁺ e Ca²⁺; excesso de Ca²⁺ → reduz absorção de Mg²⁺ e K⁺; calagem excessiva em solos ácidos = pode induzir deficiência de Mg e K; relação Ca:Mg no solo deve ser 3:1 a 7:1 (razão ideal no solo para gramíneas); relação K:(Ca+Mg) na planta > 2,5 = deficiência de Mg provável em pastagens (tetania de pastagem em ruminantes).',
 'Havlin, J.L.; Tisdale, S.L.; Nelson, W.L.; Beaton, J.D. (2017). Soil Fertility and Fertilizers: An Introduction to Nutrient Management. 8th ed. Pearson.',
 '{Ca, Mg, cálcio, magnésio, parede celular, clorofila, blossom-end rot, meristema, xilema, floema, K, antagonismo, clorose, folha velha, tomate, milho, soja}');
