-- ─── HAVLIN et al. — MICRONUTRIENTES: MANEJO E DISPONIBILIDADE ───────────────
-- Soil Fertility and Fertilizers, 8ª ed. (2017) — Fe, Zn, Cu, Mn, B — manejo prático
-- ─────────────────────────────────────────────────────────────────────────────

insert into public.conhecimento (titulo, tipo, cultura, conteudo, fonte, tags) values

('Havlin et al. — Ferro (Fe): disponibilidade no solo, quelatos e manejo',
 'protocolo', 'all',
 'FERRO — DISPONIBILIDADE NO SOLO: cada unidade de aumento de pH reduz Fe³⁺ em solução 1.000 vezes e Fe²⁺ 100 vezes. Em pH 7-8 (solos calcários), Fe total em solução é insuficiente para plantas mesmo em solos com alto Fe total. Mecanismo natural: quelatos orgânicos do solo (ácidos cítrico, oxálico, málico, tartárico, EDTA natural da MO) complexam Fe³⁺ → aumentam difusão até a raiz. Fe²⁺ aumenta drasticamente em solos encharcados (condições redutoras) → toxicidade foliar ("bronzing") em arroz inundado (>300 ppm Fe no tecido). SENSIBILIDADE À DEFICIÊNCIA — culturas sensíveis em solos calcários: soja, feijão, sorgo de grão, sorgo forrageiro, citrus, fruteiras, amendoim, girassol, espinafre. Culturas tolerantes: trigo, aveia, milho-doce, arroz, beterraba, batata. QUELATOS SINTÉTICOS (estabilidade por pH): Fe-EDDHA = estável em toda a faixa de pH (preferido para solos calcários, pH 7-8,5); Fe-DTPA = estável até pH 7,5; Fe-EDTA = instável acima de pH 6,5. MANEJO: (1) Solo calcário: Fe-EDDHA = fonte preferida (70% disponível após 14 semanas vs. 20% FeSO₄ após 1 semana); (2) Foliar: solução FeSO₄ 2% = 15-30 L/ha; repetir a cada 7-14 dias em deficiência severa; (3) Acidificação local: S elementar, tiossulfato de amônio ou H₂SO₄ em banda = reduz pH e aumenta Fe; (4) Solo ácido: FeSO₄ no sulco (30-70 kg Fe/ha) é eficaz. Em soja: selecionar variedades Fe-eficientes para solos calcários.',
 'Havlin, J.L.; Tisdale, S.L.; Nelson, W.L.; Beaton, J.D. (2017). Soil Fertility and Fertilizers: An Introduction to Nutrient Management. 8th ed. Pearson.',
 '{Fe, ferro, clorose, quelato, EDDHA, DTPA, EDTA, calcário, pH, bronzing, arroz, soja, FeSO4, foliar, inundação}'),

('Havlin et al. — Zinco (Zn): deficiência por cultura, fatores de solo e fontes',
 'protocolo', 'all',
 'ZINCO — DISPONIBILIDADE: redução de 30x na solução por unidade de pH entre pH 5-7 (adsorção em CaCO₃, óxidos Fe/Al e argilas). Abaixo de 10-20 ppm Zn foliar = deficiência; 25-150 ppm = suficiência; >400 ppm = toxicidade. CULTURAS DE ALTA SENSIBILIDADE: milho, feijão, citrus, fruteiras caducas, pecan, soja, arroz, cana-de-açúcar, amendoim. SENSIBILIDADE LEVE: alfafa, cevada, algodão, alface, batata, sorgo, beterraba, trigo. SINTOMAS POR CULTURA: milho — faixas brancas entre a nervura central e a borda das folhas jovens (manchas brancas características); grãos e cereais — clorose na nervura central na base de folhas jovens, redução de perfilhamento; fruteiras — roseta (folhas pequenas aglomeradas no ápice); em deficiência moderada os sintomas podem desaparecer com calor, mas maturity é retardada. FATORES DE SOLO: (a) calagem excessiva → aumenta adsorção de Zn em CaCO₃ e óxidos; (b) alta adubação fosfatada → pode induzir deficiência de Zn em solos marginais: P-Zn interagem → inibe micorriza que absorve Zn; (c) solo encharcado e ácido → Zn precipita como franklinita (ZnFe₂O₄) e ZnS; (d) solo rico em MO peat/muck: Zn complexado organicamente = deficiência; (e) solo arenoso: Zn lixivia facilmente. MANEJO: ZnSO₄ = fonte mais comum; 10 kg Zn/ha em solo argiloso ou 1-5 kg/ha em arenoso (eficácia por 2-3 safras). Banda é mais eficiente que lanço em solos argilosos e muito deficientes. Foliar com ZnSO₄ ou Zn-EDTA = mais eficaz que solo na maioria das situações.',
 'Havlin, J.L.; Tisdale, S.L.; Nelson, W.L.; Beaton, J.D. (2017). Soil Fertility and Fertilizers: An Introduction to Nutrient Management. 8th ed. Pearson.',
 '{Zn, zinco, deficiência, milho, fruteira, roseta, ZnSO4, calagem, P, micorriza, foliar, banda, solo, soja, arroz}'),

('Havlin et al. — Manganês (Mn) e Cobre (Cu): deficiência, toxicidade e fontes',
 'protocolo', 'all',
 'MANGANÊS — DISPONIBILIDADE: Mn²⁺ aumenta com pH ácido e com redução do solo (solo encharcado). Reduz 100x por unidade de pH. Mn²⁺ solúvel 0,01-1 ppm. Deficiência: < 15-20 ppm Mn foliar; toxicidade > 500-1.000 ppm. CULTURAS SENSÍVEIS A MN DEFICIENTE: aveia (gray speck), ervilha (marsh spot), beterraba (speckled yellows), soja, maçã, citrus, grãos de trigo, cebola. CULTURAS SENSÍVEIS A MN TÓXICO: algodão (crinkle leaf), feijão, soja em solos ácidos pH < 5,5 ou encharcados. MANEJO: MnSO₄ em banda (1-10 kg Mn/ha) ou foliar (mais eficaz); MnO² deve ser finamente triturado (pouco solúvel). Calagem corrige toxicidade de Mn; S elementar ou N-NH₄⁺ (acidificantes) corrigem deficiência em solos com pH alto. Quelatos de Mn em banda: NÃO usar em lanço (Ca ou Fe do solo deslocam Mn do quelato → Mn precipita). COBRE — DISPONIBILIDADE: Cu é o micronutriente mais fortemente adsorvido pela MO do solo (maior do que Fe, Zn ou Mn). Deficiência comum em solos turfosos e solos arenosos muito lixiviados. Deficiência: < 4 ppm Cu foliar; 5-20 ppm = suficiência; > 30 ppm → deficiência de Fe por antagonismo. CULTURAS SENSÍVEIS A CU DEFICIENTE: alfafa, trigo (não centeio que absorve 2x mais Cu), beterraba, citrus, cebola. Resistentes: feijão, soja, batata, gramíneas forrageiras. MANEJO: CuSO₄ em banda (1-5 kg Cu/ha em cereais; 2-4 kg/ha em soja) = preferido sobre foliar; residual por 2+ anos. Cuidado: esterco de suíno pode ter Cu excessivo (Cu adicionado na ração) → acúmulo no solo.',
 'Havlin, J.L.; Tisdale, S.L.; Nelson, W.L.; Beaton, J.D. (2017). Soil Fertility and Fertilizers: An Introduction to Nutrient Management. 8th ed. Pearson.',
 '{Mn, manganês, Cu, cobre, gray speck, crinkle leaf, MnSO4, CuSO4, toxicidade, acidez, soja, trigo, algodão, aveia}'),

('Havlin et al. — Boro (B): mobilidade por espécie, deficiência e manejo',
 'protocolo', 'all',
 'BORO — MOBILIDADE ENTRE ESPÉCIES: B é IMÓVEL na maioria das culturas (sintomas em meristemas e folhas jovens). ESPÉCIES COM B IMÓVEL: alfafa, milho, algodão, feijão, amendoim, batata, sorgo, beterraba, tomate, trigo. ESPÉCIES COM B MÓVEL (transportam B no floema junto com polióis como sorbitol): maçã, pêra, pessego, cereja, ameixa, cenoura, brócolis, couve-flor, aspargo — toxicidade por B aparece nas bordas de folhas velhas (acúmulo pelo transpiração), deficiência em meristemas. REQUERIMENTO: dicots = 20-60 ppm B foliar; monocots = 6-18 ppm. Deficiência abaixo de 20 ppm em maioria das culturas; toxicidade > 200 ppm. Relação Ca:B > 1.200:1 na folha = deficiência provável. SENSIBILIDADE À DEFICIÊNCIA — ALTA: alfafa, algodão, brócolis, couve-flor, canola, beterraba, amendoim, girassol, nabo, rutabaga. BAIXA: soja, milho, trigo, aveia, cevada, arroz, batata, gramíneas forrageiras. FATORES DE SOLO: (a) pH > 6,5 reduz B disponível — liming novo precipita B em Al(OH)₃ recém-formado; (b) solos arenosos com baixa MO = deficiência comum (B lixivia facilmente — até 80% em areia); (c) solos secos reduzem transporte de B por massa de fluxo e difusão. FONTES: bórax (Na₂B₄O₇·10H₂O) = 11% B; boric acid = 17% B; Solubor (octaborato de sódio) = 20-21% B (preferido por ser mais solúvel). DOSES: lanço 0,5-3 kg B/ha para maioria das culturas; leguminosas e crucíferas requerem mais; foliar = 0,1-0,3 kg B/ha em soja/milho; 0,5-1 kg B/ha em alfafa. ATENÇÃO: janela estreita deficiência-toxicidade → não aplicar em banda próxima à semente.',
 'Havlin, J.L.; Tisdale, S.L.; Nelson, W.L.; Beaton, J.D. (2017). Soil Fertility and Fertilizers: An Introduction to Nutrient Management. 8th ed. Pearson.',
 '{B, boro, mobilidade, bórax, Solubor, alfafa, algodão, milho, soja, meristema, toxicidade, pH, areia, liming, Ca}');
