-- ─── HAVLIN et al. — Mo, Cl, ANÁLISE DE SOLO E ANÁLISE FOLIAR ───────────────
-- Soil Fertility and Fertilizers, 8ª ed. (2017) — Mo/Cl/Ni functions; soil/plant analysis
-- ─────────────────────────────────────────────────────────────────────────────

insert into public.conhecimento (titulo, tipo, cultura, conteudo, fonte, tags) values

('Havlin et al. — Molibdênio (Mo): disponibilidade, FBN e manejo',
 'protocolo', 'all',
 'MOLIBDÊNIO — FUNÇÕES: (1) componente da nitrogenase → FBN em leguminosas (nodules têm > 10x mais Mo que as folhas); (2) componente da nitrato redutase → redução de NO₃⁻ → NO₂⁻ em todas as plantas; Mo-deficiência → acúmulo de NO₃⁻ e sintomas similares à deficiência de N (clorose foliar generalizada, folhas velhas e medianas primeiro); (3) papel na absorção e translocação de Fe → clorose internerval em solos com Mo baixo pode imitar deficiência de Fe. DISPONIBILIDADE: Mo é o único micronutriente cuja disponibilidade AUMENTA com o pH (10x por unidade de pH) — oposto a todos os outros. Calagem → aumenta Mo disponível; pH < 5,5 = Mo precipitado em óxidos de Fe/Al (solos muito intemperizados = baixo Mo disponível). SO₄²⁻ compete com MoO₄²⁻ pelos mesmos transportadores → adubação com enxofre em solos com Mo marginal pode induzir deficiência de Mo. NO₃⁻ e Mg aumentam absorção de Mo; Cu e Mn reduzem. SENSIBILIDADE À DEFICIÊNCIA: ALTA — alfafa, leguminosas em geral, brócolis, couve-flor, repolho, alface, canola, espinafre. BAIXA — trigo, milho, arroz, sorgo, batata, feijão, soja. TOXICIDADE PARA ANIMAIS: molibdenose em bovinos quando foragem tem > 5 ppm Mo (desbalanço Mo:Cu). Alerta em solos argilosos, úmidos, pH alto e rico em MO. MANEJO: doses muito baixas — molibdato de amônio (54% Mo) ou molibdato de sódio (39% Mo): 12-25 g Mo/ha via semente (antes da inoculação com rizóbio); 25-50 g Mo/ha via foliar. Tratamento de sementes com Na-molibdato = método mais eficiente e econômico. Solo: 0,03-1 lb Mo/ha = eficaz por 2-4 anos. Calagem para pH 5,5-6,0 geralmente resolve deficiência de Mo em solos ácidos.',
 'Havlin, J.L.; Tisdale, S.L.; Nelson, W.L.; Beaton, J.D. (2017). Soil Fertility and Fertilizers: An Introduction to Nutrient Management. 8th ed. Pearson.',
 '{Mo, molibdênio, nitrogenase, nitrato redutase, FBN, soja, alfafa, leguminosa, pH, calagem, molibdato, semente, foliar, molibdenose}'),

('Havlin et al. — Cloro (Cl): função, deficiência e supressão de doenças em cereais',
 'artigo', 'all',
 'CLORO (Cl⁻) — FUNÇÕES PRINCIPAIS: (1) osmorregulaçao e balanço de cargas em células e vacúolos (contraíon para K⁺ em células guarda → abertura estomática); (2) fotossíntese — Cl⁻ é necessário para a função do Mn no PS II (evolução de O₂); 10% do Cl⁻ celular está nos cloroplastos; (3) turgor celular — deficiência causa murchamento das folhas. Cl⁻ é um ânion muito móvel no solo → leacha facilmente com água. Concentração normal em plantas: 0,2-2%; teor mínimo nutritivo: 70-700 ppm; toxicidade em culturas sensíveis a partir de 0,5% Cl no tecido. DEFICIÊNCIA: rara em áreas com deposição atmosférica de Cl (região costeira: > 10 kg Cl/ha/ano; interior USA: 0,5-5 kg Cl/ha/ano). Culturas SENSÍVEIS: leguminosas, citrus, abacate, pêssego, batata, alface. ALTAMENTE TOLERANTES: cevada, milho, beterraba, tomate, espinafre. SUPRESSÃO DE DOENÇAS: Cl⁻ em trigo de inverno e primavera reduz significativamente: take-all (Gaeumannomyces graminis), Septoria, tan spot e outras doenças radiculares. Mecanismo: (a) Cl⁻ inibe nitrificação → mais NH₄⁺ no solo → pH rizosférico menor → suprime fungo; (b) competição entre Cl⁻ e NO₃⁻ → planta absorve mais NH₄⁺ que favorece sistemas de defesa. Probabilidade de resposta a Cl em trigo: quando solo com < 30 lb Cl/ha (0-60 cm) = 69% de chances de resposta; 31-60 lb/ha = 31%; > 60 lb/ha = 0%. FONTES: KCl (47% Cl, mais barato e comum); NH₄Cl, CaCl₂, MgCl₂ e NaCl. Aplicar 30-50 lb Cl/ha em solos baixos em Cl. Em solos com excesso de Cl (irrigação com água salina) → problemas de fitotoxicidade.',
 'Havlin, J.L.; Tisdale, S.L.; Nelson, W.L.; Beaton, J.D. (2017). Soil Fertility and Fertilizers: An Introduction to Nutrient Management. 8th ed. Pearson.',
 '{Cl, cloro, osmorregulaçao, PS II, trigo, take-all, Septoria, disease suppression, KCl, deficiência, salinidade, cereais}'),

('Havlin et al. — Análise de solo: interpretação e recomendação de fertilizantes',
 'protocolo', 'all',
 'ANÁLISE DE SOLO — PRINCÍPIOS: o objetivo é estimar a disponibilidade de nutrientes para a planta durante a safra. Os nutrientes são classificados por mobilidade para fins de recomendação: NUTRIENTES MÓVEIS (N, S, B, Cl): movimento por difusão e massa de fluxo; o tempo de aplicação é mais crítico que a localização; aplicar próximo à semeadura ou em cobertura. NUTRIENTES IMÓVEIS (P, K, Zn, Cu, Mn, Fe): aplicar em banda perto da raiz ou incorporar ao solo para maximizar contato raiz-adubo. SISTEMAS DE INTERPRETAÇÃO: (1) Abordagem de suficiência — comparar teor de solo com nível crítico → abaixo do crítico aplicar; acima não é necessário (Mehlich-3, Bray-1 para P; AA-acetato de amônio para K trocável). (2) Abordagem de acumulação e manutenção — calcula exportação pela colheita + perdas → repor anualmente. RECOMENDAÇÃO DE P imóvel: banda = mais eficiente que lanço porque concentra P na zona de absorção. Residual de P aplicado: acumula no solo por vários anos; produtividade em solos com alto P residual não responde à adubação de P. RECOMENDAÇÃO DE K: depende do CTC do solo e do teor K trocável. Solos arenosos com CTC baixa precisam de doses menores e mais frequentes. Solo com CTC alta retém mais K trocável e buffer K em solução melhor. CUIDADOS: (a) amostrar no mesmo período do ano para comparabilidade histórica; (b) reamostrar a cada 2-4 anos; (c) análise foliar complementa análise de solo para micronutrientes; (d) análise de solo não é confiável para N mineral — variabilidade temporal alta; calibrar N pelo histórico de cultura + MO + cultura antecedente.',
 'Havlin, J.L.; Tisdale, S.L.; Nelson, W.L.; Beaton, J.D. (2017). Soil Fertility and Fertilizers: An Introduction to Nutrient Management. 8th ed. Pearson.',
 '{análise de solo, interpretação, recomendação, P, K, N, banda, suficiência, móvel, imóvel, CTC, residual, amostragem}'),

('Havlin et al. — Análise foliar: nível crítico, amostragem e interpretação por cultura',
 'protocolo', 'all',
 'ANÁLISE FOLIAR — PRINCÍPIOS: concentração de um nutriente na folha reflete o status nutricional da planta mais diretamente que análise de solo. Diagnóstico precoce (antes dos sintomas visuais) = fome oculta identificável. CONCEITO DE NÍVEL CRÍTICO: concentração foliar abaixo da qual há resposta à adubação; geralmente corresponde a 80-90% da produtividade máxima. Faixas de suficiência de macronutrientes em folha de soja (diagnóstico): N = 4,5-5,5%; P = 0,25-0,50%; K = 1,7-2,5%; Ca = 0,35-2,0%; Mg = 0,25-1,0%; S = 0,20-0,40%. MICRONUTRIENTES EM SOJA (suficiência foliar): Fe = 50-300 ppm; Mn = 20-100 ppm; Zn = 25-50 ppm; Cu = 6-15 ppm; B = 20-55 ppm; Mo = 0,5-5 ppm. TIMING DA AMOSTRAGEM: crítico para comparabilidade — em soja amostrar o 3º ou 4º trifólio completamente expandido a partir do ápice (estádio R1-R2); em milho amostrar a folha oposta e abaixo da espiga (VT-R1). INTERPRETAÇÃO: nutrientes móveis (N, P, K, Mg, Mo) — concentração nas folhas velhas declina durante enchimento de grãos (redistribuição) → amostrar folhas definidas e no momento padrão. Nutrientes imóveis (Ca, Fe, Mn, Zn, Cu) — concentração nas folhas velhas aumenta com maturidade. Análise foliar sem análise de solo não permite diagnóstico completo → combinação das duas é o padrão ouro de diagnose. Eficiência de nutrientes = produtividade por unidade de nutriente absorvido; genótipos com alta eficiência absorvem e/ou utilizam melhor o nutriente.',
 'Havlin, J.L.; Tisdale, S.L.; Nelson, W.L.; Beaton, J.D. (2017). Soil Fertility and Fertilizers: An Introduction to Nutrient Management. 8th ed. Pearson.',
 '{análise foliar, nível crítico, suficiência, soja, milho, amostragem, N, P, K, Ca, Mg, Fe, Zn, Mn, Cu, B, Mo, diagnose}');
