-- ─── MARSCHNER'S MINERAL NUTRITION — SOLOS ENCHARCADOS E DIAGNOSE VISUAL ────
-- 3ª Ed. (2012) — Sec. 17.4: waterlogged soils, redox sequence, Fe/Mn toxicity, rice Zn
-- ─────────────────────────────────────────────────────────────────────────────

insert into public.conhecimento (titulo, tipo, cultura, conteudo, fonte, tags) values

('Marschner — Solos encharcados: sequência redox e disponibilidade de nutrientes',
 'artigo', 'all',
 'Em solos encharcados, O₂ é depletado rapidamente → microorganismos usam outros aceptores de elétrons em sequência crescente de potencial redox: (1) Redução de O₂ (Eh > 812 mV) → solo aeróbico; (2) Desnitrificação (NO₃⁻ → NO₂⁻ → N₂O → N₂, Eh ~747 mV) → perda de N em solos encharcados com NO₃⁻; (3) Redução de Mn⁴⁺ → Mn²⁺ solúvel (Eh ~526 mV) — ocorre em dias após o alagamento em solos com alto Mn e baixo NO₃⁻; (4) Redução de Fe³⁺ → Fe²⁺ (Eh ~47 mV) — Fe²⁺ pode acumular até concentrações tóxicas; em solos ácidos a redução de Fe causa elevação do pH; em solos com FePO₄ → liberação de P (aumenta disponibilidade de P); (5) Redução de SO₄²⁻ → H₂S (Eh ~-221 mV) — H₂S é fitotóxico para raízes; precipita Zn, Cu, Fe e Cd como sulfetos (insolúveis) → pode causar deficiência de Zn em arroz alagado; (6) Redução de CO₂ → CH₄ (metano, Eh < -244 mV) — campos de arroz = fonte significativa de CH₄ (20-40 Tg/ano = ~11% das emissões globais). PRINCIPAIS EFEITOS NUTRICIONAIS: (a) Fe²⁺ acumula → toxicidade (bronzeamento) em arroz quando > 500 ppm Fe no tecido foliar; (b) Mn²⁺ acumula → toxicidade em dicotiledôneas sensíveis; (c) Deficiência de N por desnitrificação + redução de absorção radicular; (d) Deficiência de Zn em arroz irrigado: pH alto + HCO₃⁻ + formação de ZnS na rizosfera + precipitação de Zn nos óxidos de Fe oxidados na rizosfera. IMPLICAÇÕES: solos com palha incorporada antes do alagamento acumulam ácidos graxos de cadeia curta (acético, propiônico) e fenólicos → fitotóxicos para raízes; em arroz, ácidos fenilpropanoicos a < 50 μM inibem elongação radicular.',
 'Marschner, H. (Ed.) (2012). Marschner''s Mineral Nutrition of Higher Plants. 3rd ed. Academic Press, London.',
 '{encharcamento, redox, Fe, Mn, Zn, arroz, desnitrificação, H2S, CH4, FePO4, palha, sulfeto, pH, toxicidade, alagamento}'),

('Marschner — Adaptação de plantas ao encharcamento: aerênquima e nutrição',
 'artigo', 'all',
 'PLANTAS EM SOLOS ENCHARCADOS — RESPOSTAS E TOLERÂNCIA: espécies não-adaptadas (mesófitas — soja, milho, trigo, leguminosas) mostram sintomas em sequência: (1) murchamento e epinastia (dobramento das folhas para baixo) por acúmulo de etileno e redução da condutância hidráulica das raízes (redução de aquaporinas); (2) 2-5 dias: parada de crescimento das folhas mais jovens; (3) 5-7 dias: clorose e senescência das folhas mais velhas (deficiência de N por desnitrificação + baixa absorção radicular); (4) morte das raízes. TOLERÂNCIA AO ENCHARCAMENTO em leguminosas: feijão-fava > tremoço-amarelo > grão-de-bico > lentilha > ervilha (ordem decrescente). MECANISMOS DE ADAPTAÇÃO: (a) Aerênquima radicular — formação de canais de ar no córtex radicular por autólise de células, induzido por etileno; arroz de várzea (wetland rice) tem alta capacidade de aerênquima e O₂ liberado das raízes oxida a rizosfera (previne acúmulo de Fe²⁺, Mn²⁺ e H₂S tóxicos); (b) Raízes adventícias próximas à superfície — crescem acima da zona anaerôbica; (c) Elongação subaquática do colmo (em arroz) para manter folhas acima da água. NUTRIÇÃO EM ESPÉCIES ADAPTADAS (arroz de várzea): oxigênio liberado pelas raízes oxida o Fe²⁺ → Fe(OH)₃ → acidifica rizosfera → mobiliza Zn adsorvido nos óxidos de Fe → aumenta P solúvel de frações Ca-P ácidas. NH₄⁺ predomina em solos de arroz alagado (nitrificação inibida) → absorção de N como NH₄⁺ → acidifica a rizosfera. IMPACTO DE DEFICIÊNCIAS: deficiência de N por desnitrificação é o principal fator de perda de produtividade de soja em áreas com encharcamento temporal. Compensação com N (NO₃⁻ ou NH₄⁺) aplicado próximo às raízes novas pode reduzir os danos.',
 'Marschner, H. (Ed.) (2012). Marschner''s Mineral Nutrition of Higher Plants. 3rd ed. Academic Press, London.',
 '{aerênquima, arroz, encharcamento, etileno, tolerância, soja, leguminosa, NH4, desnitrificação, Fe, oxidação rizosfera, Zn, adaptação}'),

('Marschner — Diagnose visual de deficiências: padrão simétrico e gradiente foliar',
 'artigo', 'all',
 'DIAGNOSE VISUAL — PRINCÍPIO DO PADRÃO SIMÉTRICO: distúrbios nutricionais têm sempre padrão simétrico e gradiente regular entre folhas velhas e jovens. Folhas da mesma posição fisiológica (mesma idade) em uma planta mostram padrão de sintomas quase idêntico; há gradação marcada da severidade entre folhas velhas e jovens. DIFERENÇA ENTRE DISTÚRBIOS NUTRICIONAIS E DOENÇAS/PRAGAS: sintomas de doenças/pragas são assimétricos ou posicionados aleatoriamente nas plantas e dentro do campo (especialmente em fases avançadas de infecção). Para distinguir: verificar se há padrão de distribuição sistemático no campo; sintomas nutricionais = distribuição associada a variabilidade do solo (manchas no campo), bordas próximas a caleiros, etc. INFORMAÇÕES COMPLEMENTARES para diagnose: pH do solo, análise de solo, teor de umidade (seco/encharcado), condições climáticas (baixa temperatura ou geada), aplicações de fertilizantes, fungicidas ou pesticidas. DIAGNOSE SIMULTÂNEA DE DEFICIÊNCIA + TOXICIDADE: solos ácidos encharcados → toxicidade de Mn + deficiência de Mg podem ocorrer simultaneamente. Solos calcários → deficiência de Fe + Zn + Mn podem coexistir. LIMITAÇÃO DA DIAGNOSE VISUAL: frequentemente, quando sintomas visuais aparecem, perdas de rendimento já ocorreram e não são reversíveis (fome oculta). Análise foliar durante estádios vegetativos = diagnose precoce. PADRÃO ASSIMÉTRICO = indica dano mecânico, spray, doença ou praga (não nutricional). Sintoma nutricional = SEMPRE bilateral/simétrico nas folhas.',
 'Marschner, H. (Ed.) (2012). Marschner''s Mineral Nutrition of Higher Plants. 3rd ed. Academic Press, London.',
 '{diagnose, sintoma, padrão simétrico, doença, praga, deficiência, toxicidade, análise foliar, encharcamento, Mn, Mg, Fe, Zn}'),

('Marschner — Silício (Si): funções benéficas em gramíneas e arroz',
 'artigo', 'all',
 'SILÍCIO (Si) — ELEMENTO BENÉFICO (não essencial para todas as plantas, mas muito importante em gramíneas): Si é absorvido como ácido monosilícico H₄SiO₄ por transportadores específicos (família Lsi). CONCENTRAÇÕES: gramíneas acumulam 1-10% Si no tecido seco; dicotiledôneas acumulam muito menos (0,1-0,5%). Em arroz: Si é o elemento mineral mais abundante (10-15% da massa seca da palha). FUNÇÕES BENÉFICAS EM GRAMÍNEAS E ARROZ: (1) Rigidez mecânica dos colmos e folhas → resistência ao acamamento em cereais; folhas eretas em arroz aumentam interceptação de luz; (2) Resistência a fungos: Si na parede celular aumenta resistência mecânica à penetração de hifas de Pyricularia (brusone) e Helminthosporium em arroz; (3) Proteção contra toxicidade de Mn: Si nas paredes celulares reduz entrada de Mn²⁺ no simplasto → distribui Mn mais uniformemente e reduz dano oxidativo; (4) Proteção contra Al tóxico: Si complexa Al na parede celular → atenua toxicidade em solos ácidos; (5) Proteção contra insetos sugadores: Si epidérmico aumenta dureza → reduz pastejo por cigarrinha-das-pastagens e pulgões. DISPONIBILIDADE NO SOLO: Si disponível como H₄SiO₄ — solos com boa mineralogia de silicatos têm mais Si; solos muito intemperizados (Oxissolos) podem ser deficientes. Adubação com Si (escória de siderurgia, wollastonita) em cana-de-açúcar, arroz e milho pode aumentar produtividade e resistência a doenças. Si solúvel em solução de solo: 3-40 ppm — correto pH e evitar solos muito intemperizados para manter Si disponível.',
 'Marschner, H. (Ed.) (2012). Marschner''s Mineral Nutrition of Higher Plants. 3rd ed. Academic Press, London.',
 '{Si, silício, arroz, gramíneas, brusone, Pyricularia, acamamento, Mn, Al, resistência, cana, milho, toxicidade, inseto}');
