-- ─── MARSCHNER'S MINERAL NUTRITION — ACIDEZ DO SOLO: Al, Mn, ADAPTAÇÃO ────────
-- 3ª Ed. (2012) — Sec. 17.3: Al/Mn toxicity, ALMT/MATE tolerance, calagem management
-- ─────────────────────────────────────────────────────────────────────────────

insert into public.conhecimento (titulo, tipo, cultura, conteudo, fonte, tags) values

('Marschner — Toxicidade de Al em solos ácidos: mecanismos e sensibilidade por espécie',
 'artigo', 'all',
 'ACIDEZ DO SOLO — PRINCIPAIS FATORES LIMITANTES (Seção 17.3): solos ácidos (pH < 5,5) compreendem ~30% das terras agricultáveis não geladas; 75% desses solos também têm subsolo ácido. Em solos ácidos minerais, as principais limitações são: (1) toxicidade de prótons (H⁺), Al e Mn; (2) deficiência de Ca, Mg, P e Mo. Na América tropical: toxicidade de Al + deficiência de Ca/Mg ocorrem em > 70% dos solos ácidos; quase todos são deficientes em P ou têm alta capacidade de fixação de P. TOXICIDADE DE Al: Al³⁺ é pouco solúvel em pH > 5,5 (< 1 mg/L) mas aumenta fortemente abaixo de pH 5,5. Abaixo de pH 5,5, Al³⁺ desloca Mg²⁺ e Ca²⁺ dos sítios de troca de argilas (saturação de Al cresce). SINTOMA PRIMÁRIO: inibição do crescimento radicular — mensurável em horas após exposição (a zona de transição distal, DTZ, 1-2 mm do ápice radicular, é a mais sensível). Na parte aérea NÃO há sintomas visuais claros típicos de Al → a depressão do rendimento pode ocorrer sem sintomas evidentes na parte aérea (confunde diagnose com Mn que produz cloroses). Al³⁺ + Ca²⁺ + Mg²⁺: na presença de alta Al³⁺, Ca e Mg não conseguem competir por sítios na parede celular → deficiência secundária de Ca (mais em leguminosas) e Mg (mais em gramíneas e árvores). Al também inibe aquisição de P por redução do crescimento radicular e da superfície de absorção. SENSIBILIDADE DE ESPÉCIES (Al-tolerante → Al-sensível): MUITO TOLERANTES: centeio (rye), tremoço amarelo, arroz de sequeiro, feijão-caupi, amendoim, batata, mandioca. SENSÍVEIS: cevada, feijão-fava, milho, feijão-comum, trigo. Em solução nutritiva: concentração de Al que reduz 50% do crescimento de parte aérea varia de < 1 μM (espécies mais sensíveis) a > 30 μM (espécies resistentes). SPECTAS ADICIONAIS: Complexação orgânica de Al: ácidos orgânicos reduzem a fitotoxicidade de Al — capacidade detoxificante: citrato ≫ oxalato > malato > succinato. Substância orgânica e MO do solo complexam Al³⁺ → reduzem fitotoxicidade. Gessagem no subsolo forma AlSO₄⁺ (não-tóxico) e fornece Ca → atenua toxicidade de Al em camadas profundas.',
 'Marschner, H. (Ed.) (2012). Marschner''s Mineral Nutrition of Higher Plants. 3rd ed. Academic Press, London.',
 '{Al, alumínio, acidez, pH, solo ácido, toxicidade, raiz, Ca, Mg, P, centeio, milho, feijão, mandioca, trigo, cerrado}'),

('Marschner — Mecanismos de resistência ao Al: ALMT, MATE e exsudação de ácidos orgânicos',
 'artigo', 'all',
 'RESISTÊNCIA AO Al — MECANISMO PRINCIPAL: exsudação de ânions de ácidos orgânicos nas raízes (apical zone, DTZ), ativada pelo próprio Al³⁺ → complexação de Al³⁺ no apoplasto radicular = exclusão de Al. DOIS PADRÕES: (I) Padrão I — liberação IMEDIATA após exposição ao Al (transporte constitutivo, canal já formado); (II) Padrão II — liberação após período de latência de horas (requer expressão gênica e síntese de proteína). TRANSPORTADORES: (a) ALMT (Al-activated malate transporter) — facilita efluxo de MALATO das raízes; gene TaALMT1 no trigo — expressão transgênica de TaALMT1 em cevada Al-sensível confere alta resistência ao Al; (b) MATE (multidrug and toxin extrusion) — transportadores de CITRATO; importantes em sorgo (SbMATE), cevada (HvMATE) e outras espécies como feijão-comum (Padrão II); no feijão-common (genótipo Quimbaya — resistente) a exsudação de citrato mantida por 24h depende do pool interno de citrato e alta atividade de citrato sintase (CS); no genótipo sensível (VAX-1) o pool de citrato se esgota → Al exclusão falha. CITRATO vs. MALATO: 1 molécula de citrato pode neutralizar toda a toxicidade de Al em concentração 1:1 (Al:ligante), enquanto malato requer relação 1:8 → citrato é mais eficiente. OUTROS MECANISMOS: mucilagem da coifa radicular — capacidade de ligar Al 8x maior que o tecido radicular adjacente; redução da negatividade da parede celular (menor CEC radicular); em acumuladores de Al (chá Camellia sinensis, trigo-mourisco Fagopyrum esculentum, hortênsia) — acumulam > 1 mg Al/g PS em folhas, complexado com oxalato ou citrato no simplasto. PECTIN E PAREDE CELULAR: maior grau de metilação da pectina (DM) = menor ligação de Al na parede = maior resistência; variedades Al-sensíveis de milho e arroz têm pectina menos metilada → acumulam mais Al. CALAGEM vs. Al EM SUBSOLO: a calagem incorporada apenas nos primeiros 20 cm geralmente não corrige o subsolo ácido → raízes ficam restritas ao subsolo → estresse hídrico + deficiência de nutrientes do subsolo + perda de N por lixiviação.',
 'Marschner, H. (Ed.) (2012). Marschner''s Mineral Nutrition of Higher Plants. 3rd ed. Academic Press, London.',
 '{Al, resistência, ALMT, MATE, malato, citrato, exsudação, trigo, sorgo, cevada, feijão, pectina, mucilagem, exclusão, calagem}'),

('Marschner — Toxicidade de Mn em solos ácidos: diferenças em relação ao Al',
 'artigo', 'all',
 'TOXICIDADE DE Mn (Seção 17.3.4): Mn²⁺ (solúvel, fitotóxico) aumenta com: (a) queda de pH abaixo de 5,5; (b) queda do potencial redox (solo encharcado ou mal aerado); (c) alta atividade microbiana com decomposição de MO (solos com alta MO + anaerobiose temporária em leguminosas fixadoras de N₂). Fórmula: MnO₂ + 4H⁺ + 2e⁻ → Mn²⁺ + 2H₂O. DIFERENÇA CRÍTICA vs. TOXICIDADE DE Al: Al³⁺ fica nos tecidos radiculares → sintomas na RAIZ (sem sintoma visual típico na parte aérea); Mn²⁺ é translocado à parte aérea → sintomas aparecem PRIMEIRO nas folhas. SINTOMAS DE Mn TÓXICO: manchas cloróticas ou pardas em folhas velhas com halo clorótico (dicotiledôneas); "crinkle leaf" em algodão; em solos ácidos com Al + Mn simultaneamente, a depressão de rendimento pode ser erroneamente atribuída ao Mn quando o Al é o fator dominante. MECANISMO BIOQUÍMICO DE Mn TÓXICO: Mn²⁺ bloqueia sítios de ligação de Mg²⁺ nas raízes → deficiência induzida de Mg; também compete com Ca²⁺ → em solos ácidos com alta atividade de Mn²⁺, fornecimento de Mg (calcário dolomítico) reduz toxicidade de Mn. TOLERÂNCIA: (a) sequestração de Mn em vacúolos/Golgi; (b) distribuição uniforme de Mn no apoplasto foliar (em feijão-caupi tolerante, Mn distribuído uniformemente sem acúmulo local). Si aumenta fortemente a tolerância ao Mn no tecido foliar. LEGUMINOSAS: nodulação é a etapa mais sensível à toxicidade de Mn em solos ácidos — comprometida pela combinação de Al alto + Mn alto + baixo Ca + baixo P → perda da fixação biológica de N₂ em leguminosas em solos ácidos não corrigidos. Em solos tropicais muito intemperizados (Oxissolos), Mn total é baixo → deficiência de Mn pode ocorrer após calagem. CALAGEM para Mn: eficaz porque eleva pH → precipita MnO₂ (insolúvel). DIAGNOSE DIFERENCIAL Al vs. Mn: toxicidade de Al = raízes escuras e curtas, sem sintoma visual claro em folhas; toxicidade de Mn = manchas/cloroses em folhas velhas.',
 'Marschner, H. (Ed.) (2012). Marschner''s Mineral Nutrition of Higher Plants. 3rd ed. Academic Press, London.',
 '{Mn, manganês, toxicidade, acidez, Al, calagem, leguminosa, nódulo, feijão-caupi, algodão, Si, Mg, diagnose diferencial}'),

('Marschner — Calagem e gessagem em solos ácidos: manejo integrado',
 'protocolo', 'all',
 'MANEJO DE SOLOS ÁCIDOS — CALAGEM: objetivo primário = elevar pH para reduzir Al³⁺ e Mn²⁺ solúveis e aumentar disponibilidade de Mo, Ca, Mg e P. Em solos Oxissolos/Ultissolos do cerrado e sul do Brasil: meta de pH H₂O = 5,5-6,5 dependendo da cultura. EFEITO DA CALAGEM EM NUTRIENTES: AUMENTA disponibilidade: Mo (10x por unidade de pH — mais responsivo), Ca (se calcítico ou dolomítico), Mg (se calcário dolomítico), P (entre pH 5,5-6,5); REDUZ disponibilidade: Fe, Mn, Zn, Cu, B (possível deficiência induzida por calagem excessiva → pH > 6,5 em solos arenosos → deficiência de Zn e B em milho). FORMAS DE CALCÁRIO: calcítico (CaCO₃ ≥ 95%); dolomítico (CaCO₃ + MgCO₃ ≥ 50% MgCO₃) — preferível em solos com Ca:Mg < 3:1; PNRT/PRNT (Poder Relativo de Neutralização Total) = CCE × fator de finura × umidade → mede eficácia real. Calcário mais fino reage mais rápido mas menor durabilidade; calcário grosso reage mais lentamente. CALAGEM EM SUBSOLO: a calagem superficial não corrige subsolo ácido (CaCO₃ tem baixa solubilidade e lenta mobilização). Alternativas: (a) GESSAGEM (CaSO₄·2H₂O = gesso agrícola, 16-17% Ca, 13-14% S): SO₄²⁻ se lixivia com Ca²⁺ para subsolo → acidez de Al reduzida por formação de AlSO₄⁺ (não-tóxico) + fornecimento de Ca para aprofundamento radicular; doses: 2-6 t gesso/ha em solos argilosos com Al tóxico no subsolo; (b) Incorporação profunda de calcário com subsolagem. CALAGEM EM PLANTIO DIRETO: aplicar calcário na superfície e aguardar migração lenta (3-5 anos para atingir 10-15 cm de profundidade). ADUBO P EM BANDA vs. Al: aplicação de P em banda próximo à semente atenua toxicidade de Al em plântulas de trigo e sorgo em solos de baixo pH → P forma complexos com Al no solo próximo à raiz. LEGUMINOSAS EM SOLOS ÁCIDOS: calagem é pré-requisito para nodulação eficiente; inoculação com Rhizobium resistente a Al + seleção de cultivares tolerantes ao Al = estratégia para produção em solos ácidos com menor insumo. SEQUÊNCIA PRÁTICA: corrigir topsoil com calcário (PRNT ≥ 70%) → gessagem para subsolo → reamostragem a cada 2-4 anos.',
 'Marschner, H. (Ed.) (2012). Marschner''s Mineral Nutrition of Higher Plants. 3rd ed. Academic Press, London.',
 '{calagem, gessagem, acidez, Al, pH, calcário, dolomítico, PRNT, subsolo, plantio direto, leguminosa, Zn, B, Mo, cerrado, oxissolo}');
