-- ─── HAVLIN et al. — CALAGEM, ACIDEZ DO SOLO E CORREÇÃO ─────────────────────
-- Soil Fertility and Fertilizers, 8ª ed. (2017) — Cap. 3: soil acidity, lime requirement
-- ─────────────────────────────────────────────────────────────────────────────

insert into public.conhecimento (titulo, tipo, cultura, conteudo, fonte, tags) values

('Havlin et al. — Química da acidez do solo: acidez ativa, potencial e trocável',
 'artigo', 'all',
 'ACIDEZ DO SOLO — TIPOS: (1) Acidez ativa = H⁺ em solução (medido pelo pH); representa < 1% da acidez total. (2) Acidez potencial = H⁺ + Al³⁺ na CTC — é a acidez que requer neutralização pela calagem; quantificada por tampão (SMP, Mehlich etc.); solos argilosos ou com alta MO têm maior acidez potencial que solos arenosos com mesmo pH. (3) Saturação de Al = % da CTC ocupada por Al³⁺ → aumenta com queda do pH; metas de calagem são frequentemente expressas como redução da saturação de Al para < 5-10% e/ou aumento da saturação de bases (V%) a níveis adequados para a cultura. FONTES DE ACIDEZ NO SOLO: (a) Precipitação (chuva + CO₂ atmosférico = H₂CO₃ → pH 5,5-5,7); (b) Remoção de bases pela colheita; (c) Fertilizantes nitrogenados amoniacais — PRINCIPAL FONTE ANTRÓPICA: oxidação de NH₄⁺ (nitrificação) → H⁺; regra prática: 1 kg N-NH₄⁺ como (NH₄)₂SO₄ acidifica equivalente a 3,6 kg CaCO₃; sulfato de amônio acidifica 2x mais que ureia; (d) Respiração das raízes + microorganismos = CO₂ → H₂CO₃; (e) Oxidação de sulfetos em solos recém-drenados → H₂SO₄. EFEITO DO pH NOS NUTRIENTES: abaixo de pH 5,5 → Al³⁺ e Mn²⁺ solúveis aumentam fortemente (Al³⁺ cresce 1.000x por unidade de pH abaixo de 5,5); P precipita como Al/Fe-PO₄; Mo adsorvido em óxidos de Fe/Al; deficiências de Ca e Mg comuns em solos arenosos. Acima de pH 7,0 → Fe, Mn, Zn, Cu, B, Co ficam pouco disponíveis (quelação e precipitação). pH 6,0-6,5 é a faixa ótima para maioria das culturas (equilíbrio entre disponibilidade de macro e micronutrientes). EFEITO DO pH DO SOLO NAS PLANTAS: em pH < 5,0 → toxicidade de H⁺ direta nas raízes (raízes escuras, crescimento lateral reduzido) independente do Al. Em pH 5,0-5,5 → Al³⁺ domina (inibe elongação radicular); em pH 5,5-6,0 → Mn²⁺ pode ser fator limitante em solos com alto Mn reduzível.',
 'Havlin, J.L.; Tisdale, S.L.; Nelson, W.L.; Beaton, J.D. (2017). Soil Fertility and Fertilizers: An Introduction to Nutrient Management. 8th ed. Pearson.',
 '{pH, acidez, Al, Mn, CTC, saturação de bases, saturação de Al, amônio, nitrificação, calagem, MO, P, Mo, nutrientes}'),

('Havlin et al. — Necessidade de calagem (NC) e materiais calcários',
 'protocolo', 'all',
 'NECESSIDADE DE CALAGEM (NC): quantidade de CaCO₃ necessária para elevar pH ao valor desejado; depende do pH atual, CTC, teor de argila e MO. MÉTODOS DE DETERMINAÇÃO: (1) Tampão SMP — solos com argilas 2:1 e 2:1:1 (argilas ativas, alta MO); comum em EUA Centro-Leste; (2) Tampão Mehlich — ultissolos e solos intemperizados (cauliníticos); mais adequado para solos do Brasil; (3) Adams-Evans — solos de baixa CTC, cauliníticos (ultissolos); (4) Woodruff — mollissolos. No Brasil: método SMP adaptado (IAC) + saturação de bases (V%) são os mais utilizados. PRINCÍPIO: V% alvo − V% atual × CTC / 10 = NC em t CaCO₃/ha (fórmula de Quaggio e Raij). FORMAS DE CALCÁRIO: CCE (Calcium Carbonate Equivalent) = poder neutralizante relativo ao CaCO₃ puro (100%): calcário calcítico (80-100% CCE); calcário dolomítico (95-120% CCE — maior CCE porque CaMg(CO₃)₂ / 184 × 2 × 100 = 109%); cal virgem CaO = 150-175% CCE (reage rapidamente, cáustico); cal hidratada Ca(OH)₂ = 120-135% CCE (rápida); escória de siderurgia (CaSiO₃) = 60-90% CCE. No Brasil: PRNT (Poder Relativo de Neutralização Total) = CCE × F₁ (finura) × F₂ (umidade) — valores > 70% são adequados; PRNT alto significa reação mais rápida e eficaz. CALCÁRIO CALCÍTICO vs. DOLOMÍTICO: usar dolomítico quando solo tem Ca:Mg < 3:1 (deficiência provável de Mg) ou relação K:(Ca+Mg) > 2,5% (tetania de pastagem em ruminantes). Se solo tem Ca e Mg adequados → calcítico é suficiente. QUANTIDADE PRÁTICA: NC depende principalmente do ΔpH e da CTC; solos argilosos com alta CTC precisam de mais calcário que solos arenosos para a mesma elevação de pH. REAPLICAÇÃO: cada 4-5 anos monitorando pH pelo histórico; solos arenosos: mais frequente; plantio direto: calcário aplicado em superfície e incorporado mais lentamente.',
 'Havlin, J.L.; Tisdale, S.L.; Nelson, W.L.; Beaton, J.D. (2017). Soil Fertility and Fertilizers: An Introduction to Nutrient Management. 8th ed. Pearson.',
 '{calagem, NC, PRNT, CCE, calcário, dolomítico, calcítico, CTC, V%, SMP, Mehlich, pH, MO, argila}'),

('Havlin et al. — Efeito da calagem na disponibilidade de nutrientes e pH ótimo por cultura',
 'protocolo', 'all',
 'EFEITO DA CALAGEM NOS NUTRIENTES: Calagem AUMENTA disponibilidade: Mo (mais responsivo — adsorção em óxidos de Fe/Al diminui com pH crescente → Mo liberado → essencial para nitrogenase em leguminosas; aumento de pH de 5,0 para 6,2 geralmente resolve Mo para FBN); Ca (se calcário calcítico ou dolomítico); Mg (se calcário dolomítico); P (entre pH 5,5-6,5 — precipitação Al/Fe-PO₄ reduz). Calagem REDUZ disponibilidade: Fe, Mn, Zn, Cu, B (precipitação ou adsorção aumenta com pH) → calagem EXCESSIVA (pH > 6,5-7,0 em solos arenosos) pode INDUZIR deficiências de Zn, Fe, Mn e B em culturas sensíveis. ESTRATÉGIA: nunca fazer calagem para pH > 6,5 em solos com histórico de Zn ou B deficientes; monitorar micronutrientes após calagem. pH ÓTIMO POR CULTURA (faixa): soja 6,0-6,5 (FBN melhor acima de pH 6,0 por Mo e nodulação); milho 5,8-7,0; trigo 6,0-7,0; arroz irrigado 5,5-6,5; batata 5,2-6,0 (sensível a sarna Streptomyces em pH alto); mirtilo/blueberry 4,5-5,5; alfafa/alfalfa 6,5-7,0 (exige alta saturação de bases); pastagens tropicais (Brachiaria) 5,0-6,0 (tolerante à acidez). V% (SATURAÇÃO DE BASES) ALVO NO BRASIL: soja 60-70%; milho 50-60%; pastagens Brachiaria 40-50%; cana-de-açúcar 60-70%; café 60-70%; feijão 60-70%; arroz irrigado 50-60%. CALAGEM AUMENTA: nodulação de leguminosas (Rhizobium sensível a Al + baixo Mo); mineralização de N orgânico; atividade microbiana geral; disponibilidade de P em solos ácidos altamente fixadores. CALAGEM PODE DIMINUIR: disponibilidade de micronutrientes catiônicos (Fe, Mn, Zn, Cu, Ni) → testar foliar após calagem em áreas com histórico de deficiência; S-sulfato pode ser adsorvido a óxidos após calagem (reduz SO₄²⁻ disponível em solos intemperizados).',
 'Havlin, J.L.; Tisdale, S.L.; Nelson, W.L.; Beaton, J.D. (2017). Soil Fertility and Fertilizers: An Introduction to Nutrient Management. 8th ed. Pearson.',
 '{calagem, pH, V%, soja, milho, alfafa, Zn, Mn, Fe, B, Mo, FBN, Rhizobium, nodulação, micronutriente, disponibilidade}'),

('Havlin et al. — Tolerância de culturas ao Al e P em banda para redução de toxicidade',
 'protocolo', 'all',
 'TOLERÂNCIA DE CULTURAS AO Al (Table 3-8 — faixas de pH ótimo): ALTA TOLERÂNCIA A pH BAIXO (toleram pH 4,5-5,5): centeio, tremoço, batata-doce, mandioca, arroz, arando/blueberry (pH 4,5-5,5), azaléia (pH 4,5-6,0). TOLERÂNCIA MÉDIA (pH 5,0-6,5): aveia, milho, sorgo, algodão, soja, girassol, trigo-mourisco, fumo. SENSÍVEIS (requerem pH 6,0-7,0): cevada, trevo branco, alfafa, beterraba, alface, espinafre, aspargo, cebola. MUITO SENSÍVEIS (pH 6,5-7,5): espirro (candytuft), capim-sudão em áreas altamente produtivas. ESTRATÉGIA DE MANEJO PARA Al TÓXICO: (1) Calagem: elevar pH para reduzir Al³⁺ → fórmula: por cada 1 t CaCO₃/ha → pH aumenta ~0,1-0,2 unidades (depende do solo); (2) P em banda: aplicação de P₂O₅ em banda próximo à linha de semeadura (sulco) reduz toxicidade de Al em plântulas de trigo e sorgo em solos de pH baixo — mecanismo: P complexa Al³⁺ formando Al-fosfato na rizosfera próxima à raiz jovem; em solos com pH 4,5 e alta fixação de P, P em banda aumentou rendimento de trigo de 38 → 51 bu/ac mesmo sem calcário; (3) Gessagem para subsolo: doses 2-4 t gesso/ha → AlSO₄⁺ (não-tóxico) + fornecimento de Ca no perfil; (4) Variedades Al-tolerantes (em soja, feijão, trigo, milho e sorgo existem cultivares selecionadas para Al) — verificar cultivares recomendadas para cerrado. ATENÇÃO: solos com Al tóxico no subsolo mas calagem apenas no topsoil terão sistema radicular raso → maior estresse hídrico em períodos de seca. Gessagem + calagem profunda = complementares para aprofundamento radicular.',
 'Havlin, J.L.; Tisdale, S.L.; Nelson, W.L.; Beaton, J.D. (2017). Soil Fertility and Fertilizers: An Introduction to Nutrient Management. 8th ed. Pearson.',
 '{Al, tolerância, pH ótimo, calagem, gessagem, P banda, soja, trigo, sorgo, milho, cerrado, subsolo, V%, plântula}');
