-- ─── HAVLIN et al. — REMOÇÃO DE NUTRIENTES PELAS CULTURAS E DIAGNOSE VISUAL ──
-- Soil Fertility and Fertilizers, 8ª ed. (2017) — Table 9-1: nutrient removal + Fig. 9-1 key
-- ─────────────────────────────────────────────────────────────────────────────

insert into public.conhecimento (titulo, tipo, cultura, conteudo, fonte, tags) values

('Havlin et al. — Exportação de macronutrientes por grãos e forragens (Tabela 9-1)',
 'referencia', 'all',
 'EXPORTAÇÃO DE NUTRIENTES (lbs/acre pela parte colhida, Table 9-1): GRÃOS PRINCIPAIS — SOJA (50 bu/ac = ~3,4 t/ha grão): N=188, P=41, K=74, Ca=19, Mg=16 lbs/ac; + palhada (3 t/ac): N=89, P=16, K=74 lbs/ac; TOTAL planta (grão+palhada): N=277, P=57, K=148 lbs/ac (~77 kgN + 16kgP + 41kgK por ton de grão). MILHO (200 bu/ac = ~12,5 t/ha): grão N=150, P=40, K=160; palhada N=110, P=40, K=160; TOTAL planta: N=260, P=80, K=320 lbs/ac (~13 kgN + 4kgP + 15kgK por ton de grão). TRIGO (60 bu/ac = ~4 t/ha): grão N=70, P=12, K=30, Ca=6, Mg=8; palhada N=45, P=8, K=65, Ca=22, Mg=8. CEVADA (60 bu/ac): N=65, P=14, K=24 lbs/ac. CANOLA (45 bu/ac): N=145, P=22, K=80 (alta exportação de N e K; grão rico em óleo e proteína). SORGO GRÃO (80 bu/ac): N=65, P=30, K=22; grão com palhada: N=65+80, P=30+25, K=22+115 lbs/ac. AVEIA grão: N=60, P=10, K=15 lbs/ac. AMENDOIM: N=140, P=22, K=150; ramos N=100, P=25, K=80 lbs/ac. FORRAGEIRAS (ton/ac): ALFAFA (6 ton/ac): N=350, P=40, K=300, Ca=160, Mg=22 lbs/ac (alta demanda de P, K, Ca, Mg). CAPIM-BERMUDA COSTEIRO (8 ton/ac): N=400, P=45, K=310, Ca=32 lbs/ac. CORNICHÃO: N=60, P=13, K=40 lbs/ac/ton. SOJA FORRAGEM: N=360, P=50, K=320 lbs/ac/6ton. OUTRAS CULTURAS: ALGODÃO (caroço+fibra, 1,3 ton/ac): N=63, P=25, K=72 lbs/ac; CANA-DE-AÇÚCAR (40 ton/ac): N=180, P=23, K=250 lbs/ac. CONVERSÃO PRÁTICA (lbs/ac ÷ rendimento em ton/ha × 1,12 = kg/ton): soja grão ≈ 80 kgN/t + 14 kgP/t + 22 kgK/t exportados no grão; para repor N, P, K retirados pela lavoura, calcular com base na expectativa de produtividade e fator de eficiência do fertilizante.',
 'Havlin, J.L.; Tisdale, S.L.; Nelson, W.L.; Beaton, J.D. (2017). Soil Fertility and Fertilizers: An Introduction to Nutrient Management. 8th ed. Pearson.',
 '{exportação nutrientes, N, P, K, Ca, Mg, soja, milho, trigo, cevada, canola, alfafa, sorgo, capim, cana, tabela remoção}'),

('Havlin et al. — Chave de diagnose visual de deficiências: mobilidade e sintomas por nutriente',
 'referencia', 'all',
 'DIAGNOSE VISUAL — CHAVE (Fig. 9-1): PASSO 1 — Sintomas em folhas VELHAS ou NOVAS? NUTRIENTES MÓVEIS (sintomas em folhas VELHAS primeiro, redistribuídos para novas): N, P, K, Mg, Mo. NUTRIENTES IMÓVEIS (sintomas em folhas NOVAS/meristemas primeiro): Ca, Fe, Mn, Zn, Cu, Ni. S, Cl, B: mobilidade variável por espécie. PASSO 2 — Cor e padrão nos locais afetados: FOLHAS VELHAS AMARELAS (clorose uniforme, sem manchas) + crescimento reduzido = N deficiente (toda folha pálida/amarelada por redução de clorofila); FOLHAS VELHAS COM BORDAS NECRÓTICAS + sem clorose internerval = K deficiente (escaldado das bordas); FOLHAS VELHAS COM CLOROSE INTERNERVAL (nervuras verdes, internérvios amarelos ou avermelhados) = Mg deficiente (clorofila ligada a Mg); FOLHAS VELHAS AVERMELHADAS/ROXAS + bordas necróticas = P deficiente (acúmulo de antocianinas); FOLHAS VELHAS AMARELAS UNIFORMES + sem necrose = Mo ou S deficientes (Mo: semelhante à deficiência de N; S: clorose uniforme + pecíolo pode ficar avermelhado). FOLHAS NOVAS COM CLOROSE INTERNERVAL NÍTIDA (veias verdes, entre-veias amarelo-esbranquiçado) = Fe deficiente (padrão mais nítido que Mn); FOLHAS NOVAS CLOROSE INTERNERVAL MAIS DIFUSA + manchas necróticas pontilhadas = Mn deficiente; FOLHAS NOVAS CLOROSE LEVE + manchas brancas entre nervura central e borda = Zn deficiente em milho (white stripes); FOLHAS NOVAS CLORÓTICAS + pontas brancas ou ápices enrolados/necróticos = Cu deficiente; FOLHAS NOVAS/MERISTEMAS MORREM + necrose = Ca ou B deficiente (Ca: meristema apical; B: toda estrutura reprodutiva e meristema). FOME OCULTA: concentração foliar abaixo do nível crítico mas sem sintoma visual → perdas de rendimento silenciosas → análise foliar preventiva é mais eficiente que esperar sintomas visuais. DOENÇAS vs. DEFICIÊNCIA: deficiências nutricionais sempre simétricas bilateralmente e com gradiente de gravidade ao longo da planta; doenças e pragas = padrão assimétrico ou aleatório.',
 'Havlin, J.L.; Tisdale, S.L.; Nelson, W.L.; Beaton, J.D. (2017). Soil Fertility and Fertilizers: An Introduction to Nutrient Management. 8th ed. Pearson.',
 '{diagnose, deficiência, sintoma, clorose, necrose, mobilidade, N, P, K, Mg, Fe, Mn, Zn, Cu, B, Ca, Mo, antocianina, fome oculta}'),

('Havlin et al. — Amostragem foliar: época, órgão e faixas de suficiência por cultura',
 'protocolo', 'all',
 'AMOSTRAGEM FOLIAR — ÉPOCAS E ÓRGÃOS PADRÃO (Table 9-3): SOJA: amostra o 3º ou 4º trifólio completamente desenvolvido a partir do topo (folha recém-madura) nos estádios R1-R2 (florescimento-início de formação de vagem). MILHO: folha inteira oposta e abaixo da espiga no espigamento (VT-R1). TRIGO: 4 folhas superiores no espigamento (maturação do pólen). ALGODÃO: o mais jovem trifólio recém-maturado no espigamento. ALFAFA: 1/10 superior do terço superior de plantas em início de florescimento (10% floração). CITRUS: folhas de 4-6 meses de brotações não-frutíferas. MACIEIRA: folhas a meio do broto terminal em meados do verão. FAIXAS DE SUFICIÊNCIA FOLIAR — SOJA (R1-R2, trifólio recém-maduro): N 4,5-5,5%; P 0,25-0,50%; K 1,7-2,5%; Ca 0,35-2,0%; Mg 0,25-1,0%; S 0,20-0,40%; Fe 50-300 ppm; Mn 20-100 ppm; Zn 25-50 ppm; Cu 6-15 ppm; B 20-55 ppm; Mo 0,5-5 ppm. MILHO (folha da espiga, VT): N 2,5-3,5%; P 0,25-0,40%; K 1,5-2,5%; Ca 0,21-0,50%; Mg 0,15-0,40%; Fe 25-250 ppm; Mn 20-150 ppm; Zn 20-60 ppm; Cu 5-25 ppm; B 5-25 ppm. TRIGO (4 folhas superiores, espigamento): N 3,0-4,5%; P 0,20-0,45%; K 1,7-3,0%; Fe 25-100 ppm; Mn 20-100 ppm; Zn 20-70 ppm; Cu 5-12 ppm; Mo 0,1-1,0 ppm. INTERPRETAÇÃO: relação N:S > 15 → deficiência de S provável; relação Ca:B > 1.200:1 → deficiência de B provável; Fe:Mn < 1,5 → Fe pode estar sendo inibido por alto Mn; K:(Ca+Mg) > 2,5 em forragem → tetania de pastagem em ruminantes. CUIDADOS: nunca comparar análises com diferentes épocas de amostragem ou diferentes órgãos amostrados; teores decrescem com maturidade em nutrientes móveis (N, P, K, Mg).',
 'Havlin, J.L.; Tisdale, S.L.; Nelson, W.L.; Beaton, J.D. (2017). Soil Fertility and Fertilizers: An Introduction to Nutrient Management. 8th ed. Pearson.',
 '{análise foliar, amostragem, soja, milho, trigo, alfafa, suficiência, N, P, K, Ca, Mg, Fe, Mn, Zn, Cu, B, Mo, R1, R2, VT}'),

('Havlin et al. — Nitrogênio: resposta de milho e soja à adubação nitrogenada',
 'protocolo', 'all',
 'N EM MILHO — RECOMENDAÇÃO POR PRODUTIVIDADE ESPERADA: 1,0-1,2 lb N por bushel esperado (+ descontar N do solo = MO% × fator de mineralização e N de cultura antecedente). Milho após soja = 20-40 lb N/ac de crédito de N. Milho após milho = N mínimo do histórico recomendado. NUE (N use efficiency) em milho: 50-60% do N aplicado é recuperado no grão; excesso = potencial de lixiviação (NO₃⁻) ou volatilização (N₂O, NH₃). TIMING: divisão de doses é mais eficiente que dose única antecipada em solos arenosos ou com alta precipitação → parcelamento (1/3 na semeadura + 2/3 em cobertura V4-V6) reduz perdas. N EM SOJA — FBN vs. N mineral: soja bem nodulada fixa 40-60% do N total da planta (pode ser 80% em solos arenosos com baixo N); remove ~1,5 lb N por bushel (58 kg N/t); mas exporta também N no grão colhido sem retornar para o solo → N negativo para o solo a longo prazo. Soja inoculada com Bradyrhizobium + Mo (12-25 g Mo/ha na semente) = estratégia para maximizar FBN e não precisar de N mineral. N mineral em soja só recomendado quando: solo com baixo N-FBN histórico + baixo potencial de nodulação (solos novos, pH < 5,5, solo muito compactado). DIAGNOSE DO N: clorostalk test em milho (talo NO₃⁻ > 700 ppm na colheita = N suficiente; < 250 ppm = N deficiente). Índice de clorofila foliar (Minolta SPAD) na folha da espiga em VT: > 50 = N suficiente; < 40 = N provavelmente deficiente. FORMAS DE N: ureia (46% N) = mais usada; URAN (28-32% N) = menor risco de volatilização; (NH₄)₂SO₄ (21% N, 24% S) = fornece S; anidro (82% N) = mais eficiente por custo mas requer equipamento especial.',
 'Havlin, J.L.; Tisdale, S.L.; Nelson, W.L.; Beaton, J.D. (2017). Soil Fertility and Fertilizers: An Introduction to Nutrient Management. 8th ed. Pearson.',
 '{N, nitrogênio, milho, soja, FBN, uréia, cobertura, NUE, Bradyrhizobium, inoculação, SPAD, clorostalk, MO, mineralização}');
