-- ─── MARSCHNER'S MINERAL NUTRITION — SOLOS SALINOS E TOLERÂNCIA À SALINIDADE ──
-- 3ª Ed. (2012) — Sec. 17.6: ECe thresholds, osmotic stress, Na/Cl toxicity, adaptation
-- ─────────────────────────────────────────────────────────────────────────────

insert into public.conhecimento (titulo, tipo, cultura, conteudo, fonte, tags) values

('Marschner — Tolerância de culturas à salinidade: limiares de ECe e classificação',
 'referencia', 'all',
 'SALINIDADE DO SOLO — DEFINIÇÃO E MEDIÇÃO: solo salino = ECe (condutividade elétrica do extrato de saturação) > 4 dS/m ≈ 40 mM NaCl. Na prática de campo, concentração real na solução do solo é 2-4x maior que no extrato de saturação (menor teor de água). Solo sódico = PST (percentual de saturação de Na) > 15% ou SAR > 13. TOLERÂNCIA POR CULTURA (Tabela 17.26 — ECe limiar e decréscimo por dS/m acima do limiar): MUITO SENSÍVEIS (ECe limiar 1,0-1,7 dS/m): feijão-comum P. vulgaris — limiar 1,0 dS/m, -19% por dS/m (S); cenoura — limiar 1,0 dS/m, -14%/dS/m; damasco/apricot — 1,6 dS/m, -24%/dS/m (S); milho — 1,7 dS/m, -12%/dS/m. MODERADAMENTE SENSÍVEIS: tomate — 2,5 dS/m, -9,9%/dS/m; uva/videira — 1,5 dS/m, -9,6%/dS/m. MODERADAMENTE TOLERANTES: soja — 5,0 dS/m, -20%/dS/m (MT); azevém perene — 5,6 dS/m, -7,8%/dS/m. TOLERANTES: trigo — 6,0 dS/m, -7,1%/dS/m; beterraba — 7,0 dS/m, -5,9%/dS/m; cevada — 8,0 dS/m, -5%/dS/m (T mais tolerante entre cereais); tamareira (date palm) — 4,0 dS/m, -3,6%/dS/m (T). VARIAÇÕES ONTOGÊNESE: beterraba = tolerante em maior parte do ciclo, mas SENSÍVEL na germinação; arroz, tomate, trigo, cevada = sensibilidade aumenta após germinação. Arroz = crescimento vegetativo menos afetado que desenvolvimento reprodutivo (salinidade reduz enchimento de grãos). INTERAÇÕES: salinidade + encharcamento = efeito sinérgico negativo em maioria das espécies. B excessivo em água de irrigação (> 0,5 mg/L citrus/nogueira; > 2 mg/L maioria das culturas) pode ser mais limitante que a salinidade per se.',
 'Marschner, H. (Ed.) (2012). Marschner''s Mineral Nutrition of Higher Plants. 3rd ed. Academic Press, London.',
 '{salinidade, ECe, tolerância, feijão, milho, tomate, soja, trigo, cevada, beterraba, arroz, PST, SAR, B, irrigação}'),

('Marschner — Três principais restrições de solos salinos: déficit hídrico, toxicidade iônica e desequilíbrio nutricional',
 'artigo', 'all',
 'RESTRIÇÕES PRINCIPAIS DE SOLOS SALINOS (Seção 17.6.3.2): (1) DÉFICIT HÍDRICO (estresse osmótico): sais reduzem o potencial osmótico (ψπ) do solo → menor disponibilidade de água para absorção; potencial hídrico crítico para a maioria das plantas = -1.500 kPa (ponto de murcha); em solos salinos, este nível é atingido com menor dessecamento que em solos normais porque parte do potencial hídrico vem do ψπ + potencial mátrico. (2) TOXICIDADE IÔNICA: acúmulo excessivo de Na⁺ e Cl⁻ no citoplasma inibe enzimas (> 10 mM Na no citoplasma = prejudicial em glicófitas; Na desloca K e Ca de sítios enzimáticos). Na principalmente prejudica enzimas e membranas; Cl prejudica folhas por acúmulo. Sintoma: clorose e necrose nas margens de folhas velhas (folhas velhas pois Na/Cl acumulam conforme a transpiração). (3) DESEQUILÍBRIO NUTRICIONAL: Na⁺ compete com K⁺, Ca²⁺ e Mg²⁺ → deficiência induzida dessas bases; Cl⁻ compete com NO₃⁻ (inibe absorção de N em solos salinos → pode limitar crescimento por N); SO₄²⁻ e CO₃²⁻ em solos alcalinos → precipita Ca, Mg e micronutrientes. INTERAÇÃO DOS EFEITOS: em estágio inicial = déficit hídrico domina → reduz crescimento imediatamente; em exposição prolongada = toxicidade iônica domina folhas velhas; folhas novas sofrem mais com falta de carboidratos (fotoassimilados) por redução fotossintética nas velhas. DIAGNOSE NA PRÁTICA: salinidade → clorose e necrose das MARGENS das FOLHAS VELHAS (padrão diferente de K, Mg ou B — que também afetam bordas/margens mas com outros padrões). Se há suspeita de salinidade, confirmar com ECe do solo e análise da água de irrigação.',
 'Marschner, H. (Ed.) (2012). Marschner''s Mineral Nutrition of Higher Plants. 3rd ed. Academic Press, London.',
 '{salinidade, toxicidade, Na, Cl, K, Ca, Mg, N, déficit hídrico, osmótico, ECe, diagnose, irrigação, K deficiência}'),

('Marschner — Mecanismos de tolerância à salinidade: exclusão, inclusão e solutos compatíveis',
 'artigo', 'all',
 'ESTRATÉGIAS DE TOLERÂNCIA À SAL (Seção 17.6.4): EXCLUSÃO (glicófitas e maioria das culturas): evitar acúmulo de Na/Cl no simplasto; (a) restrição de transporte de Na para o xilema → regulado por transportadores HKT na parênquima do xilema (genes Nax1 e Nax2 em trigo); (b) retrotrasnlocação de Na do floema — feijão-comum transporta Na dos brotos de volta para as raízes para re-exclusão; (c) Na/H antiporters SOS1 na membrana plasmática = exportam Na do citoplasma para o apoplasto ou rizosfera; INCLUSÃO (halófitas e algumas culturas tolerantes como beterraba): acumulam Na e Cl no vacúolo via transportadores NHX1 (vacuolar Na/H antiporters, alimentados por V-ATPase e V-PPase) → Na/Cl no vacúolo servem como osmótico barato → compensa déficit osmótico sem custo energético alto. AJUSTAMENTO OSMÓTICO — CUSTO ENERGÉTICO: NaCl = 0,54 mole ATP/osmol (barato); K-malato = 13 mole ATP/osmol; sacarose = 54 mole ATP/osmol → halófitas que usam NaCl como osmótico têm vantagem energética. SOLUTOS COMPATÍVEIS (síntese no citoplasma para ajuste osmótico sem interferência metabólica): glicina betaína (Chenopodiaceae, gramíneas — protege cloroplastos; reduz a necessidade de K para enzimas); prolina (maioria das plantas — também detoxifica espécies reativas de O₂); sorbitol (Rosaceae, Plantaginaceae); D-pinitol (leguminosas); manitol; trealose. TOLERÂNCIA TISSUE E COMPARTIMENTAÇÃO: Na/K muito maior nos vacúolos que no citoplasma em halófitas; chloroplastos de plantas tolerantes mantêm baixo Na e alto K mesmo com alta salinidade externa. Si reduz acúmulo de Na no xilema de arroz (bloqueia fluxo apoplástico radicular). MANEJO: seleção de cultivares tolerantes; irrigação frequente para lixiviar sais (demanda boa drenagem); gessagem (CaSO₄) reduz SAR e melhora estrutura de solos sódicos; acidificação com S elementar ou H₂SO₄ para solos alcalinos-salinos.',
 'Marschner, H. (Ed.) (2012). Marschner''s Mineral Nutrition of Higher Plants. 3rd ed. Academic Press, London.',
 '{salinidade, tolerância, exclusão, inclusão, halófita, NHX1, SOS1, HKT, glicina betaína, prolina, soluto compatível, beterraba, trigo, arroz, Si, gessagem}'),

('Marschner — Toxicidade de Cl vs. Na por espécie: feijão, uva, leguminosas e citrus',
 'artigo', 'all',
 'TOXICIDADE DE Cl vs. Na (Seção 17.6.3.4): A MAIORIA das CULTURAS SENSÍVEIS são mais sensíveis ao Cl⁻ que ao Na⁺. SENSÍVEIS A Cl: leguminosas (trevo, Medicago), citrus, videira (uva), feijão — o Cl se acumula nas folhas (> 3,5 mg Cl/g PS = tóxico para culturas sensíveis) → clorose e necrose marginal de folhas velhas; FEIJÃO = exclui Na eficientemente mas NÃO exclui Cl → o principal problema é Cl, não Na. UVA: tolerância à salinidade é dominada pela exclusão de Cl pelo porta-enxerto; porta-enxertos eficientes → videira tolerante; porta-enxertos ineficientes → alta sensibilidade. BETERRABA = incluidora de Na e Cl, mas tolera alto nível nas vacuoles → cresce melhor com NaCl do que sem (halófita facultativa); K e Ca foliar decrescem com salinidade por competição. MILHO = menos tolerante que beterraba, mas mantém Na foliar relativamente baixo (excluidor eficiente de Na); em milho, é o déficit osmótico (não Na ou Cl) que domina a inibição de crescimento em baixa-moderada salinidade. ARROZ = raízes muito sensíveis ao aumento de Na (mais que Cl); crescimento radicular inibido por Na antes do Cl causar toxicidade foliar. CONCENTRAÇÕES TÓXICAS DE Cl: sensíveis (citrus, nogueira, feijão) = > 3,5 mg Cl/g PS foliar (10 mM no líquido foliar); tolerantes (cevada, espinafre, alface, beterraba) = 20-30 mg Cl/g PS (60-90 mM). MANEJO PRÁTICO: para culturas sensíveis a Cl (citrus, uva, leguminosas) → usar fertilizantes com sulfato ou nitrato em vez de cloreto (KNO₃ em vez de KCl); para K: muriato de K (KCl) pode ser prejudicial em solos com salinidade ou em culturas sensíveis a Cl; sulfato de K (K₂SO₄) é a opção segura. Alta taxa de troca de N como NO₃⁻ reduz absorção de Cl competitivamente → pode atenuar toxicidade de Cl em solos levemente salinos.',
 'Marschner, H. (Ed.) (2012). Marschner''s Mineral Nutrition of Higher Plants. 3rd ed. Academic Press, London.',
 '{Cl, Na, salinidade, feijão, citrus, uva, arroz, milho, beterraba, KCl, KNO3, toxicidade, exclusão, porta-enxerto, irrigação}');
