-- ─── HAVLIN et al. — POSICIONAMENTO DE FERTILIZANTES: BANDA vs. LANÇO ─────────
-- Soil Fertility and Fertilizers, 8ª ed. (2017) — Cap. 10: placement, salt index, timing
-- ─────────────────────────────────────────────────────────────────────────────

insert into public.conhecimento (titulo, tipo, cultura, conteudo, fonte, tags) values

('Havlin et al. — Posicionamento de fertilizantes: métodos e fatores de decisão',
 'protocolo', 'all',
 'MÉTODOS DE POSICIONAMENTO DE FERTILIZANTES (Cap. 10): (1) LANÇO (broadcast): aplicação uniforme na superfície antes, durante ou após o plantio; eficiente para nutrientes MÓVEIS (N, S, B, Cl) que se movem pela massa de fluxo e difusão; menos eficiente para P e micronutrientes imóveis por causa da alta adsorção no solo quando espalhado. Em plantio direto, lanço de N pode perder por NH₃ volatilização (ureia), imobilização e desnitrificação. (2) BANDA (sulco ou ao lado e abaixo da semente): coloca fertilizante concentrado perto das raízes jovens → reduz contato fertilizante-solo → menor fixação de P em solos de alta capacidade de adsorção. Banda é recomendada especialmente para P, K, Zn e micronutrientes imóveis. (3) STARTER (com a semente / pop-up): dose baixa de N-P-K-S colocada 2-5 cm abaixo e ao lado da semente → estimula crescimento inicial, especialmente em solos frios e úmidos. (4) ADUBAÇÃO EM COBERTURA (sidedress / topdress): N para milho e sorgo em V4-V8 (fase de crescimento ativo); topdress de N em cereais de inverno antes do espigamento; sidedress de N com injetor subsuperficial = mais eficiente que lanço em plantio direto. FATORES DE DECISÃO: mobilidade do nutriente no solo; nível de fertilidade atual (solo test P/K); textura (arenoso = menor CTC → lixiviação K/Mg); sistema de preparo (plantio direto = maior risco de volatilização de N na superfície); condições climáticas na semeadura (solo frio e úmido = maior resposta ao starter). PRINCÍPIO FUNDAMENTAL: nutrientes IMÓVEIS (P, K, Zn, Cu, Mn, Fe) devem ser posicionados para maximizar contato raiz-fertilizante; nutrientes MÓVEIS (N, S, B, Cl) → timing (época de aplicação) é mais crítico que posicionamento.',
 'Havlin, J.L.; Tisdale, S.L.; Nelson, W.L.; Beaton, J.D. (2017). Soil Fertility and Fertilizers: An Introduction to Nutrient Management. 8th ed. Pearson.',
 '{posicionamento, banda, lanço, starter, pop-up, sidedress, topdress, P, K, N, plantio direto, imóvel, móvel, adubação}'),

('Havlin et al. — Fósforo em banda vs. lanço: quando cada método é mais eficiente',
 'protocolo', 'all',
 'P EM BANDA vs. LANÇO (Figs. 10-41 a 10-44): BANDA É SUPERIOR ao lanço quando: (1) Solo test P BAIXO + solos com alta fixação de P (Oxissolos, Ultissolos com alto teor de Fe/Al); (2) Solo FRIO e ÚMIDO na semeadura (difusão de P reduzida em temperaturas < 15°C); (3) Culturas de INÍCIO DE CRESCIMENTO CRÍTICO (milho, sorgo em solos temperados — antecipação de maturidade); (4) Solo com incorporação MÍNIMA (superfície seca na semeadura). LANÇO É IGUAL à banda quando: Solo test P MÉDIO-ALTO + solo quente/úmido na semeadura + boa incorporação + culturas de estação quente. BANDA É MELHOR EM SOLO TEST BAIXO: razão BC:BD = 4-5x (precisa aplicar 4-5x mais P em lanço para obter o mesmo rendimento que band aplicada). RECUPERAÇÃO DE P NO PRIMEIRO ANO: banda ou lanço = apenas 20% do P aplicado é recuperado no 1º ano; residual acumula no solo. REGRA PRÁTICA: em solos com alta fixação de P (oxissolos = até 1.200 kg P₂O₅/ha para saturar pontos de fixação), a banda é essencial — não adianta aplicar P em lanço em grandes quantidades sem banda, pois a adsorção supera a disponibilidade para plantas jovens. P BANDA com NH₄⁺: MAP ou DAP ao lado da semente aumenta eficiência de P em solos calcários por dois mecanismos — (a) NH₄⁺ acidifica a rizosfera local; (b) P e NH₄⁺ competem pelos mesmos sítios de adsorção → maior P disponível. NH₄⁺ com P (via MAP/DAP em banda) = mais eficiente que P sozinho em solos alcalinos. STARTER em SOLO TEST ALTO: ainda pode ter resposta em condições de solo frio/úmido (resposta de precocidade/maturity) mesmo sem resposta de rendimento final.',
 'Havlin, J.L.; Tisdale, S.L.; Nelson, W.L.; Beaton, J.D. (2017). Soil Fertility and Fertilizers: An Introduction to Nutrient Management. 8th ed. Pearson.',
 '{P, fósforo, banda, lanço, starter, fixação, oxissolo, MAP, DAP, NH4, solo frio, plantio direto, recuperação, milho}'),

('Havlin et al. — Índice de salinidade de fertilizantes: risco de queima na semente',
 'referencia', 'all',
 'ÍNDICE DE SALINIDADE (IS) — Tabela 10-2: medida do aumento de pressão osmótica na solução do solo quando o fertilizante é aplicado (relativo ao NaNO₃ = 100). Fertilizantes com IS alto = maior risco de dano à semente quando aplicados em contato ou próximo a ela. VALORES DE IS (por 100 lb do material): KCl (60% K₂O) = IS 116 (ALTO — maior risco em banda com semente); NH₄NO₃ (35% N) = IS 104; (NH₄)₂SO₄ (21% N) = IS 88; UAN 28% = IS 100; ureia (46% N) = IS 71; KNO₃ (50% K₂O) = IS 70; K₂SO₄ (54% K₂O) = IS 43 (menor risco que KCl); MgSO₄·7H₂O = IS 44; MAP (11-22-0) = IS 27 (mais seguro para aplicação com semente); TSP (0-46-0) = IS 10 (muito seguro); CaSO₄·2H₂O (gesso) = IS 8 (praticamente inerte). ÍNDICE PARCIAL DE SALINIDADE por unidade de nutriente: N como KNO₃ = 5,3 (alto); N como NaNO₃ = 6,1; K como KCl = 1,9; K como K₂SO₄ = 0,85; P como TSP = 0,21; P como MAP = 0,41. REGRAS PRÁTICAS: (a) K em banda com semente: < 10 lb K₂O/acre (culturas sensíveis); 15-30 lb K₂O/acre (cereais tolerantes); (b) Ureia em semente: EVITAR → ureia libera NH₃ livre que é tóxico para plântulas; (c) N+K juntos na semente = efeito aditivo de salinidade → dose máxima ainda menor; (d) Sulfato de K (K₂SO₄) = melhor opção que KCl para bandas próximas à semente; (e) MAP = fonte de P mais segura para aplicação com semente; (f) DAP com semente = EVITAR em solo seco/quente — NH₃ livre de DAP pode queimar plântulas. SINTOMA DE SALINIDADE NA SEMENTE: germinação reduzida ou irregular; radicela curta e marrom; murcha imediata das plântulas sem causa aparente (confunde com fungos de solo).',
 'Havlin, J.L.; Tisdale, S.L.; Nelson, W.L.; Beaton, J.D. (2017). Soil Fertility and Fertilizers: An Introduction to Nutrient Management. 8th ed. Pearson.',
 '{índice salinidade, IS, KCl, ureia, MAP, DAP, TSP, semente, queima, banda, K, N, P, germinação, plântula}'),

('Havlin et al. — Timing de N: época de aplicação por cultura e sistema de cultivo',
 'protocolo', 'all',
 'TIMING DE N — PRINCÍPIO: aplicar N o mais próximo possível do pico de demanda da cultura para maximizar eficiência de uso (NUE) e reduzir perdas por lixiviação, desnitrificação e volatilização. MILHO: (a) Pré-plantio (30-40% da dose) + cobertura V4-V8 (60-70%) = estratégia mais eficiente; (b) Aplicação antecipada integral no outono = 10-30% menos eficiente que aplicação na primavera em solos arenosos; em solos argilosos, redução de 5-10%; (c) Temperatura do solo < 10°C (50°F) = nitrificação reduzida → aplicação de NH₄⁺ no outono é mais segura em solos argilosos; NUNCA aplicar N-NH₄⁺ no outono em solo arenoso ou orgânico. CEREAIS DE INVERNO (trigo): máxima NUE quando 20-40% aplicado no pré-plantio/plantio + restante em cobertura no início da elongação do colmo (antes do espigamento); topdress antes do perfilhamento se solo úmido. FORRAGEIRAS E PASTAGENS: parcelamento em múltiplas aplicações (3-4) ao longo da estação de crescimento = mais eficiente; dose única no início = maior risco de perdas. PLANTIO DIRETO: NH₃ volatilização de ureia em superfície é maior sem incorporação → usar NBPT (urease inhibitor) ou injetar N subsuperficialmente. Em sistemas com alta cobertura residual: sidedress subsuperficial com injetor = 20-40% mais eficiente que lanço de N em superfície. FONTES DE N E SITUAÇÕES: ureia 46% N + NBPT = reduz volatilização em 50-75% em pastagens e plantio direto; UAN 28-32% N = menor risco de volatilização; anidro (82% N) = máxima eficiência por custo mas requer incorporação profunda (7-10 cm); (NH₄)₂SO₄ = também fornece S; não usar anidro em solos secos (fendilhados) → perda de NH₃ pela fenda.',
 'Havlin, J.L.; Tisdale, S.L.; Nelson, W.L.; Beaton, J.D. (2017). Soil Fertility and Fertilizers: An Introduction to Nutrient Management. 8th ed. Pearson.',
 '{N, nitrogênio, timing, cobertura, sidedress, milho, trigo, pastagem, ureia, NBPT, anidro, NUE, volatilização, plantio direto}');
