-- ─── HAVLIN et al. — MATÉRIA ORGÂNICA, PLANTIO DIRETO E ROTAÇÃO DE CULTURAS ─────
-- Soil Fertility and Fertilizers, 8ª ed. (2017) — Cap. 12: soil health, OM, tillage, rotation
-- ─────────────────────────────────────────────────────────────────────────────

insert into public.conhecimento (titulo, tipo, cultura, conteudo, fonte, tags) values

('Havlin et al. — Saúde do solo e matéria orgânica: indicadores e efeitos na produtividade',
 'artigo', 'all',
 'SAÚDE DO SOLO (SOIL HEALTH) — Cap. 12: conjunto de propriedades físicas, biológicas e químicas que determinam a capacidade do solo em sustentar produção. INDICADORES MENSURÁVEIS (Tabela 12-1): profundidade do topsoil (volume de raízes + disponibilidade de água e nutrientes); MO do solo (ciclagem de nutrientes, retenção de água e pesticidas, estrutura); infiltração (erosão e escorrimento superficial); agregação (estrutura e erosão); densidade global (penetração radicular e porosidade); biomassa microbiana (atividade biológica e ciclagem); pH (disponibilidade de nutrientes); salinidade/sodicidade; disponibilidade de nutrientes. A MO É O FATOR MAIS CRÍTICO: efeitos no solo: (1) COR escura = maior temperatura de superfície → antecipa germinação e desenvolvimento inicial; (2) RETENÇÃO DE ÁGUA: MO retém 20x seu peso em água → fundamental em solos arenosos; (3) CIMENTAÇÃO DE PARTÍCULAS em agregados; (4) AUMENTO DA CTC em 20-70% (grupos carboxilicos COOH); (5) CICLAGEM DE NUTRIENTES por mineralização/imobilização; (6) QUELAÇÃO de micronutrientes (Mn²⁺ complexado pela MO = menos tóxico); (7) TAMPONAMENTO de pH. DECLÍNIO DA MO COM CULTIVO: quando solo virgem é cultivado, MO declina rapidamente nos primeiros 10 anos e continua por décadas; em cultivo convencional, MO pode cair 50% em 40-70 anos. Solo virgem com 5% MO = mineraliza ~140 kg N/ha por estação (= suficiente para culturas antigas); em solo cultivado com 2% MO = mineraliza ~56 kg N/ha (= insuficiente para colheitas modernas). RESTAURAÇÃO DE MO: solo orgânico aumenta com: entrada de C > perdas de C; no-till + alta produtividade + rotações são as principais vias; efeitos demora 5-8 anos para ser mensurável em no-till (concentrado nos primeiros 5-10 cm).',
 'Havlin, J.L.; Tisdale, S.L.; Nelson, W.L.; Beaton, J.D. (2017). Soil Fertility and Fertilizers: An Introduction to Nutrient Management. 8th ed. Pearson.',
 '{MO, matéria orgânica, saúde do solo, CTC, biomassa microbiana, agregação, N mineralização, produtividade, plantio direto, solo}'),

('Havlin et al. — Plantio direto e sistemas de preparo: efeitos na MO, temperatura e erosão',
 'protocolo', 'all',
 'SISTEMAS DE PREPARO DO SOLO (Cap. 12): PREPARO CONVENCIONAL (aração profunda): incorpora todos os resíduos; aumenta aeração e temperatura → acelera oxidação da MO (mineralização); necessita maior investimento de energia e mão de obra. PLANTIO DIRETO (no-till): resíduos deixados na superfície; sem perturbação do solo exceto sulco de semeadura. VANTAGENS DO NO-TILL: (1) erosão reduzida drasticamente (em 30% de cobertura de resíduo → perda de solo = 20% do solo descoberto); (2) MO aumenta com tempo, especialmente nos primeiros 5 cm; (3) retenção de água: maior infiltração + menor evaporação = maior disponibilidade hídrica (em sistema trigo-sorgo-pousio, no-till armazenou 35% da chuva vs. 15% em preparo convencional = +47 bu/ac de sorgo); (4) menor custo de combustível, mão de obra e máquinas. DESVANTAGENS DO NO-TILL: solo mais frio na primavera (resíduos = isolante → menor temperatura de germinação), especialmente em solos mal drenados; maior incidência de doenças fúngicas em alguns sistemas; necessidade de maior habilidade de manejo. STRIP TILLAGE: faixa estreita preparada no plantio → compromisso entre no-till e preparo convencional → solo mais quente no sulco, resíduos entre linhas. TILLAGE EFEITO NO NITROGÊNIO: preparo melhora aeração → aumenta mineralização do N orgânico → a longo prazo esgota o estoque de N-orgânico; em plantio direto, N de ureia lançada na superfície pode ser imobilizado pelos resíduos de alta relação C:N → eficiência melhorada com aplicação subsuperficial. COBERTURA DE RESÍDUOS NA SUPERFÍCIE: soja deixa menos cobertura que milho após semeadura → maior erosão pós-soja. SOLO APÓS 7 ANOS DE MILHO CONTÍNUO: no-till pH mais baixo na superfície (H⁺ de nitrificação não misturado); preparo convencional = pH mais uniforme no perfil (incorporação de cal).',
 'Havlin, J.L.; Tisdale, S.L.; Nelson, W.L.; Beaton, J.D. (2017). Soil Fertility and Fertilizers: An Introduction to Nutrient Management. 8th ed. Pearson.',
 '{plantio direto, no-till, preparo do solo, MO, erosão, N, temperatura solo, resíduo, strip till, conservação}'),

('Havlin et al. — Rotação de culturas: benefícios agronômicos, N e controle de pragas',
 'protocolo', 'all',
 'ROTAÇÃO DE CULTURAS (Cap. 12): BENEFÍCIOS GERAIS: reduz erosão pelo vento e água; mantém ou aumenta MO; aumenta N disponível com leguminosas; aproveita nutrientes residuais de culturas anteriores; melhora estrutura do solo (raízes profundas de leguminosas redistribuem nutrientes do subsolo); diversifica renda e distribui risco. DADOS DO MORROW PLOTS (Illinois — 100+ anos): corn contínuo SEM fertilizante = 47 bu/ac; corn-soja = 79 bu/ac; corn-aveia-feno = 100 bu/ac; com N-P-K: corn contínuo = 127-141 bu/ac; corn-soja = 153-157 bu/ac; corn-aveia-feno = 160-168 bu/ac → rotação 2-3 anos > monocultura mesmo com fertilização. BENEFÍCIO DO EFEITO ROTAÇÃO: milho após soja = 10-20% maior rendimento que milho contínuo; mecanismo inclui alelopatia negativa no contínuo + patógenos de solo específicos + estrutura do solo. LEGUMINOSAS NA ROTAÇÃO: crédito de N da soja para milho subsequente = 20-40 kg N/ha em média (depende do rendimento da soja e sistema de preparo); alfafa de 1º ano incorporada pode fornecer 35-300 kg N/ha. CONTROLE DE PRAGAS: rotação reduz pressão de doenças específicas (ex: podridões de raiz em trigo, mancha de rede em cevada, esclerotínia em soja/canola); intervalo mínimo recomendado = 3-4 anos para doenças graves (canola); nematoides controlados com gramíneas em rotação. ALEGORIA E AUTOALELOPATIA: reseeding de alfafa após alfafa causa queda progressiva de rendimento (alelopatia); trigo contínuo sofre takeall (Gaeumannomyces graminis); corn contínuo = corn rootworm aumenta. PLANEJAMENTO: sequência de 2 safras = warm season + cool season; 3 safras = warm + cool sem consecutivos; 4+ safras = máximo de 50% da mesma família.',
 'Havlin, J.L.; Tisdale, S.L.; Nelson, W.L.; Beaton, J.D. (2017). Soil Fertility and Fertilizers: An Introduction to Nutrient Management. 8th ed. Pearson.',
 '{rotação, culturas, soja, milho, N, leguminosa, plantio direto, doença, praga, MO, alelopatia, solo}'),

('Havlin et al. — Plantas de cobertura e adubos verdes: aporte de N e proteção do solo',
 'protocolo', 'all',
 'PLANTAS DE COBERTURA (COVER CROPS) — Cap. 12: plantadas após a colheita para proteger o solo durante o período sem cultivo. Se incorporadas antes do plantio da cultura principal → adubo verde. BENEFÍCIOS: (1) N de leguminosas (Table 12-12): alfafa = 20-150 kg N/ha; ervilhaca peluda (hairy vetch) = 60+ kg N/ha; cravo-vermelho = 35-130 kg N/ha; feijão azevém = 20-35 kg N/ha; ervilha do campo = 60-160 kg N/ha; (2) supressão de plantas daninhas por efeito alelopático; (3) redução de erosão durante entressafra; (4) maior infiltração + menor evaporação de água; (5) pastejo em outono-inverno nas gramíneas (retorno econômico adicional). LEGUMINOSAS vs. NÃO-LEGUMINOSAS: leguminosas fixam N₂ = maior retorno de N; não-leguminosas (centeio, trigo) = proteção física + alta relação C:N = imobilização temporária de N após incorporação. SINCRONIZAÇÃO: mineralização do N do adubo verde deve ser sincronizada com o pico de demanda da cultura subsequente (N mineralizado mais cedo na primavera = risco de lixiviação antes do milho atingir demanda máxima em V4-V8); trigo demanda N mais cedo que milho na primavera → adubo verde pode ser mais eficiente para trigo que milho. MANEJO PRÁTICO: incorporar adubo verde 2-4 semanas antes do plantio para sincronizar mineralização com demanda precoce; leguminosas com C:N < 20:1 = mineralização imediata; gramíneas com C:N > 30:1 = imobilização temporária → adicionar N suplementar na semeadura para compensar. ATENÇÃO: uso de água pela planta de cobertura pode reduzir água disponível para a próxima cultura em regiões semiáridas (ex: norte de Minas Gerais, Nordeste).',
 'Havlin, J.L.; Tisdale, S.L.; Nelson, W.L.; Beaton, J.D. (2017). Soil Fertility and Fertilizers: An Introduction to Nutrient Management. 8th ed. Pearson.',
 '{cobertura, adubo verde, N, leguminosa, ervilhaca, alfafa, centeio, C:N, mineralização, erosão, plantio direto, solo}');
