-- ─── MARSCHNER'S MINERAL NUTRITION — RIZOSFERA, RAÍZES CLUSTER E MICORRIZAS ───
-- 3ª Ed. (2012) — Cap. 13-15: root exudates, cluster roots, AM/ECM mycorrhizae
-- ─────────────────────────────────────────────────────────────────────────────

insert into public.conhecimento (titulo, tipo, cultura, conteudo, fonte, tags) values

('Marschner — Rizosfera: química e modificações induzidas por raízes',
 'artigo', 'all',
 'RIZOSFERA (Cap. 13-14): zona do solo diretamente influenciada pela atividade radicular (normalmente 1-2 mm ao redor da raiz). A densidade de microrganismos na rizosfera é 10-100x maior que no solo bulk. GRADIENTES AO LONGO DA RAIZ: zonas apicais (meristema, elongação) = maior taxa de absorção de água e nutrientes + menor pH local (maior bombeamento de prótons) + menor densidade microbiana; zonas subapicais (pelos radiculares) = maior liberação de exsudatos orgânicos. MODIFICAÇÕES DE pH NA RIZOSFERA: (a) Nutrição com NH₄⁺ → acidifica rizosfera (H⁺ liberado pela assimilação do NH₄⁺ + nitrifificação inibida) — benéfico para aumentar disponibilidade de P, Zn, Mn, Fe; (b) Nutrição com NO₃⁻ → alcaliniza rizosfera (OH⁻/HCO₃⁻ liberados) — pode reduzir disponibilidade de micronutrientes catiônicos próximo à raiz; (c) Fixação de N₂ por leguminosas = acidifica rizosfera (H⁺ produzido como subproduto da nitrogenase); (d) Exsudação de ácidos orgânicos (citrato, malato, oxalato) = acidifica + complexa Al³⁺, Fe³⁺ e Ca²⁺ → aumenta disponibilidade de P em solos com alto Al ou Ca. RIZODEPOSIÇÃO: 5-10% do C assimilado é liberado como exsudatos de raiz; 30-40% da entrada total de MO no solo vem da rizosfera (que representa apenas 2-3% do volume total). FOSFATASES: exsudadas pelas raízes e microrganismos rizosféricos; mineralizam P orgânico (fitato, fosfolipídios) → contribuição importante em solos com alto P-orgânico. MANEJO: adubação com NH₄⁺ (uréia, sulfato de amônio) próxima às raízes → acidifica rizosfera → melhora disponibilidade de P em solos calcários e neutros. Inoculação com rizobactérias e fungos micorrízicos = via biológica para melhorar exploração do solo.',
 'Marschner, H. (Ed.) (2012). Marschner''s Mineral Nutrition of Higher Plants. 3rd ed. Academic Press, London.',
 '{rizosfera, exsudato, pH, NH4, NO3, ácido orgânico, fosfatase, P, Zn, Fe, Mn, Al, micorriza, rizobactéria}'),

('Marschner — Raízes cluster (proteoid roots): adaptação à deficiência de P',
 'artigo', 'all',
 'RAÍZES CLUSTER (Cap. 13-14): morfologia especializada que aparece em resposta à deficiência de P (principalmente), N e Fe; característica de Proteaceae, tremoço branco (Lupinus albus) e outras espécies em solos de baixa P. ESTRUTURA: densas aglomerações de laterais curtas cobertas de pelos radiculares (aspecto de escovinha); em tremoço branco = ~50% da matéria seca de raízes em condições de deficiência severa de P; em Proteaceae australianas = até 80%. MECANISMO: (1) Liberação massiva de CITRATO (+ H⁺) durante 2-3 dias de vida ativa da raiz cluster: citrato acidifica a rizosfera local + complexa Al³⁺, Fe³⁺ e Ca²⁺ → desorve P adsorvido nos óxidos de Fe/Al e desestabiliza Ca-P em solos calcários; (2) H⁺ exsudado concomitantemente à exsudação de citrato (ativado pela PM H⁺-ATPase) amplifica a acidificação local; (3) FOSFATASES ácidas secretadas pelas raízes cluster mineralizam P orgânico no volume de solo adjacente; (4) Flavonoides, quitinases e glucanases também secretados — efeito antimicrobiano local (inibe degradação do citrato por microrganismos). TEMPO DE ATIVIDADE: 2-3 dias por cluster → para manter captação contínua de P, a planta precisa formar novos clusters em solo ainda não esgotado. LIMITAÇÃO: volume de solo mobilizado é pequeno (zona imediatamente adjacente) → raízes cluster são mais eficientes em solos homogeneamente pobres em P (como Oxissolos e Ultissolos do cerrado) do que em solos com P localizado. IMPLICAÇÃO PRÁTICA: adubação de P em banda próxima às raízes jovens → maior eficiência que lanço em solos com alta capacidade de fixação de P. Tremoço branco = planta sentinela para deficiência de P em solos ácidos.',
 'Marschner, H. (Ed.) (2012). Marschner''s Mineral Nutrition of Higher Plants. 3rd ed. Academic Press, London.',
 '{raiz cluster, proteoid, P, deficiência, tremoço, citrato, fosfatase, oxissolo, cerrado, H-ATPase, exsudato, fixação}'),

('Marschner — Micorrizas arbusculares (AM): mecanismos de benefício nutricional',
 'artigo', 'all',
 'MICORRIZAS ARBUSCULARES (Cap. 15): associação simbiótica entre a maioria das plantas e fungos do filo Glomeromycota; formadas por quase todas as culturas agrícolas (exceto brássicas e Chenopodiaceae). MECANISMO P: hifas externas captam P no solo além da zona de depleção radicular (raiz = 1-2 mm; hifas AM = 2-11 cm do plano radicular, como em trevo branco com Glomus mosseae) → P absorvido pelas hifas é convertido em polifosfato (polyP) e transportado nas vacuoleis móveis das hifas até a raiz; na interface arbúsculo/raiz, polifosfato é hidrolisado por fosfatases fúngicas → P inorgânico transferido para a célula hospedeira via transportadores especiais (não expressos em raízes não-micorrizadas). CONTRIBUIÇÃO DAS HIFAS NA CAPTAÇÃO: P = 70-80% em trevo branco, 20% em milho; Zn = 50% em trevo, 25% em milho; Cu = 60% em trevo, 25% em milho; Mn = reduzido pelas micorrizas (AM muda a comunidade microbiana — reduz bactérias redutoras de Mn → menor disponibilidade de Mn²⁺). EFEITO SOBRE CRESCIMENTO: maior em solo com P BAIXO; benefício desaparece com P alto → em solos com alto P, as hifas custam C mas não fornecem P adicional → micorriza pode até reduzir crescimento em P alto. CUSTO: 4-20% do fotossintato diário é alocado ao fungo (carboidratos vão das raízes para as pontas das hifas; polifosfato e outros nutrientes voltam para a planta). INTERAÇÃO COM NODULAÇÃO: em soja, AM em baixo P aumentou o número de nódulos de 33 para 97 por planta + atividade de nitrogenase (ARA) duplicou → AM e Rhizobium são complementares em solos com baixo P. INIBIÇÃO POR P: alta adubação de P reduz colonização de AM e comprimento de hifa em 33-75% → déficit de Zn e Cu pode surgir como consequência de alta adubação de P em solos originalmente pobres nesses micronutrientes. PRÁTICA: inoculação com AM em culturas com baixo estande em solos de baixa fertilidade + evitar excesso de P na semeadura para não inibir a colonização.',
 'Marschner, H. (Ed.) (2012). Marschner''s Mineral Nutrition of Higher Plants. 3rd ed. Academic Press, London.',
 '{micorriza, AM, hifa, P, Zn, Cu, Mn, nodulação, Rhizobium, soja, milho, trevo, polifosfato, arbúsculo, simbiótico}'),

('Marschner — Rizobactérias promotoras de crescimento (PGPR) e bioinoculantes',
 'artigo', 'all',
 'PGPR (Plant Growth-Promoting Rhizosphere Bacteria) — Cap. 15: microrganismos da rizosfera que estimulam crescimento das raízes através de: (1) Melhoria da disponibilidade de nutrientes (solubilização de P por Bacillus, Pseudomonas; mineralização de N orgânico; sideróforos para Fe); (2) Produção de fitohormônios (AIA — auxina — por Azospirillum; citocininas e giberelinas por várias bactérias); (3) Inibição de patógenos por competição ou produção de antibióticos/fungicidas. RIZOBACTÉRIAS DIAZOTRÓFICAS: Azospirillum, Azotobacter, Pseudomonas = fixam N₂ de forma assimbiótica; em capim-pé-de-galinha e outras gramíneas, Azospirillum pode fornecer 10-40 kg N/ha/ano; associação benéfica com milho, arroz e cana-de-açúcar. BACTÉRIAS SOLUBILIZADORAS DE FOSFATO: Bacillus, Pseudomonas, Penicillium = liberam P de fosfatos insolúveis por ácidos orgânicos (glucônico, cítrico) e fosfatases; eficácia no campo é variável e dependente do pH e tipo de P do solo. PATÓGENOS DO SOLO vs. PGPR: competição por Fe via sideróforos (fluorescent pseudomonads suprimem patógenos que não produzem sideróforos eficientes); AM suprime Fusarium oxysporum em tomate e murcha em casuarina. INTERAÇÃO AM × PGPR: PGPR estimulam colonização por AM (Azospirillum + AM em milho = maior colonização radicular e absorção de P); Bacillus subtilis pré-inóculo = melhora o estabelecimento de AM. MANEJO: inoculação múltipla (AM + Rhizobium + PGPR) em leguminosas = estratégia para solos com baixa fertilidade, especialmente quando se deseja reduzir insumos. Temperatura de armazenamento < 10°C e ausência de luz direta = condições para maior viabilidade dos inóculos.',
 'Marschner, H. (Ed.) (2012). Marschner''s Mineral Nutrition of Higher Plants. 3rd ed. Academic Press, London.',
 '{PGPR, rizobactéria, Azospirillum, P solubilizador, sideróforo, AM, Rhizobium, FBN, milho, soja, patógeno, bioinoculante}');
