-- ─── MARSCHNER'S MINERAL NUTRITION — FIXAÇÃO BIOLÓGICA DE NITROGÊNIO (FBN) ──
-- 3ª Ed. (2012) — Cap. 16: nitrogenase, simbiose rhizobium, nutrição e FBN
-- ─────────────────────────────────────────────────────────────────────────────

insert into public.conhecimento (titulo, tipo, cultura, conteudo, fonte, tags) values

('Marschner — FBN: bioquímica da nitrogenase e proteção contra O₂ (leghemoglobina)',
 'artigo', 'all',
 'FIXAÇÃO BIOLÓGICA DE N₂ (Cap. 16): FBN global contribui 40-70 Tg N/ano em sistemas agrícolas e 107-195 Tg N/ano em ecossistemas terrestres naturais, comparável à produção industrial de N (Haber-Bosch = ~100 Tg N/ano). NITROGENASE: enzima exclusiva de procariotos; molibdênio-nitrogenase (mais abundante) = 2 proteínas: dinitrogenase (componente I, MoFe-proteína, 240 kDa, com cofator FeMo e cluster-P) + dinitrogenase redutase (componente II, Fe-proteína, 60 kDa, acopla hidrólise de ATP à transferência de elétrons). ESTEQUIOMETRIA: N₂ + 8e⁻ + 8H⁺ + 16 MgATP → 2NH₃ + H₂ + 16 MgADP + 16 Pi; custo energético mínimo = 960 kJ/mol N fixado. INIBIÇÃO POR O₂: nitrogenase é inativada irreversivelmente pelo O₂ → diferentes mecanismos de proteção: (1) anaeróbios obrigatórios (Clostridium); (2) fixação só em anaerobiose (Klebsiella); (3) respiração excessiva consumindo O₂ = proteção respiratória (Azotobacter); (4) slime/biofilme limitando difusão; (5) heterocistos de cianobactérias (Anabaena, Nostoc) = separação espacial de fotossíntese e fixação; (6) controle de difusão de O₂ + LEGHEMOGLOBINA em nódulos de leguminosas. LEGHEMOGLOBINA (Lb): heme-proteína com Fe central (estrutura idêntica à citocromo); em nódulos maduros de soja = 5% da proteína total do nódulo; faz captação de O₂ do espaço intercelular e o entrega por difusão a oxidase cbb₃ nos bacteroides → mantém [O₂] interna muito baixa enquanto sustenta respiração bacteroide intensa para produzir ATP; síntese depende de Fe (componente heme) e Co (cobalamina envolvida na síntese do heme). TRANSPORTE DO N FIXADO: NH₃ liberado pelos bacteroides → protonado a NH₄⁺ no espaço simbiossomal (ácido) → transportado ao citosol da célula hospedeira → assimilado via GS/GOGAT; exportado no xilema como: (a) ASPARAGINA em nódulos indeterminados (Medicago, Trifolium, Pisum, Vicia, Lens = leguminosas temperadas); (b) UREÍDEOS (alantoína + ácido alantoico) em nódulos determinados (soja, Phaseolus, Vigna, Lotus = leguminosas tropicais/subtropicais). UREÍDEOS (soja): síntese nos nódulos por oxidação de purinas → xantina → ácido úrico → alantoína + ácido alantoico; enzima-chave = xantina desidrogenase (Mo-dependente); concentração de ureídeos no xilema = indicador prático da atividade de FBN em soja no campo.',
 'Marschner, H. (Ed.) (2012). Marschner''s Mineral Nutrition of Higher Plants. 3rd ed. Academic Press, London.',
 '{FBN, nitrogenase, leghemoglobina, N2 fixação, ureídeo, alantoína, soja, Mo, Fe, Co, GS/GOGAT, nódulo, ATP, O2}'),

('Marschner — Especificidade hospedeiro-rhizobium, sinalização Nod factor e tipo de nódulo',
 'artigo', 'all',
 'DIVERSIDADE SIMBIÓTICA (Tabela 16.1): Rhizobium leguminosarum bv. phaseoli → Phaseolus; R. leguminosarum bv. trifolii → Trifolium; R. leguminosarum bv. viciae → Pisum, Lens, Vicia; Sinorhizobium meliloti → Medicago, Melilotus, Trigonella; Mesorhizobium loti → Lotus, Lupinus; Bradyrhizobium japonicum → Glycine (soja), Macroptilium, Vigna; Rhizobium sp. NGR234 = mais ampla = nodula ≥112 gêneros. DIÁLOGO MOLECULAR: (1) Raiz de leguminosa libera FLAVONOIDES (micromolar-nanomolar) no rizosfera — luteolina de Medicago sativa; 7,4-dihidroxiflavona de Trifolium; daidzeína de soja; (2) Flavonoide + proteína NodD constitutiva → ativa transcrição dos genes nod → síntese e secreção de NOD FACTORS (lipoquitooligossacarídeos); (3) Nod factors → deformação e curvamento de pelos radiculares + divisão cortical + formação de fio de infecção → bacteria entra no fio de infecção. TIPOS DE NÓDULO: (a) INDETERMINADO (Medicago, Trifolium, Pisum, Vicia, Lens) = iniciado no córtex interno da raiz; manutenção de meristema apical ativo; bacteroides incapazes de regenerar forma livre após senescência; (b) DETERMINADO (Glycine = soja, Phaseolus, Vigna, Lotus) = iniciado no córtex externo; sem meristema ativo, vida útil mais limitada; bacteroides conseguem regenerar forma livre. CUSTO DE C: fornecimento de carbono aos nódulos → sucrose entra nas células não-infectadas → sacarose sintase → monossacarídeos → glicólise → PEP → oxaloacetato → malato (MDH) → malato entra nos bacteroides via DctA → TCA → ATP + elétrons para nitrogenase; custo de C ao nódulo > 10% do C fotossintético diário. SANÇÃO DO HOSPEDEIRO: plantas que detectam nódulos ineficazes (pouco N₂ fixado) reduzem o fornecimento de O₂ aos bacteroides inefetivos → desfavorece linhagens parasitas; mecanismo baseado em variação na permeabilidade ao O₂ do córtex do nódulo.',
 'Marschner, H. (Ed.) (2012). Marschner''s Mineral Nutrition of Higher Plants. 3rd ed. Academic Press, London.',
 '{rhizobium, Bradyrhizobium, soja, nodulação, nód factor, flavonoide, Medicago, Trifolium, nódulo determinado, indeterminado, simbiose, sinalização}'),

('Marschner — Nutrição mineral e FBN: efeitos de Mo, Fe, Co, P, S, B e N mineral',
 'artigo', 'all',
 'NUTRIENTES CRÍTICOS PARA FBN (Seção 16.4.5): MOLIBDÊNIO (Mo): cofator metálico da nitrogenase (cofator FeMo) E da xantina desidrogenase (síntese de ureídeos em soja) → deficiência impacta fixação E transporte de N; deficiência de Mo em solos ácidos tropicais = causa frequente de N-deficiência em leguminosas sem fertilizante N; semente de amendoim tratada com 100 g Mo/ha (MoO₃) = +125% peso nódulo + maior atividade de nitrogenase + 370% aumento de vagem em solos ácidos vs. apenas 60 kg N/ha mineral; Mo tem alta prioridade de alocação para nódulos — transportado preferencialmente para nódulos mesmo em deficiência. FERRO (Fe): componente da leghemoglobina, nitrogenase Fe-proteína, ferredoxina e diversas hidrogenases → Fe é necessário em MAIOR quantidade para formação de nódulos do que para crescimento vegetativo; deficiência de Fe não afeta muito crescimento aéreo de amendoim, mas reduz drasticamente massa de nódulo, concentração de leghemoglobina, número de bacteroides e atividade de nitrogenase; alta concentração de bicarbonato (solos calcários) → clorose por Fe + supressão de nodulação; em feijoeiro com baixa disponibilidade de Fe → N₂ fixação reduz de 1,04 para 0,55 mmol planta⁻¹. COBALTO (Co): coenzima cobalamina (vitamina B12) → síntese de leghemoglobina nos bacteroides (metilmalonil-CoA mutase envolvida na síntese de heme); Co 0 vs. Co 0,50 mg CoSO₄·7H₂O/kg solo em tremoço: leghemoglobina = 0 vs. 22,5 nmol/g; bacteroides = 6×10⁹ vs. 14×10⁹ por nódulo; atividade nitrogenase = 10 vs. 172 nmol C₂H₂/g nódulo/min. FÓSFORO (P): demanda de ATP pela nitrogenase + GS/GOGAT + síntese de fosfolipídeos dos bacteroides; nódulos são dreno forte de P (concentração 3x maior em nódulo que em raízes e caule); P mínimo para nodulação = 0,5 μg P/L na solução; aumento de 200 para 500 μg P/L → maior ganho relativo em nódulo do que em raízes/parte aérea; AM (micorriza arbuscular) melhora P e aumenta nodulação. ENXOFRE (S): aminoácidos sulfurados (cisteína, metionina) na nitrogenase Fe-proteína (cluster Fe₄S₄); deficiência de S reduz leghemoglobina + ATP em bacteroides e mitocôndrias; atividade de PEP-carboxilase, MDH e glutamato sintase reduzem sob S deficiente. BORO (B): requerido para estrutura de fio de infecção e invasão das células do nódulo; concentração de B no nódulo = 4-5x maior que nas raízes; sem B, bactérias não progridem no fio de infecção → aborto da thread de infecção. NITROGÊNIO MINERAL: N-mineral em baixa dose = estimula FBN (supre N inicial antes dos nódulos se estabelecerem, estimulando crescimento foliar e maior fotossintato para nódulos); N-mineral alto = inibe nodulação e atividade de nitrogenase (retroalimentação negativa); NO₃⁻ mais inibitório que NH₄⁺; starter-N de 20-40 kg N/ha pode já reduzir nodulação de soja em condições brasileiras (Hungria et al., 2005).',
 'Marschner, H. (Ed.) (2012). Marschner''s Mineral Nutrition of Higher Plants. 3rd ed. Academic Press, London.',
 '{FBN, Mo, Fe, Co, P, S, B, nitrogenase, leghemoglobina, nódulo, soja, amendoim, tremoço, feijoeiro, N mineral, nodulação, AM}'),

('Marschner — FBN: quantidades fixadas por espécie, pH, Al, temperatura e seca',
 'referencia', 'all',
 'QUANTIDADES FIXADAS POR LEGUMINOSAS (Tabela 16.8, Werner 2005): Medicago sativa (alfafa) = 250 kg N/ha/estação; Trifolium spp. (trevo) = 250 kg N/ha/estação; Vicia faba = 200 kg N/ha/estação; Lupinus spp. = 150 kg N/ha/estação; Pisum spp. (ervilha) = 150 kg N/ha/estação; Cicer arietinum (grão-de-bico) = 135 kg N/ha/estação; Glycine max (soja) = 100 kg N/ha/estação; Arachis hypogaea (amendoim) = 100 kg N/ha/estação; Lens culinaris (lentilha) = 80 kg N/ha/estação; Cajanus cajan = 91 kg N/ha/estação; TOTAL GERAL: 24-250 kg N/ha/estação (até 340 kg em alguns estudos). Azolla-Anabaena (arroz inundado) = 50-80 kg N/ha/ano; cianobactérias de superfície de solo (clima temperado) = 13-38 kg N/ha/ano. EFEITO DE pH (Fig. 16.11): > pH 7.0 = simbiose sem restrição; pH 6.0 = início de supressão de expressão de genes nod; pH 5.0 = redução na multiplicação e infecção do rhizobium, distribuição restrita no solo; pH < 5.0 = populações muito baixas de rhizobia, falha de nodulação; CORREÇÃO DE pH (calagem) = solução mais eficiente para melhorar nodulação em solos ácidos → aumento de nodulação em feijoeiro, alfafa e amendoim com calagem; efeito cumulativo: 80-96 kg CaO equivalente necessário por tonelada de matéria seca de leguminosa para neutralizar o H⁺ produzido pela FBN. ALUMÍNIO (Al³⁺): Al monomérico inibe multiplicação de rhizobia e formação de pelos radiculares (sítios primários de infecção) → nodulação prejudicada; combinação de baixo pH + alto Al é a principal causa de falha de FBN em Oxissolos/Ultissolos do cerrado sem calagem; Ca em concentrações adequadas alivia efeito de H⁺ e Al sobre nodulação. TEMPERATURA ÓTIMA POR SISTEMA (Sadowsky, 2005): feijoeiro comum + rhizobium = 25-30°C; ervilha e trevo = ~30°C; caupi, amendoim e soja = 35-40°C; altas temperaturas (> 40°C) = inibem sobrevivência do rhizobium e infecção radicular + alteram síntese de leghemoglobina e atividade de nitrogenase. SECA: seca durante fase vegetativa = retarda nodulação e fixação; após nódulos estabelecidos = seca reduz FBN por aumento da resistência à difusão de O₂ para os bacteroides; em soja, seca eleva ureídeos e aminoácidos livres no tecido = feedback negativo na fixação. INOCULAÇÃO: semente inoculada com Bradyrhizobium japonicum selecionado + Mo (12-25 g Mo/ha via tratamento de sementes) = estratégia padrão para soja em solos sem histórico de cultivo de soja ou com populações inadequadas; competição entre linhagem inoculada e rhizobia nativos do solo é o principal limitante do sucesso da inoculação.',
 'Marschner, H. (Ed.) (2012). Marschner''s Mineral Nutrition of Higher Plants. 3rd ed. Academic Press, London.',
 '{FBN, soja, alfafa, trevo, feijoeiro, amendoim, kg N/ha, pH, Al, calagem, temperatura, seca, inoculação, Bradyrhizobium, Azolla, oxissolo, cerrado}');
