-- ─── BIOFERTILIZANTES — PGPR, AZOSPIRILLUM E BACTÉRIAS DIAZOTRÓFICAS ────────
-- Inoculantes e promotores de crescimento para soja, milho e feijão
-- Fontes: Embrapa Soja/SNT; Hungria et al.; Döbereiner; Figueiredo et al.
-- ─────────────────────────────────────────────────────────────────────────────

insert into public.conhecimento (titulo, tipo, cultura, conteudo, fonte, tags) values

('Biofertilizantes — PGPR: mecanismos de promoção de crescimento vegetal',
 'artigo', 'all',
 'PGPR (Plant Growth Promoting Rhizobacteria): microrganismos da rizosfera que promovem crescimento por mecanismos DIRETOS e INDIRETOS. MECANISMOS DIRETOS: (1) FIXAÇÃO BIOLÓGICA DE N₂: Bradyrhizobium (soja), Rhizobium (feijão), Azospirillum (cereais, capins), Herbaspirillum (cana, arroz), Gluconacetobacter (cana); (2) SOLUBILIZAÇÃO DE P INORGÂNICO: Bacillus megaterium, Pseudomonas fluorescens, Aspergillus niger — produzem ácidos orgânicos (glucônico, cítrico, láctico) que acidificam o rizosfera e liberam P-insolúvel do solo; solubilização de Ca₃(PO₄)₂, AlPO₄, FePO₄; (3) MINERALIZAÇÃO DE P ORGÂNICO: fosfatases extracelulares (ácidas e alcalinas) que hidrolisam ésteres fosfatos do húmus → P disponível; (4) PRODUÇÃO DE FITOHORMÔNIOS: IAA (triptofano dependente), CKs, GAs e etileno por Azospirillum brasilense, Bacillus sp., Pseudomonas putida; IAA bacteriano estimula formação de raízes laterais e pelos radiculares → maior área de absorção. MECANISMOS INDIRETOS: (1) SIDEROFOROS: quelantes de Fe³⁺ de alta afinidade (pioverdin, enterobastin, bacillibactin) → mobiliza Fe do solo → competição com patógenos por Fe; (2) ANTIBIOTICOS: inibição de Fusarium, Pythium, Rhizoctonia por Pseudomonas e Bacillus; (3) INDUÇÃO DE RESISTÊNCIA SISTÊMICA (ISR): estimula SA e JA-dependentes em resposta a patógenos; (4) VOLATEIS: 2,3-butanodiol e acetoína de Bacillus subtilis GB03 estimulam crescimento de Arabidopsis; (5) ENZIMAS DEGRADATIVAS: ACC deaminase (Pseudomonas, Rhizobium) → degrada ACC precursor de etileno → reduz etileno em estresse → proteção radicular.',
 'Hungria, M. et al. (2010). Inoculation with selected strains of Azospirillum brasilense and A. lipoferum improves yields of maize and wheat in Brazil. Plant and Soil, 331, 413-425. / Figueiredo, M.V.B. et al. (2010). Plant growth promoting rhizobacteria: Fundamentals and applications. In: Maheshwari DK (ed) Plant Growth and Health Promoting Bacteria. Springer.',
 '{PGPR, rizobactérias, promoção de crescimento, solubilização de P, IAA, sideróforos, ACC deaminase, Azospirillum, Bacillus, Pseudomonas, ISR, resistência sistêmica}'),

('Biofertilizantes — Azospirillum brasilense: mecanismos, doses e resposta em soja, milho e trigo',
 'artigo', 'all',
 'AZOSPIRILLUM: gênero de α-proteobactérias diazotróficas (fixação associativa de N₂); espécies principais = A. brasilense (estirpes Sp7, Sp245, Ab-V5, Ab-V6, UFSM — padrão MAPA no Brasil) e A. lipoferum. MECANISMOS DE PROMOÇÃO: (1) FIXAÇÃO DE N₂ ASSOCIATIVA: contribuição de 10-30 kg N/ha em gramíneas (muito inferior ao Bradyrhizobium/soja), mas bioquimicamente confirmada por marcação isotópica ¹⁵N; (2) PRODUÇÃO DE IAA: via IpyA (piruvato de indol) e IAAid (indolacetamida); em condições ricas de triptofano exsuda > 0.18 μmol IAA/mL; efeito dominante sobre raízes (> número de raízes laterais, comprimento de pelos, >área radicular até 35% em trigo); (3) NITRATO REDUTASE: reduz NO₃⁻ → NO₂⁻ → NO → estimula divisão celular via sinalização de NO (óxido nítrico); (4) PRODUÇÃO DE GIBERELINAS E CITOCININAS: detectadas em meios de cultura; (5) FORMAÇÃO DE BIOFILME: proteção física e biológica da raiz. RESULTADOS EXPERIMENTAIS: META-ANÁLISE (Hungria et al., 2010, 22 ensaios): milho inoculado = +30% rendimento; trigo = +18%; soja = variável mas positivo quando co-inoculado com Bradyrhizobium. RECOMENDAÇÃO PRÁTICA PARA SOJA: co-inoculação Bradyrhizobium + Azospirillum brasilense (estirpes Ab-V5+Ab-V6) = RECOMENDAÇÃO OFICIAL EMBRAPA → maior FBN e crescimento radicular; dose = 100 mL inoculante/50 kg semente (líquido) ou 150-200 g/50 kg (turfoso); compatibilidade com fungicida de tratamento: aplicar inoculante SEPARADO do fungicida (fungicida antes, secar, inoculante no último momento antes do plantio); não misturar diretamente.',
 'Hungria, M. et al. (2010). Inoculation with selected strains of Azospirillum brasilense and A. lipoferum improves yields of maize and wheat in Brazil. Plant Soil 331:413-425. / Embrapa Soja (2016). Co-inoculação. Nota Técnica.',
 '{Azospirillum, brasilense, co-inoculação, Bradyrhizobium, soja, milho, trigo, IAA, fixação N2, MAPA, Ab-V5, Ab-V6, tratamento de sementes, fungicida}'),

('Biofertilizantes — Solubilizadores de fosfato: Bacillus e Pseudomonas em soja e milho',
 'artigo', 'all',
 'SOLUBILIZAÇÃO DE FOSFATO INORGÂNICO: mecanismo principal = produção de ácidos orgânicos (ácido glucônico por oxidação direta de glucose via PQQ-GDH; ácidos cítrico, málico, láctico, succínico por ciclo de Krebs); acidificação do microambiente → dissolução de fosfatos insolúveis: Ca₃(PO₄)₂ (solo neutro-alcalino), AlPO₄ e FePO₄ (solo ácido). GÊNEROS RELEVANTES: BACILLUS MEGATERIUM: solubilizador de P muito estudado; Producente de ácido glucônico via glucose desidrogenase PQQ-dependente; formulado em biofertilizante comercial ProBio P (Embrapa); ensaios de campo = +15-20% P disponível na solução do solo; PSEUDOMONAS FLUORESCENS: sideróforos + solubilização de P + antibióticos contra Fusarium; adaptada a rizosfera de soja e milho; ASPERGILLUS NIGER (fungo): produtor de ácido glucônico em quantidades industriais; base de alguns biofertilizantes comerciais. MINERALIZAÇÃO DE P ORGÂNICO: 25-85% do P total do solo é orgânico (fitatos, DNA, fosfolipídeos); enzimas fosfatases produzidas por PGPR: fosfatase ácida (pH < 6.5) e fosfatase alcalina (pH > 7.0); fitases = hidrolisam ácido fítico (IP6) → 6 inorgânicos + inositol; Bacillus subtilis e Aspergillus niger = produtores de fitase. INTERAÇÃO COM MICORRIZA (AM): hifas de AM estendem raio de exploração do solo para P → complementar aos solubilizadores bacterianos; co-inoculação AM + solubilizador P = efeitos aditivos; P insolúvel solubilizado por bactérias → absorvido por hifas AM → transferido à planta; AM conecta vantagens de ambos os mecanismos.',
 'Gyaneshwar, P. et al. (2002). Role of soil microorganisms in improving P nutrition of plants. Plant and Soil 245:83-93. / Richardson, A.E. et al. (2009). Acquisition of phosphorus and nitrogen in the rhizosphere. Plant Soil 321:305-339.',
 '{solubilização de fosfato, Bacillus, Pseudomonas, ácido glucônico, P inorgânico, fitase, micorriza AM, mineralização, P orgânico, rizosfera, biofertilizante}'),

('Biofertilizantes — Micorriza arbuscular (AM): fisiologia, colonização e benefícios nutricionais',
 'artigo', 'all',
 'MICORRIZA ARBUSCULAR (AM): simbiose entre raízes e fungos Glomeromycota (Glomus, Rhizophagus, Claroideoglomus, Funneliformis); > 80% das espécies vegetais formam AM; ESTRUTURAS: esporos no solo + hifas externas (estendem 5-20 cm além da rizosfera) + hifas internas + ARBÚSCULOS (estruturas de troca dentro das células corticais, vida útil de ~4 dias, depois digeridas = ciclo de digestão continua) + vesículas (estruturas de armazenamento). BENEFÍCIOS NUTRICIONAIS: FÓSFORO: principal benefício; hifas exploram mesoporos (0.5-5 μm) inacessíveis às raízes (> 20 μm); transporte de P via PHO84/PHT1 transportadores de alta afinidade nas hifas → interface arbuscular → planta; AM aumenta absorção de P em 3-8x em solos com P baixo; eficiência máxima em P < 25 mg/dm³ (menor que este nível = AM muito eficiente; muito alto = planta não investe em AM); MICRONUTRIENTES: Zn (AM aumenta 1.5-3x), Cu (1.5-2x), Mn, Fe (moderado); ÁGUA: hifas externas absorvem água adicional → maior tolerância a seca; MOLÉCULAS SINALIZADORAS: LCO (lipoquitooligossacarídeos = moléculas Nod-like) secretadas pelo fungo AM → ativam CSP (cascata de sinalização para colonização) na raiz. FATORES QUE REDUZEM COLONIZAÇÃO: alto P no solo (> 60-80 mg/dm³), fungicidas sistêmicos (benomyl, carbendazin), solo esterilizado/fumigado, monocultivo sem esporos; FATORES QUE FAVORECEM: baixo a médio P, rotação de culturas, plantio direto, matéria orgânica, ausência de fungicidas de solo. SOJA: AM importante principalmente em solos com P baixo; co-inoculação AM + Bradyrhizobium + Azospirillum = sinergia positiva para FBN e nutrição.',
 'Smith, S.E. & Read, D.J. (2008). Mycorrhizal Symbiosis. 3rd ed. Academic Press. / Barea, J.M. et al. (2005). Microbial co-operation in the rhizosphere. J Exp Bot 56:1761-1778.',
 '{micorriza AM, Glomus, Rhizophagus, arbúsculos, fósforo, P, Zn, Cu, hifas, colonização, solo, simbiose, Bradyrhizobium, co-inoculação, soja}'),

('Biofertilizantes — Bioestimulantes: extratos de algas, ácidos húmicos e aminoácidos',
 'artigo', 'all',
 'BIOESTIMULANTES: substâncias ou microrganismos (não nutrientes, não pesticidas) que aplicados em pequenas quantidades na planta, semente ou solo estimulam crescimento, nutrição e tolerância a estresses. CATEGORIAS PRINCIPAIS: (1) EXTRATOS DE ALGAS MARINHAS (Ascophyllum nodosum, Sargassum sp., Fucus vesiculosus): contêm betaínas (glicina betaína, λ-aminobutirobetaína, creatinina), aminoácidos, microelementos, oligossacarídeos sulfatados, laminarina (elicitora de defesa), carrageenanos; mecanismo: estimulam CK endógenas (citocininas), melhoram abertura estomática, acumulam osmoprotegentes para seca; dose típica: 1-2 L/ha; efeitos: +8-15% produtividade em soja (ensaios), maior pegamento floral, melhor enchimento; (2) ÁCIDOS HÚMICOS E FÚLVICOS: extraídos de leonardita, humus, turfa ou vermicomposto; mecanismo: aumento de CTC rizosférica → maior retenção de nutrientes; estimulam H⁺-ATPases de membrana → aumentam absorção de NO₃⁻, PO₄³⁻, K⁺; ácido fúlvico melhora solubilidade e mobilidade de Fe e Zn; dose: 3-5 L/ha (líquido); importante: qualidade (grau de humificação) varia muito entre produtos; (3) AMINOÁCIDOS EXÓGENOS: aminoácidos hidrolisados de proteína vegetal ou animal (conchilina, colágeno, hidrolisado de feather meal); mecanismo: supresso de síntese "de novo" de aminoácidos → economia de ATP e esqueletos carbonados; prolina aplicada exogenamente → ativa sistema antioxidante + osmorregulador; glicina, alanina, aminoácidos aromáticos são precursores de fenólicos e hormônios; doses: 200-500 mL/ha; melhora absorção de micronutrientes quando quelatizados com aminoácidos (Zn-aminoácido, Fe-aminoácido). (4) PROTEÍNAS HIDROLISADAS DE LEGUMINOSAS: maior especificidade hormonal, menores riscos de contaminação por patógenos animais que as de origem animal. SYNERGON EFFECT: combinação de ácido húmico + aminoácidos + extrato de alga = efeito sinérgico documentado em múltiplos estudos; prática recomendada no estresse do florescimento (R1-R2) em soja.',
 'du Jardin, P. (2015). Plant biostimulants: Definition, concept, main categories and regulation. Sci Hort 196:3-14. / Khan, W. et al. (2009). Ascophyllum nodosum extract: Evaluation of its cytokinin-like activity. J Plant Physiol 166:1-9.',
 '{bioestimulante, alga, Ascophyllum nodosum, ácido húmico, ácido fúlvico, aminoácido, prolina, glicina betaína, citocinina, osmorregulação, seca, estresse, soja, florescimento}'),

('Biofertilizantes — Silício na nutrição de plantas: absorção, mecanismos e aplicação em soja',
 'artigo', 'all',
 'SILÍCIO (Si): não classificado como essencial, mas BENÉFICO (reduz estresses e aumenta produtividade em muitas culturas). FORMAS NO SOLO: ácido monossilícico H₄SiO₄ (forma absorvida pela planta, pH 2-9 = solúvel; pH > 9 = polimerização); 0.1-0.6 mM em solução do solo; acumulado em frações amorfas (biogênica e geogênica). ABSORÇÃO: transportadores NIP (Aquaporinas Nodulin-like Intrinsic Proteins) = Lsi1 (influxo, epiderme/endoderme) e Lsi2 (efluxo, efluxa para xilema); Si acumula em folhas como sílica amorfa (SiO₂·nH₂O) na parede celular e espaços intercelulares. DEPOSIÇÃO E EFEITO FÍSICO: 1-3 mm de deposição de sílica na cutícula foliar → barreira física contra penetração de fungos (Blumeria, Magnaporthe); dupla camada sílica+cera = reduz transpiração cuticular 20-30%; deposição em casca de arroz = ~20% Si. MECANISMOS FISIOLÓGICOS: (1) ANTIOXIDANTE: Si não reage diretamente, mas ativa SOD, CAT, APX e POD endógenas → reduz ROS; SOD+Si = +40% atividade em estresse de Al; (2) ANTI-PATOGÊNICO: ativa genes de defesa PR1, PR2, PR3 (PR-proteínas) via ativação de SA; (3) ANTI-HERBIVORIA: silicificação de células da epiderme foliar → abrasão de peças bucais de insetos; (4) TOLERÂNCIA AO AL: Si + Al → precipitam como aluminossilicatos nas células da raiz → menos Al tóxico; (5) REDUÇÃO DA TOXICIDADE DE Mn: Si reduz absorção de Mn em solos ácidos e atenua sintomas de toxicidade; (6) OSMORREGULAÇÃO EM SECA: Si aplicado via foliar → reduz WUE (uso eficiente de água). DOSES PARA SOJA: silicato de cálcio (wollastonita) ou silicato de magnésio (escória de siderurgia) = 1-3 t/ha solo; silício foliar (ácido monossilícico ou silicato de potássio) = 1-2 L/ha em 200-400 L água. INTERAÇÃO COM DOENÇAS: silício reduz ferrugem da soja (P. pachyrhizi) em 30-55% em ensaios de campo.',
 'Epstein, E. (1999). Silicon. Annu Rev Plant Physiol 50:641-664. / Ma, J.F. & Yamaji, N. (2008). Functions and transport of silicon in plants. Cell Mol Life Sci 65:3049-3057. / Korndörfer et al. (Embrapa). Silício na agricultura.',
 '{silício, Si, wollastonita, escória, H4SiO4, Lsi1, Lsi2, barreira física, antifúngico, SOD, CAT, Al toxicidade, Mn toxicidade, ferrugem, soja, PR-proteínas}');
