-- ─── BIOFERTILIZANTES — INOCULANTES, COMPATIBILIDADE E TECNOLOGIA DE APLICAÇÃO
-- Bradyrhizobium, co-inoculação, tratamento de sementes e interações
-- ─────────────────────────────────────────────────────────────────────────────

insert into public.conhecimento (titulo, tipo, cultura, conteudo, fonte, tags) values

('Biofertilizantes — Bradyrhizobium japonicum/elkanii: tecnologia de inoculação para soja',
 'artigo', 'soja',
 'BRADYRHIZOBIUM JAPONICUM e B. ELKANII: bactérias fixadoras de N₂ em simbiose com soja; estirpes brasileiras padrão MAPA: SEMIA 5079 (Semia 587 = B. japonicum) e SEMIA 5080 (CPAC 7 = B. elkanii) — padrão desde 1990s; NOVA GERAÇÃO: estirpes UFSC-A70 e UFSC-A73 (Embrapa 2021) = maior competitividade + maior FBN; concentração mínima = 1×10⁹ UFC/mL (líquido) ou 1×10⁹ UFC/g (turfoso). EFICIÊNCIA DA INOCULAÇÃO: solo com população de Bradyrhizobium > 10² UFC/g = pode nodular naturalmente, mas cepa nativa raramente atinge eficiência ótima; inoculação com estirpes selecionadas = 50-300 kg N/ha no ciclo; equivalente a 109-650 kg ureia/ha (N de ureia a 45%); CUSTO-BENEFÍCIO: inoculante custa R$3-10/ha vs. 100-200 kg N fertilizante mineral a R$60-120/ha = economia de R$60-200/ha quando inoculação funciona. COMPATIBILIDADE COM AGROQUÍMICOS (tabela prática): MICROBIOLÓGICO: fungicidas sistêmicos (carbendazim, tiabendazol, metalaxil) reduzem viabilidade de Bradyrhizobium 40-90% — aplicar inoculante separado, secar semente depois do fungicida; FUNGICIDAS TRIAZÓIS (tiofanato metílico, tebuconazol): redução de 30-60%; INSETICIDAS NEONICOTINÓIDES (imidacloprido, tiametoxam): redução de 10-30%; INSETICIDAS ORGANOFOSFORADOS: alta toxicidade aos inoculantes (evitar). MÉTODO CO-INOCULAÇÃO: Bradyrhizobium (100 mL/50 kg) + Azospirillum brasilense (100 mL/50 kg) aplicados separados; co-inoculação aumenta nodulação 20-40% e FBN em 15-25% vs. inoculação simples; resultado: +3-8 sc/ha em média em 22 ensaios Embrapa. DOSE EM SOLO (quando não na semente): inoculante na linha de plantio = 200-400 mL/ha de inoculante líquido; vantagem = sem interferência de agroquímicos; desvantagem = necessita equipamento próprio.',
 'Hungria, M. et al. (2013). Tecnologia de inoculação e co-inoculação em soja. Comunicado Técnico Embrapa Soja 88. / Embrapa Soja (2020). Inoculação em soja: tecnologias e perspectivas.',
 '{Bradyrhizobium, SEMIA 5079, SEMIA 5080, inoculação, soja, FBN, co-inoculação, Azospirillum, compatibilidade, fungicida, inseticida, neonicotinóide, tratamento de semente}'),

('Biofertilizantes — Inoculantes para milho e trigo: Azospirillum e diazotróficos',
 'artigo', 'milho',
 'INOCULAÇÃO EM MILHO: Azospirillum brasilense (estirpes Ab-V5 + Ab-V6, Embrapa) = inoculante oficial registrado MAPA para milho e soja (IN 13/2011, atualizada 2019); mecanismo principal no milho = produção de IAA que estimula maior densidade de pelos radiculares e raízes laterais → maior absorção de N, P e água → responde a N-mineral por aumentar a eficiência de uso. RESPOSTAS A CAMPO: meta-análise de 27 ensaios Embrapa (2010-2018) = +18% rendimento no milho inoculado; maior efeito em solos com baixo a médio N, ou em situações de seca. DOSE: 100-200 mL de inoculante líquido/50 kg semente; aplicar próximo ao plantio; manter <4h entre inoculação e plantio; evitar exposição solar direta. COMPATIBILIDADE EM MILHO: fungicidas de tratamento de semente (fludioxonil+metalaxil, tiram) reduzem viabilidade do Azospirillum → sempre aplicar o inoculante POR ÚLTIMO, imediatamente antes do plantio, ou usar inoculante in furco (na linha de plantio); inseticidas imidacloprido = redução moderada (30%); piraclostrobina+tiofanato = alta redução (60-80%) = evitar contato. INOCULAÇÃO EM TRIGO: Azospirillum irazabalense e A. brasilense; ensaios no Paraná e RS = +12-20% rendimento; economia de 20-40 kg N/ha mineral. DIAZOTRÓFICOS EM CANA-DE-AÇÚCAR: Gluconacetobacter diazotrophicus, Herbaspirillum seropedicae, Nitrospirillum amazonense = endofíticos (colonizam xilema e tecidos internos); contribuição de N = 40-170 kg N/ha documentada em cana de açúcar sem N mineral; no Brasil, variedades modernas de cana perderam parte da capacidade de associação com esses diazotróficos por seleção para alta resposta ao N mineral.',
 'Hungria, M. et al. (2010). Inoculation with selected strains of Azospirillum brasilense and A. lipoferum improves yields of maize and wheat in Brazil. Plant Soil 331:413. / Embrapa Milho e Sorgo (2020). Inoculação em milho. Circular Técnica.',
 '{Azospirillum, milho, trigo, cana, inoculante, Ab-V5, Ab-V6, IAA, N, diazotróficos, Gluconacetobacter, Herbaspirillum, tratamento de semente, in furco}'),

('Biofertilizantes — Poliaminas, osmoprotegentes e mitigação de estresse abiótico',
 'artigo', 'all',
 'POLIAMINAS (PAs): compostos policatiônicos derivados de aminoácidos (putrescina de ornitina/arginina; espermidina = putrescina + N-aminopropil; espermina = espermidina + N-aminopropil); funções: estabilização de ácidos nucleicos (DNA, RNA, ribossomas) e membranas; inibição de nucleases e proteases; interação com receptores de GABA; sinalização em senescência e frutificação. RELAÇÃO COM ESTRESSES: SECA: PA aumentam em folhas de plantas submetidas à seca; espermidina + espermina estabilizam tilacoides e membranas → reduz dano por dehydration; putrescina + seca → ativa síntese de prolina (via P5CS) → osmoregulação. CALOR: espermidina ativa resposta de choque térmico (HSP) → thermotolerance; SALINIDADE: PAs reduzem entrada de Na⁺ via inibição de canais não-seletivos de cátions. INTERAÇÃO NUTRITIONAL: POTÁSSIO: K regula biossíntese de putrescina (K-deficiência → acúmulo de putrescina → sinal de alerta); ENXOFRE: S necessário para síntese de S-adenosilmetionina (SAM, precursor de espermidina e espermina via dcSAM); COBRE: PAs oxidadas por diamino oxidases (Cu-dependentes) → H₂O₂ → sinalização secundária. APLICAÇÕES PRÁTICAS: espermidina exógena (0.1-1 mM) foliar = documentado aumento de tolerância a seca e calor em soja (R1-R2); extrato de algas (Ascophyllum nodosum) = fonte natural de betaínas análogas a PAs; poliaminas via aminoácidos exógenos (arginina, prolina) = via indireta de suplementação. BIOSSÍNTESE DE ETILENO: PA e etileno compartilham SAM como precursor → competição entre vias (PA produção alta = inibe etileno; IAA estimula PA → auxilia em enraizamento).',
 'Alcázar, R. et al. (2010). Involvement of polyamines in plant response to abiotic stress. Biotechnol Lett 32:1857. / Kusano, T. et al. (2008). Polyamines: essential factors for growth and survival. Planta 228:367.',
 '{poliaminas, putrescina, espermidina, espermina, seca, calor, salinidade, S, K, Cu, SAM, etileno, osmoprotegente, betaína, Ascophyllum, alga}'),

('Biofertilizantes — Ácido húmico e fúlvico: mecanismos de ação em nutrição e crescimento',
 'artigo', 'all',
 'SUBSTÂNCIAS HÚMICAS (SH): produto final da decomposição da matéria orgânica; classificadas por solubilidade: ÁCIDO HÚMICO (AH) = solúvel em base (pH>2), insolúvel em ácido; ÁCIDO FÚLVICO (AF) = solúvel em toda faixa de pH; HUMINA = insolúvel; composição: núcleos aromáticos, cadeias alifáticas, grupos funcionais ácidos (-COOH, -OH) e N alifático. MECANISMOS DE AÇÃO: (1) ESTIMULAÇÃO DE H⁺-ATPase: AH e AF ativam ATPases de membrana plasmática (dose-resposta: 0.01-10 mg C/L = estimulação; > 100 mg C/L = inibição) → maior ejeção de H⁺ → acidificação apoplasto folhas → ativação de expansinas → crescimento celular; (2) PROMOÇÃO DE TRANSPORTE IÔNICO: ativação de ATPases aumenta gradiente eletroquímico → favorece absorção de NO₃⁻, K⁺, Fe²⁺; (3) QUELAÇÃO DE MICRONUTRIENTES: grupos -COOH e -OH de SH formam complexos orgânicos com Fe³⁺, Zn²⁺, Mn²⁺, Cu²⁺ → protege micronutrientes da fixação no solo e facilita absorção; pH-dependente: AH+Fe em pH 6-7 = Fe mais estável que Fe-EDTA; (4) MIMETISMO HORMONAL: AH apresentam atividade auxínica (estimulam enraizamento) e citocininica (retardam senescência); estruturas aromáticas de AH ativam receptores de hormônios; (5) MELHORIA ESTRUTURAL DO SOLO: AH formam microagregados com argilas → melhor estrutura, maior retenção de água e difusão de O₂. FONTES COMERCIAIS: leonardita = rocha sedimentar rica em SH (60-80% SH); vermicomposto; xisto retortado; extrato fermentado de algas. DOSE ÓTIMA: AH 10-30 kg/ha (solo); AF 3-5 L/ha (foliar, 100-200 mg C/L); associação AH+AF = efeito sinérgico na absorção de Fe, Zn e Ca. SOJA: AF foliar em V3-R1 = +8-12% nodulação, +5-10% produtividade em ensaios Embrapa.',
 'Canellas, L.P. et al. (2015). Humic and fulvic acids as biostimulants in horticulture. Sci Hort 196:15-27. / Nardi, S. et al. (2002). Soil organic matter and plant growth. Plant Soil 147:47.',
 '{ácido húmico, ácido fúlvico, humina, leonardita, H+-ATPase, quelação, Fe, Zn, Mn, Cu, expansina, crescimento radicular, mimetismo hormonal, substâncias húmicas, biofertilizante}');
