-- ─── TAIZ & ZEIGER — FISIOLOGIA VEGETAL — ESTRESSE HÍDRICO, TÉRMICO E SALINO
-- Capítulos 22-26 da 5ª edição (2013) — respostas a estresses abióticos
-- ─────────────────────────────────────────────────────────────────────────────

insert into public.conhecimento (titulo, tipo, cultura, conteudo, fonte, tags) values

('Taiz & Zeiger — Potencial hídrico, déficit hídrico e resposta estomática ao ABA',
 'artigo', 'all',
 'RELAÇÕES HÍDRICAS (Cap. 3 & 23): POTENCIAL HÍDRICO (Ψw) = Ψs + Ψp + Ψm; Ψs = potencial osmótico (solutos rebaixam); Ψp = potencial de pressão (turgor); Ψm = potencial mátrico (forças de adsorção ao solo). DÉFICIT HÍDRICO INICIAL → cadeia de eventos: (1) Ψw foliar cai → células perdem turgor → fechamento estomático (reversível com hidratação); (2) Ψs cai por ajuste osmótico (acúmulo de prolina, betaína, solutos compatíveis, K⁺); (3) síntese de ABA: início em cloroplastos (violaxantina → xantoxina → ABA-aldeído → ABA) → exportação via xilema → células guarda → ativa canais ânion (SLAC1) e fecha K⁺-entrada (KAT1) → turgescência cai → estômato fecha. SINALIZAÇÃO DE ABA: ABA + receptor PYR/PYL → inibe PP2C → ativa SnRK2 quinases → fosforila SLAC1 (abre) e KAT1 (fecha) → K⁺ sai de célula guarda + Cl⁻ sai → água sai → turgor cai → fechamento. SENSORES DE SECA NA RAIZ: receptor OSCA1 (mecanossensitivo) detecta déficit osmótico → CaM/CMLs ativadas → MAP quinases → ABA. AJUSTE OSMÓTICO: prolina (aminoácido derivado de glutamato via P5CS, até 5% do PS em seca) → protege proteínas e membranas, scavenger de ¹O₂; GLICINA BETAÍNA (derivada de colina + oxidação por CMO/BETAINE ALDEHYDE DEHYDROGENASE) → protege estroma do cloroplasto e tilacoides; ambas são osmoprotegentes compatíveis que não inibem enzimas. INTERAÇÃO MINERAL: K⁺ (60-80% do ajuste osmótico inicial em déficit hídrico leve); Mg² e Ca²⁺ estabilizam membranas; Si (silício) reduz WUE e diminui taxa de transpiração cuticular 20-30%.',
 'Taiz, L. & Zeiger, E. (2013). Plant Physiology. 5th ed. Cap. 3, 23. Sinauer Associates.',
 '{déficit hídrico, potencial hídrico, ABA, PYR/PYL, SnRK2, SLAC1, KAT1, estômato, ajuste osmótico, prolina, betaína, seca, K, Si, silício, P5CS}'),

('Taiz & Zeiger — Estresse térmico: HSPs, chaperoninas e resposta ao calor extremo',
 'artigo', 'all',
 'ESTRESSE TÉRMICO (Cap. 26): TEMPERATURAS CRÍTICAS EM SOJA: abaixo de 10°C = inibe germinação; 15°C = crescimento lento; ótimo = 25-30°C; 35°C = redução severa da FBN (nitrogenase inativada); 38°C = inibição do tubo polínico → aborto floral; 42°C+ = desnaturação proteica generalizada. DANO MOLECULAR: membranas tilacoidais são as primeiras atingidas (fluidez excessiva → desacoplamento da fosforilação oxidativa); PSII mais sensível (dissociação de complexo de oxidação da água); rubisco ativase inibida acima de 35°C (deixa rubisco inativa); repressão de sintase de amido em endosperma → menos amido em grãos. RESPOSTA AO CHOQUE TÉRMICO: (1) SENSOR DE TEMPERATURA: membranas lipídicas (desaturação de ácidos graxos → maior fluidez = sinal); RECEPTOR DE TEMPERATURA: CNGC (canais não-seletivos de cátions) → Ca²⁺ entra; (2) HSFs (fatores de transcrição de choque térmico): HsfA2 (principal em plantas) ativado por Ca²⁺ → liga ao HSE (elemento de choque térmico, AAGAA) → ativa genes HSP; (3) HSPs (Heat Shock Proteins): HSP70 (70 kDa, ATPase-dependente) = previne desnaturação de proteínas (dobramento correto, desfazimento de agregados); HSP90 (chaperona de clientes específicos); HSP100/ClpB = redobra proteínas já desnaturadas; sHSPs (pequenas, 15-42 kDa) = formam oligômeros que protegem proteínas do estresse. TERMOTOLERÂNCIA ADQUIRIDA: aplicação de temperatura subletal (38°C/1h) → pré-adaptação para temperatura letal (45°C/2h); mediado por acúmulo de HSP, prolina e ácido salicílico; Azospirillum inoculado estimula termotolerância via produção de GABA. INTERAÇÃO MINERAL: CÁLCIO (Ca²⁺ como segundo mensageiro do choque térmico); MAGNÉSIO (ativa Rubisco ativase); POTÁSSIO (retenção de K⁺ em membranas estabilizadas pelas HSPs).',
 'Taiz, L. & Zeiger, E. (2013). Plant Physiology. 5th ed. Cap. 26. Sinauer Associates.',
 '{estresse térmico, calor, HSP, chaperonina, HsfA2, HSE, PSII, rubisco, Ca, Mg, K, termotolerância, aborto floral, FBN, soja, desnaturação, prolina, SA}'),

('Taiz & Zeiger — Estresse oxidativo: ROS, enzimas antioxidantes e neutralização',
 'artigo', 'all',
 'ESPÉCIES REATIVAS DE OXIGÊNIO (ROS): geradas em cloroplastos, mitocôndrias e peroxissomos como subproduto do metabolismo aeróbico; principais ROS: O₂•⁻ (radical superóxido), H₂O₂ (peróxido de hidrogênio), ¹O₂ (oxigênio singlete), HO• (radical hidroxil). GERAÇÃO: CLOROPLASTO: transporte de elétrons — O₂ recebe e- de ferredoxina → O₂•⁻ (reação de Mehler); PSII sob excesso de luz → ¹O₂; MITOCÔNDRIA: complexo I e III vazam e- para O₂; PEROXISSOMO: glicólato oxidase produz H₂O₂ em fotorespiration; REAÇÃO DE FENTON: Fe²⁺ + H₂O₂ → Fe³⁺ + HO• + OH⁻ (ROS mais destrutiva). SISTEMA DE DEFESA ANTIOXIDANTE: ENZIMÁTICO: SOD (dismuta O₂•⁻ → H₂O₂ + O₂; Cu/Zn-SOD no cloroplasto, Mn-SOD na mitocôndria, Fe-SOD nos plastídios); CAT (H₂O₂ → H₂O + ½O₂, peroxissomo); APX (H₂O₂ + Ascorbato → H₂O + DHA, cloroplasto); GPX (glutation peroxidase); POD (peroxidases + compostos fenólicos). CICLO ASCORBATO-GLUTATIONA (Foyer-Halliwell-Asada): APX reduz H₂O₂ → DHA → MDHAR (MDHA redutase) → ASA reduzido; DHAR (DHA redutase, usa GSH) → ASA; GR (glutation redutase, usa NADPH) → GSH; cloroplasto mantém [ASA] = 10-30 mM, [GSH] = 1-5 mM. NÃO-ENZIMÁTICO: Ascorbato (ASA), Glutationa (GSH), α-tocoferol (membranas), β-caroteno (¹O₂ quencher), flavonoides. INTERAÇÃO MINERAL: ZN (Cu/Zn-SOD), MN (Mn-SOD), FE (Fe-SOD, CAT, APX, POD), CU (Cu/Zn-SOD, POD). PROLINA: além de osmoprotegente, é scavenger direto de ¹O₂ e ativador de APX e SOD.',
 'Taiz, L. & Zeiger, E. (2013). Plant Physiology. 5th ed. Cap. 26. Sinauer Associates.',
 '{ROS, estresse oxidativo, SOD, CAT, APX, POD, ciclo ascorbato-glutationa, GSH, ascorbato, Zn, Mn, Fe, Cu, prolina, cloroplasto, Fenton, H2O2, superóxido}'),

('Taiz & Zeiger — Respostas a estresses bióticos: JA, SA e ETH na defesa vegetal',
 'artigo', 'all',
 'ESTRESSE BIÓTICO — TRIÂNGULO DA DEFESA (Cap. 13): resistência vegetal a patógenos depende de interações entre PATÓGENO, PLANTA e AMBIENTE; três categorias de reconhecimento: PTI (Pattern-Triggered Immunity = PAMPs + PRRs), ETI (Effector-Triggered Immunity = Avr + R-proteins = HR hipersensitiva), SAR (Systemic Acquired Resistance = SA). ÁCIDO JASMONICO (JA) e JASMIL-ISOLEUCINA (JA-Ile): sintetizados via ácido α-linolênico → LOX (lipooxigenase, Fe-dependente) → 13-HPOT → AOS (aleno oxidase sintase) → AOC (aleno óxido ciclase) → OPDA → 12-oxo-PDA → JA; JA + isoleucina = COI1 (receptor ubiquitina-ligase E3) + JAZ (repressores de MYC2) → JAZ degradados → MYC2 ativo → genes de defesa. JA RESPOSTAS: síntese de inibidores de protease (PI-I, PI-II = serina proteases = anti-herbívoro); tionininas e defensinas; genes de fenilpropanoide; TERPENOS VOLÁTEIS (sesquiterpenos = atraem predadores dos herbívoros = defesa indireta). ÁCIDO SALICÍLICO (SA): sintetizado via PAL (fenilalanina amônia liase) ou ICS (isochorismate synthase); receptor NPR1 (redutase TGA-TF ativada por SA) → PR-genes (PR1 = barômetro de SAR; PR2 = β-1,3-glucanase; PR3, PR4 = quitinases); NPR1 existe como monômero (no núcleo, ativo) vs oligômero (no citosol, inativo) → S-S pontes de cisteínas regulam transição; SA muda equilíbrio → redução de pontes dissulfeto → NPR1 monômero ativo. SAR vs ISR: SAR (Systemic Acquired Resistance) = SA-dependente, ativada por patógenos necrotróficos (biótrofos causam HR, liberam SA); ISR (Induced Systemic Resistance) = JA/ET-dependente, ativada por PGPR (Pseudomonas fluorescens WCS417r). ANTAGONISMO JA/SA: JA e SA frequentemente antagônicos; SA suprime COI1-JAZ → inibe JA; JA suprime NPR1 → inibe SA; estratégia do patógeno: biotrófico induz SA que inibe JA; necrótrofo induz ET+JA. INTERAÇÃO MINERAL: Mn (ativa PAL para SA); Si (estimula SA + JA); Zn (ativa LOX para JA); N (afeta síntese de PR-proteínas nitrogenadas).',
 'Taiz, L. & Zeiger, E. (2013). Plant Physiology. 5th ed. Cap. 13. Sinauer Associates.',
 '{JA, ácido jasmônico, SA, ácido salicílico, LOX, COI1, JAZ, MYC2, NPR1, PR-proteínas, SAR, ISR, ETI, PTI, PAMP, defesa biótica, patógeno, herbívoro, Mn, Si, Zn}'),

('Taiz & Zeiger — Absorção de nutrientes: mecanismos de transporte e cinética',
 'artigo', 'all',
 'ABSORÇÃO DE NUTRIENTES (Cap. 5): MECANISMOS: (1) DIFUSÃO: movimento de íons de maior → menor concentração; limitado pelo coeficiente de difusão no solo (P = 10⁻¹³ m²/s = quase imóvel; NO₃⁻ = 10⁻⁹ m²/s; K⁺ = 10⁻¹¹ m²/s); fluxo de massa vs difusão vs intercepção radicular. (2) PROTEÍNAS TRANSPORTADORAS: ALTA AFINIDADE (HAT) = funciona em baixa [íon] (< 0.5 mM), cinética Michaelis-Menten, transportadores individuais; BAIXA AFINIDADE (LAT) = funciona em alta [íon] (> 1 mM), canais e transportadores de baixa especificidade. TRANSPORTADORES CHAVE: NITRATO: NRT1.1 (dual affinity, ativo em < 0.25 mM e > 1 mM; sensor também de N); NRT2.1+NAR2 (HAT puro); AMÔNIO: AMT1.1, AMT1.2, AMT1.3 (HAT); FOSFATO: PHT1 família (14 genes em Arabidopsis); PHO1 (exporta P do xilema); POTÁSSIO: KT/HAK/KUP (HAT); AKT (canais inward K); KOR (canais outward K); FERRO: IRT1 (importa Fe²⁺ + Zn²⁺ + Mn²⁺ + Cd²⁺); FRO2 (ferri-redutase que reduz Fe³⁺→Fe²⁺ antes de IRT1); ZINCO: ZIP1-14 (importadores de Zn²⁺ e outros cátions divalentes). GRADIENTE ELETROQUÍMICO: H⁺-ATPase de membrana plasmática (consumidora de ATP) → ejeta H⁺ → Δψ negativo (-120 a -180 mV) + ΔpH (mais ácido fora) → força proton-motive force → cotransporte H⁺/íon. PELO RADICULAR: aumenta área de absorção 10-100x; 1 g de solo explorado = 10 km de pelos radiculares em trigo; pelos radiculares colonizados por AM = amplia zona de absorção para além da depleção radicular. INTERAÇÃO COM AGROQUÍMICOS: herbicidas inibidores de ALS (imazapir, imazetapir) → reduzem crescimento radicular → menor área de absorção de P e Zn; glifosato quelata Mn → reduz absorção de Mn e molibdênio.',
 'Taiz, L. & Zeiger, E. (2013). Plant Physiology. 5th ed. Cap. 5. Sinauer Associates.',
 '{absorção de nutrientes, NRT1, NRT2, AMT1, PHT1, IRT1, FRO2, ZIP, HAT, LAT, H+-ATPase, difusão, fluxo de massa, pelo radicular, AM, Mn, Mo, glifosato, imazapir}');
