-- ─── BRADY & WEIL — THE NATURE AND PROPERTIES OF SOILS (14ª Ed., 2007) ──────
-- Solo: textura, estrutura, matéria orgânica, CTC, pH e disponibilidade de nutrientes
-- ─────────────────────────────────────────────────────────────────────────────

insert into public.conhecimento (titulo, tipo, cultura, conteudo, fonte, tags) values

('Brady & Weil — Textura do solo e sua influência na CTC e disponibilidade de nutrientes',
 'referencia', 'all',
 'TEXTURA DO SOLO (Cap. 4): classificação por proporção de areia (2-0.05 mm), silte (0.05-0.002 mm) e argila (< 0.002 mm). TRIÂNGULO TEXTURAL USDA: textura argilosa (> 40% argila), argilossiltosa (> 40% argila + > 40% silte), franco-argilosa, franca (20-30% argila, 25-50% silte), siltosa, arenosa (> 85% areia). CONSEQUÊNCIAS PRÁTICAS: ARGILA: maior superfície específica (1-800 m²/g, vs areia = 0.01 m²/g); maior CTC; melhor retenção de água e nutrientes; mais suscetível a compactação; drenagem mais lenta. AREIA: macro-poros dominantes, excelente drenagem, baixíssima retenção de nutrientes; lixiviação intensa de K⁺, Mg²⁺, NO₃⁻, B. SILTE: propriedades intermediárias, suscetível à formação de crosta na superfície. CTC (CAPACIDADE DE TROCA CATIÔNICA): argila minerais têm CTC permanente (substituição isomórfica de Si⁴⁺ por Al³⁺ nas esmectitas) E dependente de pH (grupos -OH de argilas 1:1 como caulinita e de SH); solos argilosos = 15-60 cmolc/dm³; solos arenosos = 1-5 cmolc/dm³; matéria orgânica contribui 150-300 cmolc/dm³ por unidade de MO. MANEJO: solos arenosos precisam de aplicações mais frequentes e parceladas de K, Mg, B, N; solos argilosos retêm mais K e Mg mas podem ter problemas de compactação; adubação em solos arenosos deve seguir diagnose de solo frequente (cada 1-2 anos).',
 'Brady, N.C. & Weil, R.R. (2007). The Nature and Properties of Soils. 14th ed. Prentice Hall, New Jersey.',
 '{textura, argila, areia, silte, CTC, capacidade de troca catiônica, superfície específica, retenção de nutrientes, lixiviação, K, Mg, B, N, compactação, solos arenosos, solos argilosos}'),

('Brady & Weil — pH do solo: tampão, efeitos na disponibilidade de nutrientes e calagem',
 'referencia', 'all',
 'pH DO SOLO (Cap. 8): escala logarítmica (pH = -log[H⁺]); variação típica em solos agrícolas = pH 4.0-8.5; CAPACIDADE TAMPÃO: resistência à mudança de pH = função da CTC e da quantidade de íons ácidos (H⁺ + Al³⁺) em solução e adsorvidos; solos argilosos = maior poder tampão = precisam de mais calcário para corrigir o pH. EFEITOS DO pH NA DISPONIBILIDADE DE NUTRIENTES (curva de Truog): MÁXIMA DISPONIBILIDADE: N (pH 6.0-8.0 via nitrificação ótima); P (pH 6.0-7.0 = mínima fixação); K, Ca, Mg, S (pH > 6.5); B (pH 6.0-7.5); Cu, Zn (pH 6.0-7.0). MÍNIMA DISPONIBILIDADE (BLOQUEIO): P: pH < 5.5 = fixação por Al³⁺ e Fe³⁺ como FePO₄ e AlPO₄; pH > 7.5 = fixação por Ca como Ca₃(PO₄)₂; Fe, Mn: pH < 5.5 = muito solúveis (toxicidade); pH > 7 = precipitados (deficiência); Zn, Cu, B: pH > 7 = insolúveis; Mo: único que aumenta com pH alcalino (molibdênio mais disponível acima de 6.5). ALUMÍNIO: Al³⁺ em pH < 5.5 = inibe divisão celular no ápice radicular (Al³⁺ inibe ATPases e enzimas); em concentrações > 1-2 μmol/L = fitotóxico para maioria das culturas; soja tolera < 10% saturação Al; milho tolera < 15-20%; arroz de terras altas mais sensível. CALAGEM PARA SOJA: elevar pH CaCl₂ para 5.8-6.2 (Embrapa) ou pH H₂O 6.0-6.5; calcário calcítico (CaCO₃) vs dolomítico (CaCO₃+MgCO₃); PRNT = poder relativo de neutralização total (corrigir pela granulometria); dose = V% desejada x CTC pH 7.0 / PRNT; incorporar 60-90 dias antes do plantio idealmente.',
 'Brady, N.C. & Weil, R.R. (2007). The Nature and Properties of Soils. 14th ed. Prentice Hall. / Embrapa Soja (2013).',
 '{pH, tamponamento, calagem, calcário, Al, alumínio, P, Fe, Mn, Zn, B, Mo, disponibilidade, PRNT, CTC, V%, saturação de Al, soja, milho}'),

('Brady & Weil — Matéria orgânica do solo (MO): funções, mineralização e sequestro de carbono',
 'referencia', 'all',
 'MATÉRIA ORGÂNICA DO SOLO (MO) (Cap. 11): composta de HÚMUS (SH + materiais humificados = 65-75% da MO estável), resíduos vegetais parcialmente decompostos (10-15%), biomassa microbiana (5-10%), raízes vivas e mortas (5-10%). FUNÇÕES DA MO: (1) NUTRICIONAL: mineralização libera N (1-3% N na MO orgânica), P (0.1-0.4%), S (0.05-0.1%), micronutrientes; taxa de mineralização = 1-3% da MO/ano em trópicos; 30 g MO/kg solo com 3% N = 90 mg N/kg solo potencial; (2) FÍSICA: melhora estrutura do solo (formação de macroagregados com argila), aumenta capacidade de retenção de água (1 g MO retém 20 g H₂O), reduz densidade do solo, diminui erosão; (3) QUÍMICA: CTC de SH = 150-300 cmolc/dm³ (10x mais que caulinita); quelação de micronutrientes; tamponamento de pH; (4) BIOLÓGICA: substrato para biomassa microbiana; regulação de doenças de solo. MINERALIZAÇÃO: processo de decomposição de MO em CO₂ + H₂O + nutrientes minerais; controlada por: temperatura (Q₁₀ = 2-3, duplica por 10°C de aumento), umidade (máximo em θ = 60% WFPS), relação C:N (< 20:1 = mineralização líquida; 20-30:1 = equilíbrio; > 30:1 = imobilização); qualidade do resíduo (lignina, taninos, polifenóis retardam decomposição). SEQUESTRO DE C: plantio direto + cobertura = input de resíduos > saída por mineralização = acúmulo; conversão de degradado em plantio direto = sequestro de 0.5-1 t C/ha/ano; objetivo: aumentar de 20-30 g MO/kg para > 35-40 g MO/kg em solos do cerrado. INTERAÇÃO COM NUTRIENTES: MO alta → maior buffer de pH → menor toxicidade de Al; MO alta → CTC alta → menor lixiviação de K, Mg, Ca; MO chelates → micronutrientes mais móveis no solo.',
 'Brady, N.C. & Weil, R.R. (2007). The Nature and Properties of Soils. 14th ed. Prentice Hall.',
 '{matéria orgânica, MO, húmus, mineralização, C:N, N, P, S, CTC, estrutura do solo, sequestro de carbono, plantio direto, lixiviação, micronutrientes, Al, biodegradação}'),

('Brady & Weil — Dinâmica do potássio no solo: formas, lixiviação e adsorção',
 'referencia', 'all',
 'POTÁSSIO NO SOLO (Cap. 16): FORMAS: (1) K solúvel (< 1% do total) = K⁺ em solução, imediatamente disponível; (2) K trocável (1-5%) = K⁺ adsorvido nos sítios de CTC, em equilíbrio com solução; (3) K não-trocável (10-50%) = K preso em espaços entrefolha de micas e argilominerais (ilita, vermiculita) = liberação lenta; (4) K mineral da rocha matriz (50-90%) = feldspatos, micas = liberação muito lenta (séculos). TAMPÃO DE K: tampão de K = capacidade do solo de manter [K⁺] na solução = função da CTC e da proporção de K nos sítios trocáveis; solos com alta CTC argilosa = maior tampão; solos arenosos = baixo tampão = K lixivia facilmente. LIXIVIAÇÃO: K⁺ = cátion monovalente = menos adsorvido que Ca²⁺ e Mg²⁺ (menor força de adsorção); em solos arenosos tropicais com alta precipitação = perda de 20-60 kg K/ha/ano por lixiviação; parcelamento da adubação potássica em solos arenosos = obrigatório para reduzir perdas. ANTAGONISMO: K⁺ x Mg²⁺ (competição no CEC e nos transportadores HKT da membrana plasmática); K⁺ x Ca²⁺ (mesmo mecanismo, menor intensidade); excesso de K na CTC (K/CTC > 5-6%) = risco de induzir carência de Mg. ADUBAÇÃO DE K: KCl (60% K₂O, mais econômico); K₂SO₄ (50% K₂O, menos Cl, melhor para Cl-sensíveis); KNO₃ (foliar, mais solúvel); K magnésio (granulado K+Mg, evita competição); dose = demanda da cultura − teor de K trocável × fator solo.',
 'Brady, N.C. & Weil, R.R. (2007). The Nature and Properties of Soils. 14th ed. Prentice Hall.',
 '{potássio, K, lixiviação, CEC, CTC, K trocável, tampão de K, Mg, Ca, KCl, K2SO4, KNO3, solos arenosos, parcelamento, adubação, soja, milho}'),

('Brady & Weil — Frações de fósforo no solo: fixação, mobilidade e estratégias de manejo',
 'referencia', 'all',
 'FÓSFORO NO SOLO (Cap. 17): FRAÇÕES (sequencial de Hedley): P prontamente disponível (H₂O + NaHCO₃); P moderadamente disponível (NaOH); P ligado ao Ca (HCl); P recalcitrante (P em ácidos húmicos + residual); SOLOS TROPICAIS (Latossolos, Oxissolos): 60-80% do P total = P inorgânico ligado a óxidos de Fe (goethita, hematita) e Al (gibbsita) = P pouco disponível; FIXAÇÃO QUÍMICA DE P: P + Fe³⁺/Al³⁺ → FePO₄ / AlPO₄ insolúveis; ou P adsorvido em grupos -OH dos óxidos de Fe/Al via troca de ligantes; Latossolo Vermelho do cerrado = capacidade de fixação de 1000-3000 mg P/dm³ solo (muito alta); IMPLICAÇÃO AGRONÔMICA: dose de P para Latossolo atingir 12 mg P/dm³ = 200-400 kg P₂O₅/ha (aplicação inicial) vs 30-60 kg P₂O₅/ha em manutenção. ESTRATÉGIAS PARA AUMENTAR EFICIÊNCIA DE P: (1) Colocação no sulco de plantio (band = reduz contato com solo, reduz fixação); (2) Acidificação localizada (acidulantes no sulco; raízes acidificam rizosfera); (3) Micorriza arbuscular (hifas exploram P não-depletado além da rizosfera); (4) PGPR solubilizadoras de P; (5) Ácidos húmicos e fúlvicos competem com P pelos sítios de fixação (bloqueio de sítios de adsorção). MOBILIDADE: P move-se no solo quase exclusivamente por difusão (10⁻¹³ m²/s); zona de depleção = 1-3 mm ao redor da raiz; por isso volume de raízes e pelos = determinante para absorção de P.',
 'Brady, N.C. & Weil, R.R. (2007). The Nature and Properties of Soils. 14th ed. Prentice Hall. / Novais, R.F. & Smyth, T.J. (1999). Fósforo em solo e planta em condições tropicais. UFV.',
 '{fósforo, P, fixação de P, Latossolo, oxissolo, cerrado, frações de Hedley, solubilização, micorriza, PGPR, ácido húmico, difusão, zona de depleção, sulco, band, goethita, gibbsita}');
