-- ─── NOVAIS et al. — FERTILIDADE DO SOLO (SBCS, 2007) ───────────────────────
-- Micronutrientes, zinco, boro, manganês, ferro, molibdênio em solos tropicais
-- ─────────────────────────────────────────────────────────────────────────────

insert into public.conhecimento (titulo, tipo, cultura, conteudo, fonte, tags) values

('Novais et al. — Zinco no solo: formas, disponibilidade e calagem',
 'referencia', 'all',
 'ZINCO (Zn) NO SOLO (Cap. 11 — Novais et al.): FORMAS: Zn²⁺ em solução (< 0.1% do total); Zn adsorvido (troca de cátions e adsorção específica em óxidos Fe/Al); Zn ligado à MO (compostos orgânicos-Zn); Zn mineral (silicatos, smithsonita ZnCO₃). DISPONIBILIDADE: afetada fortemente pelo pH — cada unidade de pH acima de 6.0 reduz Zn²⁺ em solução 10-100x (reação: Zn(OH)⁺ → Zn(OH)₂ → ZnO); FIXAÇÃO: em solos com pH > 6.5 + P alto → Zn₃(PO₄)₂ insolúvel; P alto + Zn baixo = antagonismo P-Zn clássico dos Oxissolos; relação P:Zn ideal foliar = 50:1 (acima = deficiência induzida por P). DIAGNOSE: análise de solo com DTPA-TEA (pH 7.3) = extrator padrão; valores críticos: < 0.5 mg Zn/dm³ = deficiente (CQFS RS/SC); 0.5-1.0 mg/dm³ = médio; > 1.0 mg/dm³ = adequado. DIAGNOSE FOLIAR SOJA (V3-V4): < 21 mg/kg = deficiente; 21-50 mg/kg = adequado; > 50 mg/kg = alto. ADUBAÇÃO CORRETIVA: SOLO = 2-5 kg/ha Zn (sulfato de Zn, 20-22% Zn) ou óxido de Zn (50-80% Zn); aplicar ao solo a cada 2-3 anos; FOLIAR = 150-300 g/ha Zn-EDTA (quelatado = maior mobilidade) ou 300-500 g/ha ZnSO₄·7H₂O (barato mas menos eficiente em solo alcalino). INTERAÇÃO COM Mo: solos ácidos com pH < 5.5 = Zn e Mo deficientes simultaneamente; calagem corrige ambos (Zn disponível em 6.0-6.5; Mo disponível > 6.5).',
 'Novais, R.F. et al. (2007). Fertilidade do Solo. SBCS, Viçosa / CQFS RS/SC (2016). Manual de Calagem e Adubação.',
 '{Zn, zinco, pH, fixação, P, antagonismo P-Zn, DTPA, disponibilidade, diagnose foliar, sulfato de Zn, EDTA, quelatado, calagem, Mo, soja}'),

('Novais et al. — Boro no solo: calagem, chuva e deficiência em florescimento',
 'referencia', 'all',
 'BORO (B) NO SOLO: FORMAS: ácido bórico H₃BO₃ (forma predominante em pH < 7, não-iônico, muito móvel = suscetível à lixiviação); tetraborato B(OH)₄⁻ (forma em pH > 9); B adsorvido em Al/Fe óxidos e MO (ligação reversível, pH-dependente: máxima adsorção = pH 7-9; B muito disponível em pH 5.5-6.5 e muito pouco em pH > 7.5). DINÂMICA NO SOLO: B = micronutriente mais lixiviado em solos tropicais (exceção parcial = carga variável fixa B nos óxidos); em período seco, B fica retido em óxidos e MO → deficiência funcional; em chuva intensa = B lixivia novamente. CALAGEM: calagem eleva pH → aumenta adsorção de B → reduz B em solução → deficiência induzida por calagem! = fenômeno frequente em solos do cerrado após calagem para V% 70% sem correção de B. DIAGNOSE SOLO: extrator ácido clorídrico (Embrapa) ou água quente (Berger-Truog): < 0.3 mg B/dm³ = deficiente; 0.3-1.0 = adequado; > 1.0 = alto (toxicidade possível acima de 2-3 mg/dm³). DIAGNOSE FOLIAR SOJA: < 30 mg B/kg = deficiente; 30-60 = adequado; > 60-100 = risco de toxicidade. ADUBAÇÃO: SOLO = 0.5-2 kg/ha B (bórax 10.5% B, ou borogran, B+ granulado) = solo ácido ou por ocasião da calagem; FOLIAR = 100-300 g/ha B (ácido bórico 17.5% B ou octaborato de sódio) = aplicar em V5-V6 e R1 (pré e início do florescimento) OBRIGATORIAMENTE em soja; intervalo de segurança entre duas aplicações de B = 10-14 dias (toxicidade acumulativa). FUNÇÃO CRÍTICA EM FLORESCIMENTO: B essencial para germinação do grão de pólen e crescimento do tubo polínico → deficiência em R1 = queda imediata de flores e aborto de vagens jovens = perda econômica grave.',
 'Novais, R.F. et al. (2007). Fertilidade do Solo. SBCS, Viçosa. / CQFS RS/SC (2016).',
 '{boro, B, lixiviação, calagem, pH, H3BO3, adsorção, deficiência, toxicidade, florescimento, tubo polínico, V5, R1, bórax, ácido bórico, soja, foliar, cerrado}'),

('Novais et al. — Manganês e ferro: toxicidade em solos ácidos e alagados',
 'referencia', 'all',
 'MANGANÊS (Mn) NO SOLO: FORMAS: Mn²⁺ (divalente, solúvel, absorvível; pH < 5.5 = alta concentração); Mn³⁺ (intermediária); Mn⁴⁺ (MnO₂ = insolúvel, precipitado em pH > 6.5); TOXICIDADE CLÁSSICA: pH < 5.5 → Mn²⁺ aumenta em solução exponencialmente (pH 5.5 = 10 μmol/L; pH 5.0 = 100 μmol/L; pH 4.5 = 1000 μmol/L); > 300-500 μmol/L = fitotóxico para soja; sintomas = pontos marrons nas folhas velhas ("escoriose"), clorose; inibe absorção de Mg, Fe, Mo. CALAGEM CORRIGE: elevação de pH 5.5 → 6.0 = Mn disponível cai 10x; mais importante que adubação de Mn para corrigir toxicidade. FERRO (Fe) NO SOLO: Fe²⁺ (divalente, solúvel; solos reduzidos = alagados pH < 6.5, Fe²⁺ aumenta muito); Fe³⁺ (pH > 7 = hidróxidos e oxihidróxidos insolúveis); TOXICIDADE DE Fe EM SOLOS ALAGADOS: bronzeamento foliar, manchas ferrugem, clorose; rice iron toxicity = > 500 μmol Fe²⁺/L; drenagem do solo reduz Fe²⁺; Si foliar e Ca foliar reduzem absorção e dano. DIAGNOSE DE Fe E Mn SOLO: Fe (DTPA): < 4.5 mg/dm³ = deficiente; Mn (DTPA): < 1.0 mg/dm³ = deficiente; valores CQFS. DEFICIÊNCIA DE Fe EM SOJA: solos calcários (pH > 7 + alto Ca) = amarelão da soja; Fe³⁺ precipita como Fe(OH)₃; soja = estratégia I para absorção de Fe (FRO2 reduz Fe³⁺ → Fe²⁺; IRT1 absorve Fe²⁺); em pH alto, FRO2 inibida; CORREÇÃO: quelatos de Fe (EDTA-Fe, EDDHA-Fe = mais estável em pH > 6.5) foliar: 500-1000 g/ha.',
 'Novais, R.F. et al. (2007). Fertilidade do Solo. SBCS, Viçosa. / Marschner, H. (2012).',
 '{Mn, manganês, Fe, ferro, toxicidade, pH ácido, alagamento, calagem, DTPA, soja, amarelão, FRO2, IRT1, EDTA-Fe, EDDHA-Fe, Si, Ca, bronzeamento, escoriose}'),

('Novais et al. — Enxofre e molibdênio: demanda, déficit e nutrição de leguminosas',
 'referencia', 'all',
 'ENXOFRE (S) NO SOLO: FORMAS: SO₄²⁻ (sulfato, forma absorvível) = em equilíbrio com S adsorvido em óxidos (cargas positivas) e S em MO (mineralização libera SO₄²⁻); DINÂMICA: S é intermediariamente móvel; em Oxissolos com óxidos de Fe/Al = SO₄²⁻ adsorvido nos horizontes B (subsuperfície) → função de reservatório; precipitação ácida contribui com S; pastagem degradada = menor entrada de S via MO. DIAGNOSE: análise de solo Embrapa (S-SO₄ extraído com Ca(H₂PO₄)₂ 0.01 M): < 5 mg/dm³ = deficiente; 5-30 = adequado; > 30 = alto. SOJA: exige ~ 15-25 kg S/ha/ciclo; em solos com MO > 3% = provável suficiência; em MO < 2% ou solos arenosos = aplicar S. ADUBAÇÃO: gesso agrícola (CaSO₄·2H₂O, 16% S + 24% Ca) = fonte mais usada; 200-300 kg/ha de gesso = 32-48 kg S/ha; sulfonato de amônio (24% S + 21% N); sulfato de K (18% S); evitar solo úmido para gesso (muito solúvel = lixivia em chuvas intensas). MOLIBDÊNIO (Mo): FORMAS: MoO₄²⁻ (molibdato, forma absorvível, ANIÔNICO — comportamento oposto ao outros micronutrientes); pH: disponibilidade AUMENTA com pH (contrário dos outros micronutrientes); em solos ácidos (pH < 5.5) = Mo retido em óxidos de Fe e Al → deficiente; calagem = aumenta disponibilidade de Mo. DIAGNOSE SOLO (Embrapa, oxalato ácido): < 0.1 mg/dm³ = deficiente; ADUBAÇÃO: foliar 20-50 g Mo/ha (molibdato de sódio 39% Mo ou molibdato de amônio) = dose muito pequena; tratamento de sementes com Mo: 3-12 g Mo/50 kg semente = mais eficiente para soja; CO + Mo via tratamento de sementes = padrão para otimizar FBN.',
 'Novais, R.F. et al. (2007). Fertilidade do Solo. SBCS, Viçosa. / Embrapa Soja (2013).',
 '{S, enxofre, gesso, SO4, CaSO4, MO, oxidação, Mo, molibdênio, molibdato, FBN, pH, soja, tratamento de sementes, Co, diagnose, DTPA, oxalato ácido}'),

('Novais et al. — Cálcio e magnésio: relações no solo, calagem dolomítica e gessagem',
 'referencia', 'all',
 'CÁLCIO (Ca) E MAGNÉSIO (Mg) NO SOLO: FONTES: calcário calcítico (CaCO₃, 30-40% Ca, < 5% Mg); calcário dolomítico (CaCO₃·MgCO₃, 20-30% Ca + 8-12% Mg); Cal virgem (CaO); hidratada (Ca(OH)₂); gesso (CaSO₄ = Ca sem poder de neutralização de H⁺ = não corrige pH, mas fornece Ca e S). RELAÇÕES Ca:Mg NO SOLO: relação ideal = 3:1 a 6:1 (em cmolc/dm³ na CTC); excesso de Mg (Ca:Mg < 2:1) = Solo magnésiano = maior absorção de Mg reduz Ca e K; solo com >60% saturação de Ca = pode limitar Mg. SATURAÇÃO DE BASES: objetivo para soja = V% 70-75% (Embrapa); Ca deve corresponder a 70-75% das bases trocáveis; Mg deve ser 10-15%; K deve ser 2-5%; GESSAGEM: gesso agrícola = aplicado quando solo subterrâneo tem Al³⁺ alto (>0.5 cmolc/dm³) em profundidade OU quando Ca do subsolo é baixo (<0.5 cmolc/dm³); Ca² + SO₄²⁻ do gesso migram pelo perfil → Ca substitui Al no subsolo → raízes aprofundam → maior absorção de água em seca; dose: 50-60 kg gesso/t argila (solo argiloso = 3 t/ha; médio = 2 t/ha; arenoso = 1 t/ha); EFEITO EM SOJA: gessagem = maior aprofundamento radicular em 20-30 cm → +5-15% produtividade em anos de déficit hídrico. INTERAÇÃO Mg-K: Ca:Mg:K = 15:5:1 = relação ideal; excesso de K na adubação (K/CTC > 5-6%) = risco de carência de Mg; em solos arenosos = aplicar Mg via calagem dolomítica ou sulfato de Mg foliar.',
 'Novais, R.F. et al. (2007). Fertilidade do Solo. SBCS, Viçosa. / Sfredo, G.J. (2008). Soja no Brasil. Embrapa.',
 '{Ca, Mg, cálcio, magnésio, calcário calcítico, dolomítico, gesso, gessagem, CaSO4, V%, saturação de bases, Al, subsolo, enraizamento, soja, K, relação Ca:Mg:K}');
