-- ─── TAIZ & ZEIGER — HORMÔNIOS VEGETAIS AVANÇADO (Cap. 19-21, 5ª Ed. 2013) ───
-- Auxinas, giberelinas, citocininas, ABA e brassinosteroides em profundidade
-- ─────────────────────────────────────────────────────────────────────────────

insert into public.conhecimento (titulo, tipo, cultura, conteudo, fonte, tags) values

('Taiz & Zeiger — Auxinas (IAA): biossíntese, transporte polar e ação celular',
 'artigo', 'all',
 'AUXINAS (Cap. 19): BIOSSÍNTESE: IAA (ácido indol-3-acético) = hormônio principal; síntese dominante = via TRIPTOFANO (precursor): ROTA IPyA = TRP → IPyA (piruvato indol-3-) → IAA (YUCCA/FMO); ROTA IAAId = TRP → IAAId (indolacetamida via bactérias ou enzimas AMIDA HIDROLASE); ROTA ISA = não-triptofano = via IPyP diretamente; LOCALIZAÇÃO: meristemas apicais, folhas jovens, embriões em desenvolvimento, frutos. TRANSPORTE POLAR (PAT): TRANSPORTADORES: AUX1/LAX = importadores de IAA (auxin influx carriers); PIN (PIN-FORMED): PIN1, PIN2, PIN3, PIN4, PIN7 = exportadores (eflux carriers), localizados assimetricamente na membrana basal → direciona IAA basipetalmente; ABP1 + TMK1 = receptores na membrana que respondem ao IAA em ms. MECANISMO MOLECULAR: TIR1 (F-box receptor) + Aux/IAA repressores (domínio II = degron) → IAA liga TIR1 → SCF^TIR1 ubiquitina Aux/IAA → degradação 26S-proteassomo → ARFs (Auxin Response Factors) libertos → ativam genes de resposta. ATIVAÇÃO DE EXPANSINAS (hipótese do crescimento ácido): IAA → ativa H⁺-ATPase → exocitose de H⁺ → pH da parede ↓ de 7→5 → expansinas XTH ativadas → clivam celulose/hemicelulose → parede relaxa → entrada de K⁺+H₂O → elongação. GRADIENTE IAA E GRAVITROPISMO: coluna de amiloplastos (estatólitos) sedimenta → PIN3 relocado → IAA migra lateralmente → elongação diferencial → curvatura para baixo. INTERAÇÃO MINERAL: ZN (cofator de triptofano sintase = enzima da síntese de IAA; deficiência de Zn → reduz IAA → roseta); B (integridade de PIN via borato-pectina complexo); N (triptofano é N-aminoácido).',
 'Taiz, L. & Zeiger, E. (2013). Plant Physiology. 5th ed. Cap. 19. Sinauer.',
 '{auxina, IAA, TRP, triptofano, PIN, AUX1, TIR1, SCF, ARF, expansina, transporte polar, PAT, gravitropismo, Zn, B, N, H+-ATPase, crescimento ácido, meristema}'),

('Taiz & Zeiger — Giberelinas: biossíntese, deactivação e respostas fisiológicas em soja',
 'artigo', 'all',
 'GIBERELINAS (Cap. 20): mais de 136 giberelinas (GA) identificadas; bioativas em plantas superiores = GA₁, GA₃, GA₄, GA₇; síntese no retículo endoplasmático + plastidios. BIOSSÍNTESE: GGPP (géranilgéranilpirofosfato) → ent-copalil difosfato (ent-CDP) via ent-CPPS (COPALIL DIPHOSPHATE SYNTHASE) → ent-caureno via KS (ENTE-KAURENE SYNTHASE) → ent-caurenol → GA₁₂ via P450 + Fe/Mn-oxidases → GA₂₀ → GA₁ (ativo); DEACTIVAÇÃO: GA 2-OXIDASE = inativa GA₁ → GA₈; CONTROLE MODULADO POR FEEDBACK: GA₁ ativa DELLA proteínas → DELLA ativa 2-oxidase → degrada mais GA₁ (auto-regulação). MODO DE AÇÃO: DELLA (motivo DELLA = Asp-Glu-Leu-Leu-Ala) = repressores globais de crescimento; GA + GID1 (receptor solúvel) → GID1-GA-DELLA = SCF^SLY1 → ubiquitinação DELLA → degradação → MYC, MYBs liberados → genes de crescimento. RESPOSTAS FISIOLÓGICAS: elongação do caule (GAs estimulam células subapicais, não o meristema); germinação de sementes (GA activa α-amilases via GAMYB); florescimento de plantas de dia longo (GA integra sinal de fotoperíodo → CO → FT → flor); desenvolvimento de frutos; quebra de dormência; RELAÇÃO COM BRASSINOSTEROIDES: BR e GA cooperam → BR aumenta elongação celular, GA aumenta elongação do nodo; ambos ativam expansinas e XTHs. INTERAÇÃO MINERAL: Mn (cofator de ent-caureno sintase e GA-oxidases; Mn-deficiência = internódios curtos); Fe (Fe-2-oxoglutarato dioxigenases nas últimas etapas da síntese de GA).',
 'Taiz, L. & Zeiger, E. (2013). Plant Physiology. 5th ed. Cap. 20. Sinauer.',
 '{giberelina, GA, DELLA, GID1, SCF, SLY1, biossíntese, ent-caureno, GAMYB, elongação, florescimento, germinação, brassinosteroide, Mn, Fe, dormência, soja}'),

('Taiz & Zeiger — Citocininas: biossíntese, sinal de nitrogênio e senescência',
 'artigo', 'all',
 'CITOCININAS (Cap. 21): CLASSES: adenina-isopenteniladenina (iP, tZP = trans-zeatina = mais ativo em soja); dihidrozeatina (DHZ); ciszeatin; SÍNTESE: isopentenil difosfato (IPP, via MEP no plastídio) + AMP → iPRMP via ADENILATO ISOPENTILTRANSFERASE (IPT); iPRMP → tZRMP via CYP735A (P450-oxidase, Fe-dependente) → exportação via xilema. RECEPTORES: AHK (Arabidopsis Histidine Kinase) = AHK2, AHK3, AHK4/CRE1 = receptores de membrana com domínio CHASE; CK + AHK → phosphorylation AHP → B-ARRs (ativadores de resposta) + A-ARRs (repressores). FUNÇÕES FISIOLÓGICAS: (1) DIVISÃO CELULAR: CDK (cyclin-dependent kinase) requerida; CK ativa ciclina D (CYCD3;1) → progresso G1/S; (2) SINAL DE N: raízes ricas em N produzem mais CK → transportadas para parte aérea → inibem senescência foliar, ativam genes de assimilação de N; (3) ATRASO DE SENESCÊNCIA: CK inibem proteases, clorofilases; senescência acelerada por queda de CK (estresse, envelhecimento); (4) SINK DE DRENO: CK produzidas em sementes → atraem assimilados para grãos em enchimento; (5) ABERTURA ESTOMATAL: CK ativa KAT1 → K⁺ entra na célula guarda → turgor sobe → abertura (oposto ao ABA). INTERAÇÃO MINERAL: N (síntese de CK depende de NO₃⁻ disponível — AHK4 no meristema radicular sente N via CK); Mg (ativa adenilato quinase → síntese de AMP para CK); K (na célula guarda). BIOESTIMULANTES: kinetin, BAP (6-benzilaminopurina) usados comercialmente; extrato de algas ≈ CK; aplicação foliar R1-R2 = retém flores, reduz aborto.',
 'Taiz, L. & Zeiger, E. (2013). Plant Physiology. 5th ed. Cap. 21. Sinauer.',
 '{citocinina, CK, AHK, ARR, IPT, tZP, zeatin, N, Mg, K, sinal de N, divisão celular, senescência, abertura estomatal, sink, grãos, florescimento, BAP, kinetin, extrato de algas}'),

('Taiz & Zeiger — Etileno e ABA: síntese, sinalização e papéis no amadurecimento e estresse',
 'artigo', 'all',
 'ETILENO (Cap. 22): GÁS SIMPLES mais potente em pg/g (1 nL/L = ativo); precursor = MET (metionina) → SAM (S-adenosilmetionina) via SAM sintetase → ACC (ácido 1-aminociclopropano-1-carboxílico) via ACC sintase (ACS, inibida por Co²⁺, análogos de piridoxal) → ETILENO via ACC oxidase (ACO, requer O₂ e ASA como cofatores; Fe-dependente); REGULAÇÃO: IAA e MeJA aumentam ACS; SINALIZAÇÃO: ETR1+ETR2 (receptores de membrana com domínio histidina-kinase; quando ET se liga → inativação → CTR1 inativado → EIN2 e EIN3 ativados → genes de resposta ERF). RESPOSTAS: amadurecimento de frutos (clímax ETH → ativa genes da biossíntese de antocianinas, suavização, aroma); abscisão (ETH + IAA baixo → ativa poligalacturonases e celulases na zona de abscisão → folhas caem); tripla resposta etileno (escuridão + ETH → elongação reduzida + engrossamento + curvatura gravitrópica = sinal de obstáculo); senescência foliar (ETH + CK-deficiência). ÁCIDO ABSCÍSICO (ABA) (Cap. 23): síntese = zeaxantina → violaxantina → xantoxina → ABA-aldeído → ABA (NCED = 9-cis-epoxycarotenoid dioxygenase = enzima-chave; Mo-dependente para a etapa final: aldeído oxidase); SINALIZAÇÃO: PYR/PYL + ABA → inibe PP2C → SnRK2 ativa OST2 (H+-ATPase = fecha) + SLAC1 (ânion = fecha) + ativa síntese de AOS2 (JA coopera em estresse); FUNÇÕES: dormência de sementes (catabolismo de GA + ativação de inibidores de germinação); tolerância ao estresse (acumula compatible solutes); fechamento estomático; controle de desenvolvimento de sementes. INTERAÇÃO MINERAL: Ca²⁺ como segundo mensageiro de ABA (Ca²⁺ ativa CDPK que fosforila SLAC1); S (SAM = S-aminoácido para síntese de etileno); Cu e S para ACO.',
 'Taiz, L. & Zeiger, E. (2013). Plant Physiology. 5th ed. Cap. 22-23. Sinauer.',
 '{etileno, ET, ACS, ACO, ACC, ETR1, EIN3, amadurecimento, abscisão, ABA, PYR/PYL, PP2C, SnRK2, SLAC1, NCED, Mo, Ca, S, Cu, senescência, dormência, estômato, IAA}'),

('Taiz & Zeiger — Brassinosteroides e Jasmonatos: papel no desenvolvimento e defesa',
 'artigo', 'all',
 'BRASSINOSTEROIDES (BR) (Cap. 24 suplement): esteroides vegetais; brassinolídeo (BL) = mais ativo; síntese = campesterol → brassinolídeo via CYP90 (citocromo P450 + O₂, Fe-dependente); RECEPTOR: BRI1 (leucine-rich receptor kinase) + BAK1 (co-receptor) → fosforilação em cascata → inativa BIN2 (GSK3-like quinase = repressor) → BES1/BZR1 (fatores de transcrição) ativados → genes de elongação e resposta a estresse. FUNÇÕES: elongação celular (sinergismo com IAA + GA); estresse: BR melhora tolerância a seca, frio, salinidade, metais pesados (induz antioxidantes SOD+CAT+APX); florescimento e desenvolvimento de grãos; fotomorfogênese; APLICAÇÕES: 24-epibrassinolídeo exógeno (0.01-1 μM) foliar ou na semente = aumento de rendimento em soja, milho e arroz; efeito especialmente em estresse de calor+seca (R1-R4); Brassinolídeo aumenta fertilidade do pólen em alta temperatura. JASMONATOS (JA) (Cap. 13): ácido jasmônico + MeJA (volátil) + JA-Ile (bioativo); síntese = ácido linolênico (liberado de membranas por fosfolipase A = ativada por ferimento ou elicitores) → LOX (Fe-dependente) → 13-HPOT → AOS → AOC → OPDA → JA (beta-oxidação peroxissomal); JA-Ile = COI1 (receptor) → degrada JAZ repressores → MYC2, MYC3 ativos → síntese PI-II, VSP2, PAL (fenilpropanoide), terpenoides. CROSSTALK: JA+ETH (cooperam contra necrotrofos); JA+SA (antagonismo); BR+JA (BR reduz JA em tecidos jovens = evita autoimunidade); ETH+JA (sinergia em defesa).',
 'Taiz, L. & Zeiger, E. (2013). Plant Physiology. 5th ed. Cap. 13, 24. Sinauer.',
 '{brassinosteroide, BR, BRI1, BES1, BZR1, BIN2, elongação, jasmato, JA, LOX, COI1, JAZ, MYC2, SA, ETH, Fe, defesa, florescimento, seca, calor, soja, milho}');
