-- ─── BIOFERTILIZANTES / FISIOLOGIA — PROLINA, ANTIOXIDANTES E ESTRESSE SOJA ──
-- Osmoprotetores, enzimas antioxidantes e respostas fisiológicas a estresses
-- ─────────────────────────────────────────────────────────────────────────────

insert into public.conhecimento (titulo, tipo, cultura, conteudo, fonte, tags) values

('Prolina vegetal: biossíntese, função e acúmulo em estresse hídrico e térmico em soja',
 'artigo', 'all',
 'PROLINA: aminoácido imino, derivado do glutamato; em condições de estresse, é o principal osmoprotegente acumulado em plantas (pode chegar a 80-100 mM em células de folhas estressadas vs. 0.5 mM no controle); BIOSSÍNTESE DE PROLINA: GLUTAMATO → γ-semialdehído glutâmico (GSA) via P5CS (delta-1-pirrolina-5-carboxilato sintetase, NADPH-dependente) → P5C → Prolina via P5CR (prolina redutase); via alternativa de ornitina → OAT → GSA → P5C → Prolina (predomina em raízes). DEGRADAÇÃO: Prolina → P5C → Glutamato via ProDH (prolina desidrogenase, mitocondrial; O₂-dependente; produz H₂O₂); quando estresse aliviado = prolina degrada → glutamato reutilizado. FUNÇÕES MÚLTIPLAS: (1) Osmorregulação: acumulação ajusta Ψs sem toxicidade; (2) Proteção de proteínas e membranas: forma coluna de moléculas de água ao redor de proteínas (chaperonas químicas), estabiliza membranas em dessecação; (3) Scavenger de ROS: prolina + ¹O₂ → produtos não-tóxicos; ativa POD, APX, CAT indiretamente; (4) Fonte de C e N na recuperação: ProDH libera C e N ao glutamato após o estresse; (5) Sinalização: P5C produto = sinal de redox para resposta ao estresse. REGULAÇÃO: ABA ativa P5CS1 e P5CS2 (genes de P5CS têm ABA-responsive elements); luz azul + seca = co-reguladores; P5CS mRNA aumenta em 2-6h após déficit hídrico em folhas de soja. APLICAÇÃO PRÁTICA: prolina exógena (1-5 mM foliar) = aumenta tolerância a seca, calor e salinidade em soja; aminoácidos hidrolisados contendo prolina = via indireta eficiente; mais eficiente aplicado em V5-R1 (pré-estresse). INTERAÇÃO: K (K melhora produção de prolina via P5CS); Mg (ativa P5CS como enzima ATPase-like); N (glutamato = precursor de N).',
 'Szabados, L. & Savoure, A. (2010). Proline: a multifunctional amino acid. Trends Plant Sci 15:89-97. / Verbruggen, N. & Hermans, C. (2008). Proline accumulation in plants: a review. Amino Acids 35:753-759.',
 '{prolina, P5CS, osmorregulação, estresse hídrico, calor, seca, ABA, ROS, scavenger, chaperonas químicas, aminoácido, K, Mg, N, glutamato, soja, bioestimulante, foliar}'),

('Glicina betaína: biossíntese, proteção de cloroplastos e aplicação foliar em soja',
 'artigo', 'all',
 'GLICINA BETAÍNA (GB): quaternário de amônio, compatível com enzimas em altas concentrações; derivado da oxidação de colina (Ch) via CMO (colina monooxigenase) + BADH (betaína aldeído desidrogenase). LOCALIZAÇÃO: estroma dos cloroplastos = principal sítio de acúmulo; GB é NATURALMENTE ABUNDANTE em espinafre, beterraba, trigo, cevada; em soja e milho = PEQUENA CAPACIDADE de síntese endógena = deficiência funcional em estresse severo. FUNÇÕES: (1) Proteção do estroma: estabiliza Rubisco e proteínas do estroma em dessecação (Rubisco é menos inativada em presença de GB 100 mM); (2) Proteção de tilacoides: estabiliza proteínas PSII em calor (GB mantém OEC funcional acima de 40°C por mais tempo); (3) Regulação da atividade de enzimas: GB em 0.5-2 M não inibe enzimas (diferente de NaCl ou sorbitol); (4) Osmorregulação: efetiva em ajustar potencial osmótico; (5) Proteção de membranas: GB interage com cabeças polares de fosfolipídios → estabiliza bicamada em congelamento e desidratação. APLICAÇÃO EXÓGENA: GB foliar em soja (R1-R3) = 5-10 mM = melhora pegamento de flores em calor + seca; mistura GB + PEG ou GB + K = efeito aditivo; formulações comerciais de extrato de algas contém GB + betaínas análogas. INTERAÇÃO MINERAL: N (colina é N-betaína, consome N); S (BADH enzima precisa de S para grupo -SH); Mg (estabiliza ribossomas que sintetizam BADH); Mn (PSII-OEC protegido pela GB). DIFERENÇA DE PROLINA: prolina = citoplasmática, proteção geral; GB = cloroplasto, proteção fotossintética específica.',
 'Chen, T.H.H. & Murata, N. (2011). Glycinebetaine protects plants against abiotic stress. Plant Cell Environ 34:1-20.',
 '{glicina betaína, GB, colina, CMO, BADH, Rubisco, cloroplasto, PSII, OEC, estresse térmico, seca, salinidade, extrato de algas, N, S, Mg, Mn, soja, foliar, R1, R2}'),

('Manejo do estresse oxidativo em soja: ROS, antioxidantes e momento de aplicação',
 'artigo', 'soja',
 'PROTOCOLO ANTIOXIDANTE EM SOJA (abordagem integrativa): DIAGNOSE DE ESTRESSE OXIDATIVO: sintomas visuais = clorose internerval (Fe-SOD ou Cu/Zn-SOD comprometida) + manchas bronzeadas + necroses em folhas velhas + murcha diurna + retardo de crescimento; CAUSA NUTRICIONAL: verificar Zn, Cu, Mn, Fe (cofatores de SOD, CAT, POD) + N, S, Mg (cofatores de enzimas de síntese de clorofila e proteínas antioxidantes). ESTÁDIOS CRÍTICOS DE ESTRESSE: V3-V4 (crescimento vegetativo rápido + maior produção de ROS por fotossíntese ativa); R1-R2 (florescimento + temperatura alta = maior produção de ¹O₂ em PSII); R4-R5 (enchimento + senescência acelerada = maior etileno + ROS). PROTOCOLO DE REDUÇÃO DE ESTRESSE OXIDATIVO: (1) Pré-florescimento V4-V5: Zn (300 g/ha) + Cu (150 g/ha) + Mn (400 g/ha) = ativa enzimas SOD; (2) Florescimento R1-R2: prolina (500 mL/ha aminoácidos) + GB (extrato de algas 1 L/ha) + Ca (1 kg/ha nitrato de Ca) + B (200 g/ha) = proteção do PSII + pegamento; (3) Enchimento R4-R5: K (1.5 kg/ha KNO₃) + N (ureia 0.5% = 2 kg/ha) + Mg (0.5 kg/ha) + fungicida (para manter área foliar saudável) = manutenção fotossintética. INTERAÇÃO ROS × DEFICIÊNCIAS: deficiência de Fe = APX comprometida → H₂O₂ acumula → foto-inibição do PSII; deficiência de Zn = SOD comprometida → O₂•⁻ não neutralizado → Fenton → HO• → oxidação de lipídios de membranas; TRATAMENTO URGENTE (seco/calor severo): GB + prolina + Ca foliar + Si foliar + K foliar = protocolo de emergência para proteger o florescimento em R1-R2 sob seca + calor extremo.',
 'Mittler, R. (2002). Oxidative stress, antioxidants and stress tolerance. Trends Plant Sci 7:405-410. / Embrapa Soja (2013). Tecnologias de produção.',
 '{estresse oxidativo, ROS, SOD, CAT, APX, POD, Zn, Cu, Mn, Fe, N, Mg, prolina, glicina betaína, Ca, B, K, Si, florescimento, soja, R1, R2, V4, V5, protocolo, emergência}'),

('Manejo fisiológico integrado em soja: cronograma de aplicações por estádio',
 'referencia', 'soja',
 'CRONOGRAMA DE MANIPULAÇÕES FISIOLÓGICAS EM SOJA: TRATAMENTO DE SEMENTES (TS): Bradyrhizobium (100 mL/50 kg) + Azospirillum (100 mL/50 kg, último) + Mo+Co (3-12 g Mo/50 kg) + EDDHA-Fe (se solo calcário) = base FBN e arranque; V1-V2 (30-40 DAP): Solo ou foliar de P (se deficiente) + Zn (300 g/ha foliar ou 3 kg/ha solo) + Mn (400 g/ha foliar) + Mo (30 g/ha foliar) = estabelecimento de raízes e FBN; OPTIONAL: auxinas exógenas (AIB 50 mg/L foliar) para enraizamento adicional. V3-V4 (40-50 DAP): N foliar (0.5% ureia se amarelecimento) + K (1 kg/ha KNO₃) + Mg (500 g/ha sulfato Mg) + B (150 g/ha ácido bórico) PREVENTIVO + Zn + Mn = nutrição vegetativa plena; bioestimulante: ácidos húmicos/fúlvicos (3-5 L/ha) + extrato algas (1 L/ha). V5-V6 (50-60 DAP): B (200 g/ha OBRIGATÓRIO) + Ca (1 kg/ha nitrato Ca) + K (1 kg/ha) + Zn (200 g/ha) = PRÉ-FLORESCIMENTO = sinalização para flores; aminoácidos (300 mL/ha) + extrato algas 1 L/ha; corrigir pH foliar da calda 5.5-6.5 para melhor absorção. R1 (florescimento início): B (200 g/ha) + Ca (1 kg/ha) + Zn (200 g/ha) + Mo (30 g/ha) = CRÍTICO para pegamento; GB foliar (extrato algas 1.5-2 L/ha) se calor/seca. R2-R3 (florescimento pleno-vagens): K (1.5 kg/ha) + Ca (1 kg/ha) + S (1 kg/ha tiosulfato) + N (aminoácidos 300 mL/ha) = formação de vagens; fungicida sistêmico na sequência. R4-R5 (enchimento): K (1.5-2 kg/ha) + N foliar + Mg (500 g/ha) + S (1 kg/ha) = enchimento de proteína e óleo; manter folhas saudáveis com fungicida.',
 'Sfredo, G.J. (2008). Soja no Brasil: Calagem e Adubação. Embrapa Soja. / Hungria et al. (2013). Co-inoculação. Embrapa.',
 '{cronograma, aplicação foliar, soja, V1, V2, V3, V4, V5, V6, R1, R2, R3, R4, R5, B, Ca, Zn, K, N, Mo, Co, Mg, S, FBN, florescimento, enchimento, tratamento de sementes, bioestimulante}');
