-- ─── NOVAIS / EMBRAPA — NUTRIÇÃO DE MILHO E FEIJÃO: tabelas e critérios ──────
-- Diagnose, adubação e fisiologia específica para milho e feijão
-- ─────────────────────────────────────────────────────────────────────────────

insert into public.conhecimento (titulo, tipo, cultura, conteudo, fonte, tags) values

('Embrapa Milho — Nutrição e adubação do milho: macronutrientes e micronutrientes',
 'referencia', 'milho',
 'EXTRAÇÃO E EXPORTAÇÃO DE NUTRIENTES (milho grão, 8 t/ha): N=144 kg/ha extraído (exporta 128 kg), P₂O₅=65 kg (exporta 55 kg), K₂O=180 kg (exporta 48 kg), Ca=32 kg, Mg=22 kg, S=16 kg, Zn=280 g, Mn=200 g, Fe=600 g, Cu=70 g, B=100 g. DIAGNOSE FOLIAR (folha bandeira em V6-VT, limbo da folha média): N=27-35 g/kg; P=2-4 g/kg; K=15-25 g/kg; Ca=3-8 g/kg; Mg=2-6 g/kg; S=2-3.5 g/kg; B=15-40 mg/kg; Zn=15-60 mg/kg; Cu=4-12 mg/kg; Mn=15-150 mg/kg; Fe=50-300 mg/kg; Mo=0.1-1.0 mg/kg. ESTÁDIOS CRÍTICOS MILHO: N (V4-R1 = panícula); P (germinação-V4); K (VT-R2); Ca, B (VT-R1 = polinização = CRÍTICO). ADUBAÇÃO BASE: NPK no sulco = 300-600 kg/ha (formulação 05-20-20 ou 10-15-20 dependendo do solo); topdressing N = 40-60 kg N/ha em cobertura em V4-V6 (ureia 45% ou sulfato de amônio 21% N); parcelamento = maior eficiência do N. ZINCO EM MILHO: Zn é o micronutriente mais limitante no milho em solos do cerrado; "mancha branca" ou "stripe" do milho = Zn deficiência em V2-V4; diagnose = < 15 mg Zn/kg na folha; correção foliar = 300 g ZnSO₄/ha em V2-V4. NITROGÊNIO E MILHO: N é o nutriente mais limitante para o rendimento; resposta esperada ao N = +5-15 sc/ha por 30 kg N/ha adicionais até máximo de 150-200 kg N/ha; fonte N influencia: ureia (volatilização de NH₃ em solo aquecido = perda de 20-40%); ureia+NBPT (inibidor de urease) = reduz perda 50%; sulfato de amônio = mais eficiente em pH alto, mas acidifica o solo (-0.2 pH/100 kg).',
 'Embrapa Milho e Sorgo (2010). Tecnologias de Produção de Milho. Embrapa. / Novais, R.F. et al. (2007). Fertilidade do Solo. SBCS.',
 '{milho, N, P, K, Ca, Mg, S, Zn, Mn, Fe, Cu, B, Mo, diagnose foliar, adubação, topdressing, ureia, NBPT, sulfato de amônio, mancha branca, cerrado, V4, V6, VT, R1}'),

('Embrapa Feijão — Nutrição e adubação do feijoeiro: nutrientes críticos e déficits comuns',
 'referencia', 'feijao',
 'FEIJOEIRO COMUM (Phaseolus vulgaris): ciclo curto (65-110 dias) = alta demanda nutricional por unidade de tempo. EXTRAÇÃO DE NUTRIENTES (2.5 t grãos/ha): N=130 kg (exporta 85 kg), P₂O₅=55 kg (exporta 48 kg), K₂O=120 kg (exporta 80 kg), Ca=30 kg, Mg=15 kg, S=12 kg, Zn=210 g, B=80 g. FBN NO FEIJÃO: MENOS eficiente que soja (< 40 kg N/ha fixado na maioria das condições vs 100+ na soja); inoculação com Rhizobium tropici SEMIA 4080 + SEMIA 4088 = padrão MAPA para feijão; FBN no feijão = fortemente limitada por pH < 6.0, Al alto, P baixo, Mo baixo. ADUBAÇÃO DE PLANTIO: 250-400 kg/ha NPK (04-20-20 ou 05-25-15 dependendo análise solo); NITROGÊNIO: 0-30 kg N no plantio (inoculado = mínimo; sem inoculação = 30-60 kg N); cobertura = 20-40 kg N em V3-V4 (pré-florescimento); excesso de N antes do florescimento = crescimento vegetativo excessivo e aborto floral. ESTÁDIOS CRÍTICOS FEIJÃO: V4-R1 (pré-florescimento = estádio de manipulação = B+Ca+Zn para evitar aborto floral); R7-R8 (enchimento de grãos = K máxima demanda). DIAGNOSE FOLIAR (3ª folha trifoliolada em V4): N=40-55 g/kg; P=3-5.5 g/kg; K=18-28 g/kg; Ca=8-20 g/kg; Mg=3-8 g/kg; S=2.5-4 g/kg; B=25-70 mg/kg; Zn=20-60 mg/kg; Cu=5-15 mg/kg; Mn=40-200 mg/kg; Fe=70-400 mg/kg; Mo=0.5-5 mg/kg. CARÊNCIAS MAIS COMUNS EM FEIJÃO: Zn (solos ácidos com P alto), Mn (toxicidade em pH < 5.5), Mo (FBN comprometida em pH ácido), B (antes do florescimento = aborto), N (plantas pálidas se FBN falhou).',
 'Embrapa Arroz e Feijão (2012). Cultivo do Feijoeiro Comum. Embrapa / Novais, R.F. et al. (2007). Fertilidade do Solo. SBCS.',
 '{feijão, feijoeiro, N, P, K, Ca, Mg, S, Zn, B, Mo, Mn, Fe, Rhizobium, FBN, diagnose foliar, adubação, V4, R1, R7, florescimento, aborto floral, inoculação, SEMIA 4080}'),

('Antagonismos e sinergismos nutricionais em soja: tabela de relações práticas',
 'referencia', 'soja',
 'TABELA DE ANTAGONISMOS NUTRICIONAIS EM SOJA (impacto agronômico): K↓Mg: K alto (K/CTC > 5%) → Mg abaixo de 0.6 cmolc/dm³ = clorose internerval velhas + folhas velhas com amarelamento internerval; correção = calcário dolomítico + Mg foliar. Ca↓Mn: calagem elevada (pH > 6.5) → Mn precipita → Mn < 0.3 mg/dm³ solo = deficiência de Mn mesmo sem histórico; correção = Mn foliar 400 g/ha. P↓Zn: P alto (> 40 mg/dm³) + pH 5.5-6.5 → Zn-fosfato insolúvel; Zn foliar < 21 mg/kg = deficiência induzida por P; correção = Zn foliar 300-500 g/ha. S↓Mo: SO₄²⁻ alto + SO₄ do gesso = compete com MoO₄²⁻; Mo < 0.5 mg/kg foliar = FBN comprometida; correção = Mo foliar 30 g/ha separado do gesso. Ca↑B: B adequado = melhora distribuição de Ca; sem B = Ca mal distribuído mesmo com Ca no solo (B-pectina-Ca complexo). Mn↑Fe (antagonismo): pH ácido (< 5.5) = ambos em excesso simultâneo = toxicidade de Mn + Fe; pH 5.5-6.0 = ambos adequados. pH↓Mo (ÚNICO POSITIVO): solo ácido = Mo indisponível; calagem = corrige Mo naturalmente; em pH 6.5 = Mo adequado mesmo sem adubação. TABELA DE SINERGISMOS: N×S (N:S ideal = 17:1 em g/g; sem S = proteínas incompletas, FBN comprometida). P×Mo (P apoia síntese de ATP para nitrogenase que usa Mo). B×Ca (B mobiliza Ca e estrutura Ca-pectina da parede celular). Zn×IAA (Zn → síntese de IAA → mais raízes → maior absorção de outros nutrientes). Mo×FBN (Mo é cofator da nitrogenase = OBRIGATÓRIO para FBN eficiente).',
 'Malavolta, E. et al. (1997). Avaliação do Estado Nutricional das Plantas. Potafos. / Marschner, H. (2012). Mineral Nutrition. Academic Press.',
 '{antagonismo, sinergismo, K, Mg, Ca, Mn, P, Zn, S, Mo, B, N, Fe, soja, FBN, relações nutricionais, tabela, diagnose, pH, calagem}');
