-- ─── PIONEER/DUPONT — CORN GROWTH AND DEVELOPMENT GUIDE (2015) ──────────────
-- Estádios fenológicos do milho: vegetativos e reprodutivos
-- Fonte: DuPont Pioneer. Corn Growth and Development. Johnston, IA, 2015.
-- ─────────────────────────────────────────────────────────────────────────────

insert into public.conhecimento (titulo, tipo, cultura, conteudo, fonte, tags, ativo) values

('Pioneer — Milho: sistema de estádios fenológicos e Graus-Dia de Crescimento (GDDs)',
 'referencia', 'milho',
 'SISTEMA DE ESTÁDIOS DO MILHO (Iowa State University / Pioneer): estádios VEGETATIVOS (V) identificados pela presença de colar foliar visível — blade (lâmina) + sheath (bainha) + collar (colar, dobra entre lâmina e bainha). Quando o colar é visível, a folha é contada. Sequência: VE (emergência) → V1 → V2 → ... → V(n) → VT (pendoamento). Estádios REPRODUTIVOS (R) = R1 (pendão + estigma = Silking) → R2 (Blister) → R3 (Milk) → R4 (Dough) → R5 (Dent) → R6 (Mature). GRAUS-DIA DE CRESCIMENTO (GDDs): GDD = (Tmin + Tmax)/2 − 50°F; mínimo = 50°F (10°C); máximo = 86°F (30°C). Referências: emergência requer 90-120 GDDs após plantio; entre VE e V14 = 66-84 GDDs por folha com colar; entre V15 e VT = 48-56 GDDs por folha; silking (R1) ocorre ~1.400 GDDs após VE; maturidade (R6) ocorre ~2.800 GDDs após VE. Híbridos de maturidade relativa (RM) 75 = silking ~900 GDDs; RM 115 = ~1.300 GDDs; RM 135 = silking tardio. Híbridos do Corn Belt dos EUA desenvolvem 20-21 folhas; híbridos precoces = 11-12 folhas; híbridos tropicais = 30+ folhas.',
 'DuPont Pioneer (2015). Corn Growth and Development. Pioneer, Johnston, IA.',
 '{milho, estádios fenológicos, GDDs, graus-dia, VE, V1, VT, R1, R2, R3, R4, R5, R6, leaf collar, Iowa State, maturidade relativa, pendoamento, silking}'),

('Pioneer — Milho: germinação e emergência (VE)',
 'referencia', 'milho',
 'GERMINAÇÃO E EMERGÊNCIA (VE): semente de milho imbibi ~30-35% do peso em água; temperatura mínima do solo para radicela elongar = 50°F (10°C); solo frio = emergência lenta e desuniforme. Radicela emerge primeiro, seguida de 3-4 raízes seminais = sistema radicular seminal (absorção de água e nutrientes nos primeiros estádios). Maioria dos nutrientes para a plântula = amido e proteínas hidrolisados do endosperma. Emergência (VE) = coleóptilo rompe a superfície do solo. Luz inibe elongação do mesocótilo (primeiro internó entre cotilédone e 1º nó), fixando a coroa e 1ª raiz nodal a ~0,75 polegadas (2 cm) abaixo da superfície. Raízes nodais permanentes iniciam em VE. Raiz seminal cessa ~V3; raiz nodal (permanente) passa a dominar. PROFUNDIDADE DE PLANTIO: profundidade rasa (< 1,5 pol = 3,8 cm) prejudica desenvolvimento da coroa e raízes nodais; ideal = 1,5-2 polegadas (3,8-5 cm). Após emergência, folha cotiledonar desenvolve, seguida da 1ª folha verdadeira (ponta arredondada = V1); demais folhas têm ponta pontiaguda.',
 'DuPont Pioneer (2015). Corn Growth and Development / Ritchie, S.W. et al. (1996). How a Corn Plant Develops. Iowa State Univ. Extension Special Report No. 48.',
 '{milho, germinação, emergência, VE, coleóptilo, raiz seminal, raiz nodal, mesocótilo, coroa, GDDs, temperatura solo, profundidade de plantio}'),

('Pioneer — Milho: estádios vegetativos V1 a V5 (crescimento inicial)',
 'referencia', 'milho',
 'ESTÁDIOS V1 A V5 (early vegetative): mínima elongação de internós (dependente da temperatura do solo). ATÉ V5, o ponto de crescimento (growing point) está ABAIXO da superfície do solo = protegido de injúrias mecânicas e geadas. Todas as folhas e espigas potenciais são iniciadas neste período. Primórdios foliares = iniciados em cada nó (axila de cada folha) do 1º ao ~13º nó (acima do solo). Brotos acima do solo → tecido reprodutivo (espiga/sabugo); brotos abaixo do solo → tecido vegetativo (afilhos/suckers). RAÍZES: raízes permanentes em 5 nós abaixo do solo + 1 no nível do solo + possivelmente 1+ acima (raízes escora/brace roots = suporte mecânico e absorção se penetrarem o solo). NUTRIÇÃO CRÍTICA V1-V5: P (energia ATP para divisão celular = essencial); Zn (micronutriente mais limitante no cerrado para milho em V2-V4 = "mancha branca"); N (início de demanda para fotossíntese); temperatura do solo < 10°C bloqueia absorção de P = sintoma de deficiência mesmo com P adequado no solo.',
 'DuPont Pioneer (2015). Corn Growth and Development.',
 '{milho, V1, V2, V3, V4, V5, growing point, ponto de crescimento, raiz nodal, raiz escora, P, Zn, N, mancha branca, temperatura solo, afilho}'),

('Pioneer — Milho: estádios V6 a V11 e V12-VT (vegetativo médio e tardio)',
 'referencia', 'milho',
 'ESTÁDIOS V6 A V11 (mid-vegetative): PONTO DE CRESCIMENTO sobe acima do solo em ~V6 = planta agora susceptível a danos mecânicos, granizo e geada. Elongação rápida de internós. Folhas inferiores (1-4) podem desprender e decompor = para identificar estádio, cavar a planta e separar o caule: 1º internó visível está entre nós 4 e 5 (≈ 0,6 cm); contar colares acima do 5º nó para determinar V. Alternativa: nó ao nível do solo = geralmente nó 6. NÚMERO DE FILEIRAS DE GRÃOS definido em ~V7 = sempre número par (divisão celular); média = 14-16-18 fileiras; determinado pela genética do híbrido; estresses severos neste período podem reduzir fileiras. DESENVOLVIMENTO DA ESPIGA: primórdio da espiga primária visível em V9; primórdios florais em V12. ESTÁDIOS V12 A VT (late-vegetative): COMPRIMENTO DA ESPIGA (nº de grãos por fileira) determinado nas últimas semanas antes do pendoamento. Estresse neste período reduz grãos por fileira, mas número definitivo é fixado durante e após a polinização. NUTRIÇÃO CRÍTICA V6-VT: N (máxima absorção de N ocorre em V6-R1 = >50% do total do ciclo); K (K é essencial para elongação de internós e qualidade do colmo); B e Ca (florescimento se aproxima = B e Ca críticos para espiga e polinização).',
 'DuPont Pioneer (2015). Corn Growth and Development / Abendroth et al. (2011). Corn growth and development. PMR 1009. Iowa State Univ.',
 '{milho, V6, V7, V8, V9, V10, V11, V12, VT, ponto de crescimento, fileiras de grãos, elongação, espiga, polinização, N, K, B, Ca, pendoamento, crescimento rápido}'),

('Pioneer — Milho: transição VT-R1 e polinização (silking)',
 'referencia', 'milho',
 'TRANSIÇÃO VT → R1 (PERÍODO MAIS CRÍTICO PARA RENDIMENTO): VT = último ramo do pendão emergido e estendido; pico de liberação de pólen = metade da manhã; vida do grão de pólen = ~20 minutos após liberação; maioria do pólen cai a 6-15 m da planta; ~97% dos grãos produzidos são fertilizados por pólen de outra planta. PENDÃO (flor masculina): produz >1.000.000 grãos de pólen por planta. ESPIGA (flor feminina): produz >1.000 estigmas (silk = estigma + estilete). Relação = 1.000-1.500 grãos de pólen por estigma. NICK: coincidência entre liberação de pólen (VT) e emergência dos estigmas (R1) = essencial para polinização eficiente; híbridos modernos: estigmas emergem 1-2 dias antes do pleno pendão = melhoria evolutiva. Estigmas emergem ao longo de 3-5 dias, começando pela base da espiga → ponta. FERTILIZAÇÃO: grão de pólen pousa no estigma → tubo polínico forma em 24 horas → desce o estigma → fertiliza o óvulo → abscisão do estigma → estigma seca e escurece. Estigma sem fertilização em 7 dias → óvulo morre → posição vaga na espiga (grain gaps). ESTRESSE EM R1: temperatura >35°C inibe germinação do grão de pólen; seca severa = desidratação dos estigmas = falha de polinização; 2 semanas após R1 = período mais sensível para aborto de grãos.',
 'DuPont Pioneer (2015). Corn Growth and Development.',
 '{milho, VT, R1, polinização, pendão, estigma, silk, tubo polínico, nick, aborto de grãos, temperatura, seca, fertilização, espiga, grão de pólen}'),

('Pioneer — Milho: estádios reprodutivos R2 a R6 (formação e enchimento de grãos)',
 'referencia', 'milho',
 'ESTÁDIOS REPRODUTIVOS DO MILHO: R2 (BLISTER = 10-14 dias após R1): grãos com 85% de umidade, aspecto de bolha, endosperma claro. Comprimento máximo da espiga atingido. Aborto de grãos possível (grãos da ponta abortam primeiro). R3 (MILK = 18-22 dias após R1): grãos com 80% umidade, fluido leitoso branco por acúmulo de amido. Cor final do grão visível (amarelo, branco). Embrião distinguível do endosperma. Aborto ainda possível. R4 (DOUGH = 24-28 dias após R1): grãos com 70% umidade, consistência pastosa. ~50% do peso seco final acumulado. Cor do sabugo começa a definir-se (branco, rosa, vermelho escuro = genética do híbrido). Folhas externas da palha começam a escurecer. Estresse reduz taxa de acúmulo de amido (menor peso de grão), mas não aborto. R5 (DENT = 35-42 dias após R1): camada de amido duro externa + núcleo mole interno; quando núcleo perde umidade = "dent" (dentado). MILK LINE = interface amido duro/mole; avança da coroa para a base do grão (3-4 semanas); R5 inicial = 55% umidade + 45% MS final; R5.5 (½ milk line) = 90% da MS final. Estresse reduz acúmulo de amido e peso final. R6 (MATURIDADE FISIOLÓGICA = 60-65 dias após R1): 35% umidade; peso seco máximo atingido; milk line chega à base; camada negra (black layer) forma na ponta do grão → impede entrada/saída de amido e umidade. Black layer forma-se de ponta para base da espiga. Espiga típica = 500-800 grãos; peso médio do grão = 350 mg (15.5% umidade); bushel padrão = 25,5 kg = ~90.000 grãos.',
 'DuPont Pioneer (2015). Corn Growth and Development / Mahanna et al. (2014). Silage Zone Manual. DuPont Pioneer.',
 '{milho, R2, R3, R4, R5, R6, blister, milk, dough, dent, maturidade fisiológica, black layer, milk line, enchimento de grãos, umidade, amido, endosperma, peso de grão, espiga}'),

('Pioneer — Milho: planta de milho e morfologia (monoécica, pendão, espiga)',
 'referencia', 'milho',
 'MORFOLOGIA DO MILHO (Zea mays L.): planta MONOÉCICA = flores masculinas e femininas na mesma planta, separadas verticalmente ~1 metro. PENDÃO (flor masculina, tassel): produz grãos de pólen; liberação = 5-8 dias descontinuamente; pico = meio da manhã; pólen viable por ~20 min; alcance predominante = 6-15 m. ESPIGA (flor feminina, ear): ovários que se tornam grãos; estigma (silk) = canal para fertilização. ESTRUTURA DO GRÃO: pericarpo (tegumento, 5-6% do peso); endosperma/amido (83% do peso = camada externa de amido duro + núcleo mole); embrião/gérmen (11% = plântula embrionária + escutelo). SEMENTE: coleóptilo (bainha protetora do broto emergente); mesocótilo (1º internó entre cotilédone e 1º nó); radícula (raiz primária); coleorriza (bainha da radícula). ORIGEM: Zea mays derivado de teosinte (Zea mays ssp. mexicana/parviglumis) por domesticação há ~9.000 anos; apenas ~5 mutações genéticas principais separam teosinte do milho moderno. HÍBRIDOS: cruzamento de linhagens endogâmicas (inbreds) puras → heterose (vigor híbrido); single-cross dominante desde 1950; heterose = base do melhoramento moderno de milho.',
 'DuPont Pioneer (2015). Corn Growth and Development. / Galinat, W.C. (1988). The Origin of Corn. ASA Monograph no. 18.',
 '{milho, morfologia, monoécica, pendão, espiga, estigma, silk, grão, endosperma, embrião, coleóptilo, teosinte, híbrido, heterose, inbred, single-cross, pericarpo}');
