-- ─── EMBRAPA ALGODÃO — ADUBAÇÃO DO ALGODOEIRO NO CERRADO (Comunicado Técnico 375) ─────
-- Borin, A.L.D.C.; Ferreira, G.B.; Carvalho, M.C.S. — Embrapa Algodão, 2014
-- ──────────────────────────────────────────────────────────────────────────────────────

insert into public.conhecimento (titulo, tipo, cultura, conteudo, fonte, tags) values

('Embrapa Algodão — Extração e exportação de macronutrientes pelo algodoeiro no Cerrado',
 'referencia', 'algodao',
 'EXTRAÇÃO DE MACRONUTRIENTES (por 1.000 kg algodão em caroço): N=70 kg, P₂O₅=26 kg, K₂O=73 kg, Ca=26 kg, Mg=16 kg, S=6 kg. SIMULAÇÃO PARA 4.500 kg/ha (300@): N=315 kg, P₂O₅=117 kg, K₂O=329 kg, Ca=117 kg, Mg=72 kg, S=26 kg. EXPORTAÇÃO (somente caroço, fibra possui quantidades desprezíveis): N=34 kg/t (153 kg/300@), P₂O₅=12 kg/t (54 kg/300@), K₂O=22 kg/t (99 kg/300@), Ca=3 kg/t (13 kg/300@), Mg=8 kg/t (38 kg/300@), S=3 kg/t (15 kg/300@). EFICIÊNCIA NO USO DE FERTILIZANTES: algodão é uma das culturas de MENOR eficiência: N=44%, K=58%, P=apenas 16%; o restante retorna ao solo — alta importância para rotação de culturas (cultura sucessora se beneficia dos resíduos). IMPLICAÇÃO PRÁTICA: K e N são os macronutrientes mais absorvidos; P tem a menor eficiência de uso → alto potencial de acúmulo no solo após adubações repetidas.',
 'Borin, A.L.D.C.; Ferreira, G.B.; Carvalho, M.C.S. (2014). Adubação do Algodoeiro no Ambiente de Cerrado. Embrapa Algodão, Comunicado Técnico 375.',
 '{algodão, algodoeiro, extração de nutrientes, exportação, N, P, K, Ca, Mg, S, eficiência fertilizante, caroço, fibra, Cerrado, rotação de culturas}'),

('Embrapa Algodão — Calagem e gessagem para algodoeiro no Cerrado',
 'referencia', 'algodao',
 'CALAGEM: pH ideal em água = próximo a 6,0; pH < 5,5 = redução de produtividade; V% adequado = 60%. Método recomendado = SATURAÇÃO POR BASES: NC (t/ha) = T × (Ve − Va) / 100; onde T = CTC a pH 7,0 (SB + H+Al), Ve = 60% (saturação desejada), Va = saturação atual. Corrigir pelo PRNT: QC = NC × 100/PRNT. Calcário DOLOMÍTICO recomendado quando Mg < 1 cmolc/dm³ ou saturação Mg na CTC < 13%. Deficiência de Mg = clorose internerval nas folhas do baixeiro; em algumas cultivares = avermelhamento internerval. Aplicação: 2-3 meses antes da semeadura, com incorporação até 20 cm. GESSAGEM: aplicar quando na camada 20-40 cm ou 40-60 cm: Ca < 0,5 cmolc/dm³ OU Al > 0,5 cmolc/dm³ OU saturação por Al (m) > 30%. Dose máxima = 50 × (% argila) kg/ha (efeito residual mínimo 3 anos). Exemplos: 15% argila = máx 750 kg/ha; 50% argila = máx 2.500 kg/ha. Benefício do gesso = fornece Ca e S no perfil, reduz toxicidade de Al, favorece crescimento radicular em profundidade = maior tolerância a veranicos.',
 'Borin, A.L.D.C.; Ferreira, G.B.; Carvalho, M.C.S. (2014). Adubação do Algodoeiro no Ambiente de Cerrado. Embrapa Algodão, Comunicado Técnico 375.',
 '{algodão, calagem, gessagem, pH, saturação por bases, V%, CTC, PRNT, Mg deficiência, Al toxicidade, Ca, Cerrado, profundidade, veranico}'),

('Embrapa Algodão — Fosfatagem corretiva e adubação fosfatada de manutenção',
 'referencia', 'algodao',
 'FOSFATAGEM CORRETIVA (quando P muito baixo, baixo ou médio no solo): dose corretiva varia com teor de argila e disponibilidade de P (Mehlich-1): argila ≤15% + P muito baixo = 60 kg/ha P₂O₅; argila 15-35% + P muito baixo = 100 kg/ha; argila 36-60% + P muito baixo = 200 kg/ha; argila >60% + P muito baixo = 280 kg/ha. Efeito residual mínimo = 3 anos. Correção pode ser única (área total + incorporação 0-20 cm) ou gradual (parcelada em até 5 anos). INTERPRETAÇÃO DE P NO SOLO (Mehlich-1) PARA ADEQUADO: argila <16% = 18,1-25 mg/dm³; argila 16-35% = 15,1-20 mg/dm³; argila 36-60% = 8,1-12 mg/dm³; argila >60% = 4,1-6 mg/dm³. ADUBAÇÃO DE MANUTENÇÃO (P): produtividade até 3.000 kg/ha: P adequado = 60 kg/ha, P alto = 30 kg/ha; 4.000 kg/ha: 90 e 45 kg/ha; 5.000 kg/ha: 110 e 55 kg/ha; 6.000 kg/ha: 135 e 70 kg/ha. MODO DE APLICAÇÃO: P < adequado = sulco mais eficiente; P ≥ adequado = sulco ou lanço (sem diferença de produtividade), mas recomenda-se mínimo 30-40 kg P₂O₅/ha no sulco para uniformizar desenvolvimento inicial.',
 'Borin, A.L.D.C.; Ferreira, G.B.; Carvalho, M.C.S. (2014). Adubação do Algodoeiro no Ambiente de Cerrado. Embrapa Algodão, Comunicado Técnico 375.',
 '{algodão, fósforo, P, fosfatagem corretiva, adubação manutenção, Mehlich-1, argila, sulco, lanço, Cerrado, fase correção, fase manutenção}'),

('Embrapa Algodão — Adubação nitrogenada e potássica do algodoeiro no Cerrado',
 'referencia', 'algodao',
 'NITROGÊNIO — DOSES DE MANUTENÇÃO (função da produtividade esperada em algodão em caroço): até 3.000 kg/ha = 15-20 kg N semeadura + 60-80 kg N cobertura; 4.000 kg/ha = 15-20 + 80-100; 5.000 kg/ha = 15-20 + 100-120; 6.000 kg/ha = 15-20 + 120-140 kg/ha. Semeadura pode chegar a 40 kg N/ha em áreas com muita palhada de gramínea ou com percevejo-castanho. Dose MAIOR de N quando: cultura anterior = gramínea, baixo teor MO, início do plantio direto. Dose MENOR quando: leguminosa anterior, alto teor MO, plantio direto estabilizado. ADUBAÇÃO DE COBERTURA: 1ª safra = parcelar em 2 aplicações, 2ª não ultrapassar estádio F1 (1ª flor aberta); 2ª safra tardia (final jan/início fev) = sem parcelamento + 20% menos N. Para minimizar perdas por volatilização = garantir umidade no solo. POTÁSSIO — INTERPRETAÇÃO K MEHLICH-1 ADEQUADO: CTC < 4,0 cmolc/dm³ = K 31-40 mg/dm³; CTC > 4,0 = K 51-80 mg/dm³. DOSES K₂O (kg/ha) por faixa de K no solo (0-20 cm): produtividade 6.000 kg/ha: K <25 = 190-210, K 26-50 = 160-180, K 51-80 = 140-160, K 81-120 = 120, K >120 = 60. LIMITE NO SULCO: nunca aplicar mais de 60 kg K₂O/ha no sulco. K < adequado = até 60 kg/ha no sulco + restante lanço. K ≥ adequado = todo K a lanço (pré-semeadura até 30 dias após emergência).',
 'Borin, A.L.D.C.; Ferreira, G.B.; Carvalho, M.C.S. (2014). Adubação do Algodoeiro no Ambiente de Cerrado. Embrapa Algodão, Comunicado Técnico 375.',
 '{algodão, N, K, nitrogênio, potássio, adubação cobertura, topdressing, safra, segunda safra, F1, sulco, lanço, Cerrado, CTC, Mehlich-1, volatilização}'),

('Embrapa Algodão — Micronutrientes e diagnose foliar do algodoeiro',
 'referencia', 'algodao',
 'MICRONUTRIENTES DO ALGODOEIRO: BORO: dose recomendada = 1-3 kg B/ha; modo = parte no sulco (0,5-1,0 kg/ha) + cobertura e/ou foliar; foliar = mínimo 3 aplicações a partir do florescimento, intervalo de 15 dias; maiores doses = alta produtividade + solo com baixo teor MO + textura arenosa. Sintoma de deficiência de B = anéis concêntricos verde-escuros no pecíolo. ZINCO: se Zn solo < 1,6 mg/dm³ = 2 kg Zn/ha por safra a lanço, ou 6 kg/ha a cada 3 anos. Cu, Fe, Cl e Mo: sem registros de resposta do algodoeiro à adubação no Brasil. pH > 6,4 = Mn pode tornar-se deficiente → aplicação foliar de Mn necessária. Plantio direto com calcário superficial = pode induzir deficiências temporárias de micronutrientes → adubação foliar. DIAGNOSE FOLIAR: coleta da 4ª ou 5ª folha (com pecíolo) a partir do ápice do caule principal, durante o MÁXIMO FLORESCIMENTO; coletar 25 folhas de 25 plantas diferentes por área homogênea. TEORES FOLIARES ADEQUADOS (lavouras alta produtividade no Cerrado): N=40-45 g/kg; P=3-4 g/kg; K=20-25 g/kg; Ca=25-35 g/kg; Mg=4-8 g/kg; S=4-6 g/kg; B=40-80 mg/kg; Cu=8-15 mg/kg; Fe=70-250 mg/kg; Mn=35-80 mg/kg; Mo=1-3 mg/kg; Zn=30-65 mg/kg. DIAGNOSE VISUAL: critérios = simetria (bilateral), gradiente (de cima para baixo = imóvel; de baixo para cima = móvel) e generalização (não isolado).',
 'Borin, A.L.D.C.; Ferreira, G.B.; Carvalho, M.C.S. (2014). Adubação do Algodoeiro no Ambiente de Cerrado. Embrapa Algodão, Comunicado Técnico 375. / Yamada et al. (1999). Potafos. / Malavolta (2002).',
 '{algodão, B, Zn, Mn, micronutrientes, diagnose foliar, análise foliar, florescimento, teores foliares, boro, zinco, diagnose visual, simetria, gradiente, Cerrado, pH}');
