-- ─── BIOFERTILIZANTES — PGPR, AZOSPIRILLUM E BACTÉRIAS DIAZOTRÓFICAS ────────
-- Inoculantes e promotores de crescimento para soja, milho e feijão
-- Fontes: Embrapa Soja/SNT; Hungria et al.; Döbereiner; Figueiredo et al.
-- ─────────────────────────────────────────────────────────────────────────────

insert into public.conhecimento (titulo, tipo, cultura, conteudo, fonte, tags) values

('Biofertilizantes — PGPR: mecanismos de promoção de crescimento vegetal',
 'artigo', 'all',
 'PGPR (Plant Growth Promoting Rhizobacteria): microrganismos da rizosfera que promovem crescimento por mecanismos DIRETOS e INDIRETOS. MECANISMOS DIRETOS: (1) FIXAÇÃO BIOLÓGICA DE N₂: Bradyrhizobium (soja), Rhizobium (feijão), Azospirillum (cereais, capins), Herbaspirillum (cana, arroz), Gluconacetobacter (cana); (2) SOLUBILIZAÇÃO DE P INORGÂNICO: Bacillus megaterium, Pseudomonas fluorescens, Aspergillus niger — produzem ácidos orgânicos (glucônico, cítrico, láctico) que acidificam o rizosfera e liberam P-insolúvel do solo; solubilização de Ca₃(PO₄)₂, AlPO₄, FePO₄; (3) MINERALIZAÇÃO DE P ORGÂNICO: fosfatases extracelulares (ácidas e alcalinas) que hidrolisam ésteres fosfatos do húmus → P disponível; (4) PRODUÇÃO DE FITOHORMÔNIOS: IAA (triptofano dependente), CKs, GAs e etileno por Azospirillum brasilense, Bacillus sp., Pseudomonas putida; IAA bacteriano estimula formação de raízes laterais e pelos radiculares → maior área de absorção. MECANISMOS INDIRETOS: (1) SIDEROFOROS: quelantes de Fe³⁺ de alta afinidade (pioverdin, enterobastin, bacillibactin) → mobiliza Fe do solo → competição com patógenos por Fe; (2) ANTIBIOTICOS: inibição de Fusarium, Pythium, Rhizoctonia por Pseudomonas e Bacillus; (3) INDUÇÃO DE RESISTÊNCIA SISTÊMICA (ISR): estimula SA e JA-dependentes em resposta a patógenos; (4) VOLATEIS: 2,3-butanodiol e acetoína de Bacillus subtilis GB03 estimulam crescimento de Arabidopsis; (5) ENZIMAS DEGRADATIVAS: ACC deaminase (Pseudomonas, Rhizobium) → degrada ACC precursor de etileno → reduz etileno em estresse → proteção radicular.',
 'Hungria, M. et al. (2010). Inoculation with selected strains of Azospirillum brasilense and A. lipoferum improves yields of maize and wheat in Brazil. Plant and Soil, 331, 413-425. / Figueiredo, M.V.B. et al. (2010). Plant growth promoting rhizobacteria: Fundamentals and applications. In: Maheshwari DK (ed) Plant Growth and Health Promoting Bacteria. Springer.',
 '{PGPR, rizobactérias, promoção de crescimento, solubilização de P, IAA, sideróforos, ACC deaminase, Azospirillum, Bacillus, Pseudomonas, ISR, resistência sistêmica}'),

('Biofertilizantes — Azospirillum brasilense: mecanismos, doses e resposta em soja, milho e trigo',
 'artigo', 'all',
 'AZOSPIRILLUM: gênero de α-proteobactérias diazotróficas (fixação associativa de N₂); espécies principais = A. brasilense (estirpes Sp7, Sp245, Ab-V5, Ab-V6, UFSM — padrão MAPA no Brasil) e A. lipoferum. MECANISMOS DE PROMOÇÃO: (1) FIXAÇÃO DE N₂ ASSOCIATIVA: contribuição de 10-30 kg N/ha em gramíneas (muito inferior ao Bradyrhizobium/soja), mas bioquimicamente confirmada por marcação isotópica ¹⁵N; (2) PRODUÇÃO DE IAA: via IpyA (piruvato de indol) e IAAid (indolacetamida); em condições ricas de triptofano exsuda > 0.18 μmol IAA/mL; efeito dominante sobre raízes (> número de raízes laterais, comprimento de pelos, >área radicular até 35% em trigo); (3) NITRATO REDUTASE: reduz NO₃⁻ → NO₂⁻ → NO → estimula divisão celular via sinalização de NO (óxido nítrico); (4) PRODUÇÃO DE GIBERELINAS E CITOCININAS: detectadas em meios de cultura; (5) FORMAÇÃO DE BIOFILME: proteção física e biológica da raiz. RESULTADOS EXPERIMENTAIS: META-ANÁLISE (Hungria et al., 2010, 22 ensaios): milho inoculado = +30% rendimento; trigo = +18%; soja = variável mas positivo quando co-inoculado com Bradyrhizobium. RECOMENDAÇÃO PRÁTICA PARA SOJA: co-inoculação Bradyrhizobium + Azospirillum brasilense (estirpes Ab-V5+Ab-V6) = RECOMENDAÇÃO OFICIAL EMBRAPA → maior FBN e crescimento radicular; dose = 100 mL inoculante/50 kg semente (líquido) ou 150-200 g/50 kg (turfoso); compatibilidade com fungicida de tratamento: aplicar inoculante SEPARADO do fungicida (fungicida antes, secar, inoculante no último momento antes do plantio); não misturar diretamente.',
 'Hungria, M. et al. (2010). Inoculation with selected strains of Azospirillum brasilense and A. lipoferum improves yields of maize and wheat in Brazil. Plant Soil 331:413-425. / Embrapa Soja (2016). Co-inoculação. Nota Técnica.',
 '{Azospirillum, brasilense, co-inoculação, Bradyrhizobium, soja, milho, trigo, IAA, fixação N2, MAPA, Ab-V5, Ab-V6, tratamento de sementes, fungicida}'),

('Biofertilizantes — Solubilizadores de fosfato: Bacillus e Pseudomonas em soja e milho',
 'artigo', 'all',
 'SOLUBILIZAÇÃO DE FOSFATO INORGÂNICO: mecanismo principal = produção de ácidos orgânicos (ácido glucônico por oxidação direta de glucose via PQQ-GDH; ácidos cítrico, málico, láctico, succínico por ciclo de Krebs); acidificação do microambiente → dissolução de fosfatos insolúveis: Ca₃(PO₄)₂ (solo neutro-alcalino), AlPO₄ e FePO₄ (solo ácido). GÊNEROS RELEVANTES: BACILLUS MEGATERIUM: solubilizador de P muito estudado; Producente de ácido glucônico via glucose desidrogenase PQQ-dependente; formulado em biofertilizante comercial ProBio P (Embrapa); ensaios de campo = +15-20% P disponível na solução do solo; PSEUDOMONAS FLUORESCENS: sideróforos + solubilização de P + antibióticos contra Fusarium; adaptada a rizosfera de soja e milho; ASPERGILLUS NIGER (fungo): produtor de ácido glucônico em quantidades industriais; base de alguns biofertilizantes comerciais. MINERALIZAÇÃO DE P ORGÂNICO: 25-85% do P total do solo é orgânico (fitatos, DNA, fosfolipídeos); enzimas fosfatases produzidas por PGPR: fosfatase ácida (pH < 6.5) e fosfatase alcalina (pH > 7.0); fitases = hidrolisam ácido fítico (IP6) → 6 inorgânicos + inositol; Bacillus subtilis e Aspergillus niger = produtores de fitase. INTERAÇÃO COM MICORRIZA (AM): hifas de AM estendem raio de exploração do solo para P → complementar aos solubilizadores bacterianos; co-inoculação AM + solubilizador P = efeitos aditivos; P insolúvel solubilizado por bactérias → absorvido por hifas AM → transferido à planta; AM conecta vantagens de ambos os mecanismos.',
 'Gyaneshwar, P. et al. (2002). Role of soil microorganisms in improving P nutrition of plants. Plant and Soil 245:83-93. / Richardson, A.E. et al. (2009). Acquisition of phosphorus and nitrogen in the rhizosphere. Plant Soil 321:305-339.',
 '{solubilização de fosfato, Bacillus, Pseudomonas, ácido glucônico, P inorgânico, fitase, micorriza AM, mineralização, P orgânico, rizosfera, biofertilizante}'),

('Biofertilizantes — Micorriza arbuscular (AM): fisiologia, colonização e benefícios nutricionais',
 'artigo', 'all',
 'MICORRIZA ARBUSCULAR (AM): simbiose entre raízes e fungos Glomeromycota (Glomus, Rhizophagus, Claroideoglomus, Funneliformis); > 80% das espécies vegetais formam AM; ESTRUTURAS: esporos no solo + hifas externas (estendem 5-20 cm além da rizosfera) + hifas internas + ARBÚSCULOS (estruturas de troca dentro das células corticais, vida útil de ~4 dias, depois digeridas = ciclo de digestão continua) + vesículas (estruturas de armazenamento). BENEFÍCIOS NUTRICIONAIS: FÓSFORO: principal benefício; hifas exploram mesoporos (0.5-5 μm) inacessíveis às raízes (> 20 μm); transporte de P via PHO84/PHT1 transportadores de alta afinidade nas hifas → interface arbuscular → planta; AM aumenta absorção de P em 3-8x em solos com P baixo; eficiência máxima em P < 25 mg/dm³ (menor que este nível = AM muito eficiente; muito alto = planta não investe em AM); MICRONUTRIENTES: Zn (AM aumenta 1.5-3x), Cu (1.5-2x), Mn, Fe (moderado); ÁGUA: hifas externas absorvem água adicional → maior tolerância a seca; MOLÉCULAS SINALIZADORAS: LCO (lipoquitooligossacarídeos = moléculas Nod-like) secretadas pelo fungo AM → ativam CSP (cascata de sinalização para colonização) na raiz. FATORES QUE REDUZEM COLONIZAÇÃO: alto P no solo (> 60-80 mg/dm³), fungicidas sistêmicos (benomyl, carbendazin), solo esterilizado/fumigado, monocultivo sem esporos; FATORES QUE FAVORECEM: baixo a médio P, rotação de culturas, plantio direto, matéria orgânica, ausência de fungicidas de solo. SOJA: AM importante principalmente em solos com P baixo; co-inoculação AM + Bradyrhizobium + Azospirillum = sinergia positiva para FBN e nutrição.',
 'Smith, S.E. & Read, D.J. (2008). Mycorrhizal Symbiosis. 3rd ed. Academic Press. / Barea, J.M. et al. (2005). Microbial co-operation in the rhizosphere. J Exp Bot 56:1761-1778.',
 '{micorriza AM, Glomus, Rhizophagus, arbúsculos, fósforo, P, Zn, Cu, hifas, colonização, solo, simbiose, Bradyrhizobium, co-inoculação, soja}'),

('Biofertilizantes — Bioestimulantes: extratos de algas, ácidos húmicos e aminoácidos',
 'artigo', 'all',
 'BIOESTIMULANTES: substâncias ou microrganismos (não nutrientes, não pesticidas) que aplicados em pequenas quantidades na planta, semente ou solo estimulam crescimento, nutrição e tolerância a estresses. CATEGORIAS PRINCIPAIS: (1) EXTRATOS DE ALGAS MARINHAS (Ascophyllum nodosum, Sargassum sp., Fucus vesiculosus): contêm betaínas (glicina betaína, λ-aminobutirobetaína, creatinina), aminoácidos, microelementos, oligossacarídeos sulfatados, laminarina (elicitora de defesa), carrageenanos; mecanismo: estimulam CK endógenas (citocininas), melhoram abertura estomática, acumulam osmoprotegentes para seca; dose típica: 1-2 L/ha; efeitos: +8-15% produtividade em soja (ensaios), maior pegamento floral, melhor enchimento; (2) ÁCIDOS HÚMICOS E FÚLVICOS: extraídos de leonardita, humus, turfa ou vermicomposto; mecanismo: aumento de CTC rizosférica → maior retenção de nutrientes; estimulam H⁺-ATPases de membrana → aumentam absorção de NO₃⁻, PO₄³⁻, K⁺; ácido fúlvico melhora solubilidade e mobilidade de Fe e Zn; dose: 3-5 L/ha (líquido); importante: qualidade (grau de humificação) varia muito entre produtos; (3) AMINOÁCIDOS EXÓGENOS: aminoácidos hidrolisados de proteína vegetal ou animal (conchilina, colágeno, hidrolisado de feather meal); mecanismo: supresso de síntese "de novo" de aminoácidos → economia de ATP e esqueletos carbonados; prolina aplicada exogenamente → ativa sistema antioxidante + osmorregulador; glicina, alanina, aminoácidos aromáticos são precursores de fenólicos e hormônios; doses: 200-500 mL/ha; melhora absorção de micronutrientes quando quelatizados com aminoácidos (Zn-aminoácido, Fe-aminoácido). (4) PROTEÍNAS HIDROLISADAS DE LEGUMINOSAS: maior especificidade hormonal, menores riscos de contaminação por patógenos animais que as de origem animal. SYNERGON EFFECT: combinação de ácido húmico + aminoácidos + extrato de alga = efeito sinérgico documentado em múltiplos estudos; prática recomendada no estresse do florescimento (R1-R2) em soja.',
 'du Jardin, P. (2015). Plant biostimulants: Definition, concept, main categories and regulation. Sci Hort 196:3-14. / Khan, W. et al. (2009). Ascophyllum nodosum extract: Evaluation of its cytokinin-like activity. J Plant Physiol 166:1-9.',
 '{bioestimulante, alga, Ascophyllum nodosum, ácido húmico, ácido fúlvico, aminoácido, prolina, glicina betaína, citocinina, osmorregulação, seca, estresse, soja, florescimento}'),

('Biofertilizantes — Silício na nutrição de plantas: absorção, mecanismos e aplicação em soja',
 'artigo', 'all',
 'SILÍCIO (Si): não classificado como essencial, mas BENÉFICO (reduz estresses e aumenta produtividade em muitas culturas). FORMAS NO SOLO: ácido monossilícico H₄SiO₄ (forma absorvida pela planta, pH 2-9 = solúvel; pH > 9 = polimerização); 0.1-0.6 mM em solução do solo; acumulado em frações amorfas (biogênica e geogênica). ABSORÇÃO: transportadores NIP (Aquaporinas Nodulin-like Intrinsic Proteins) = Lsi1 (influxo, epiderme/endoderme) e Lsi2 (efluxo, efluxa para xilema); Si acumula em folhas como sílica amorfa (SiO₂·nH₂O) na parede celular e espaços intercelulares. DEPOSIÇÃO E EFEITO FÍSICO: 1-3 mm de deposição de sílica na cutícula foliar → barreira física contra penetração de fungos (Blumeria, Magnaporthe); dupla camada sílica+cera = reduz transpiração cuticular 20-30%; deposição em casca de arroz = ~20% Si. MECANISMOS FISIOLÓGICOS: (1) ANTIOXIDANTE: Si não reage diretamente, mas ativa SOD, CAT, APX e POD endógenas → reduz ROS; SOD+Si = +40% atividade em estresse de Al; (2) ANTI-PATOGÊNICO: ativa genes de defesa PR1, PR2, PR3 (PR-proteínas) via ativação de SA; (3) ANTI-HERBIVORIA: silicificação de células da epiderme foliar → abrasão de peças bucais de insetos; (4) TOLERÂNCIA AO AL: Si + Al → precipitam como aluminossilicatos nas células da raiz → menos Al tóxico; (5) REDUÇÃO DA TOXICIDADE DE Mn: Si reduz absorção de Mn em solos ácidos e atenua sintomas de toxicidade; (6) OSMORREGULAÇÃO EM SECA: Si aplicado via foliar → reduz WUE (uso eficiente de água). DOSES PARA SOJA: silicato de cálcio (wollastonita) ou silicato de magnésio (escória de siderurgia) = 1-3 t/ha solo; silício foliar (ácido monossilícico ou silicato de potássio) = 1-2 L/ha em 200-400 L água. INTERAÇÃO COM DOENÇAS: silício reduz ferrugem da soja (P. pachyrhizi) em 30-55% em ensaios de campo.',
 'Epstein, E. (1999). Silicon. Annu Rev Plant Physiol 50:641-664. / Ma, J.F. & Yamaji, N. (2008). Functions and transport of silicon in plants. Cell Mol Life Sci 65:3049-3057. / Korndörfer et al. (Embrapa). Silício na agricultura.',
 '{silício, Si, wollastonita, escória, H4SiO4, Lsi1, Lsi2, barreira física, antifúngico, SOD, CAT, Al toxicidade, Mn toxicidade, ferrugem, soja, PR-proteínas}');
-- ─── BIOFERTILIZANTES — INOCULANTES, COMPATIBILIDADE E TECNOLOGIA DE APLICAÇÃO
-- Bradyrhizobium, co-inoculação, tratamento de sementes e interações
-- ─────────────────────────────────────────────────────────────────────────────

insert into public.conhecimento (titulo, tipo, cultura, conteudo, fonte, tags) values

('Biofertilizantes — Bradyrhizobium japonicum/elkanii: tecnologia de inoculação para soja',
 'artigo', 'soja',
 'BRADYRHIZOBIUM JAPONICUM e B. ELKANII: bactérias fixadoras de N₂ em simbiose com soja; estirpes brasileiras padrão MAPA: SEMIA 5079 (Semia 587 = B. japonicum) e SEMIA 5080 (CPAC 7 = B. elkanii) — padrão desde 1990s; NOVA GERAÇÃO: estirpes UFSC-A70 e UFSC-A73 (Embrapa 2021) = maior competitividade + maior FBN; concentração mínima = 1×10⁹ UFC/mL (líquido) ou 1×10⁹ UFC/g (turfoso). EFICIÊNCIA DA INOCULAÇÃO: solo com população de Bradyrhizobium > 10² UFC/g = pode nodular naturalmente, mas cepa nativa raramente atinge eficiência ótima; inoculação com estirpes selecionadas = 50-300 kg N/ha no ciclo; equivalente a 109-650 kg ureia/ha (N de ureia a 45%); CUSTO-BENEFÍCIO: inoculante custa R$3-10/ha vs. 100-200 kg N fertilizante mineral a R$60-120/ha = economia de R$60-200/ha quando inoculação funciona. COMPATIBILIDADE COM AGROQUÍMICOS (tabela prática): MICROBIOLÓGICO: fungicidas sistêmicos (carbendazim, tiabendazol, metalaxil) reduzem viabilidade de Bradyrhizobium 40-90% — aplicar inoculante separado, secar semente depois do fungicida; FUNGICIDAS TRIAZÓIS (tiofanato metílico, tebuconazol): redução de 30-60%; INSETICIDAS NEONICOTINÓIDES (imidacloprido, tiametoxam): redução de 10-30%; INSETICIDAS ORGANOFOSFORADOS: alta toxicidade aos inoculantes (evitar). MÉTODO CO-INOCULAÇÃO: Bradyrhizobium (100 mL/50 kg) + Azospirillum brasilense (100 mL/50 kg) aplicados separados; co-inoculação aumenta nodulação 20-40% e FBN em 15-25% vs. inoculação simples; resultado: +3-8 sc/ha em média em 22 ensaios Embrapa. DOSE EM SOLO (quando não na semente): inoculante na linha de plantio = 200-400 mL/ha de inoculante líquido; vantagem = sem interferência de agroquímicos; desvantagem = necessita equipamento próprio.',
 'Hungria, M. et al. (2013). Tecnologia de inoculação e co-inoculação em soja. Comunicado Técnico Embrapa Soja 88. / Embrapa Soja (2020). Inoculação em soja: tecnologias e perspectivas.',
 '{Bradyrhizobium, SEMIA 5079, SEMIA 5080, inoculação, soja, FBN, co-inoculação, Azospirillum, compatibilidade, fungicida, inseticida, neonicotinóide, tratamento de semente}'),

('Biofertilizantes — Inoculantes para milho e trigo: Azospirillum e diazotróficos',
 'artigo', 'milho',
 'INOCULAÇÃO EM MILHO: Azospirillum brasilense (estirpes Ab-V5 + Ab-V6, Embrapa) = inoculante oficial registrado MAPA para milho e soja (IN 13/2011, atualizada 2019); mecanismo principal no milho = produção de IAA que estimula maior densidade de pelos radiculares e raízes laterais → maior absorção de N, P e água → responde a N-mineral por aumentar a eficiência de uso. RESPOSTAS A CAMPO: meta-análise de 27 ensaios Embrapa (2010-2018) = +18% rendimento no milho inoculado; maior efeito em solos com baixo a médio N, ou em situações de seca. DOSE: 100-200 mL de inoculante líquido/50 kg semente; aplicar próximo ao plantio; manter <4h entre inoculação e plantio; evitar exposição solar direta. COMPATIBILIDADE EM MILHO: fungicidas de tratamento de semente (fludioxonil+metalaxil, tiram) reduzem viabilidade do Azospirillum → sempre aplicar o inoculante POR ÚLTIMO, imediatamente antes do plantio, ou usar inoculante in furco (na linha de plantio); inseticidas imidacloprido = redução moderada (30%); piraclostrobina+tiofanato = alta redução (60-80%) = evitar contato. INOCULAÇÃO EM TRIGO: Azospirillum irazabalense e A. brasilense; ensaios no Paraná e RS = +12-20% rendimento; economia de 20-40 kg N/ha mineral. DIAZOTRÓFICOS EM CANA-DE-AÇÚCAR: Gluconacetobacter diazotrophicus, Herbaspirillum seropedicae, Nitrospirillum amazonense = endofíticos (colonizam xilema e tecidos internos); contribuição de N = 40-170 kg N/ha documentada em cana de açúcar sem N mineral; no Brasil, variedades modernas de cana perderam parte da capacidade de associação com esses diazotróficos por seleção para alta resposta ao N mineral.',
 'Hungria, M. et al. (2010). Inoculation with selected strains of Azospirillum brasilense and A. lipoferum improves yields of maize and wheat in Brazil. Plant Soil 331:413. / Embrapa Milho e Sorgo (2020). Inoculação em milho. Circular Técnica.',
 '{Azospirillum, milho, trigo, cana, inoculante, Ab-V5, Ab-V6, IAA, N, diazotróficos, Gluconacetobacter, Herbaspirillum, tratamento de semente, in furco}'),

('Biofertilizantes — Poliaminas, osmoprotegentes e mitigação de estresse abiótico',
 'artigo', 'all',
 'POLIAMINAS (PAs): compostos policatiônicos derivados de aminoácidos (putrescina de ornitina/arginina; espermidina = putrescina + N-aminopropil; espermina = espermidina + N-aminopropil); funções: estabilização de ácidos nucleicos (DNA, RNA, ribossomas) e membranas; inibição de nucleases e proteases; interação com receptores de GABA; sinalização em senescência e frutificação. RELAÇÃO COM ESTRESSES: SECA: PA aumentam em folhas de plantas submetidas à seca; espermidina + espermina estabilizam tilacoides e membranas → reduz dano por dehydration; putrescina + seca → ativa síntese de prolina (via P5CS) → osmoregulação. CALOR: espermidina ativa resposta de choque térmico (HSP) → thermotolerance; SALINIDADE: PAs reduzem entrada de Na⁺ via inibição de canais não-seletivos de cátions. INTERAÇÃO NUTRITIONAL: POTÁSSIO: K regula biossíntese de putrescina (K-deficiência → acúmulo de putrescina → sinal de alerta); ENXOFRE: S necessário para síntese de S-adenosilmetionina (SAM, precursor de espermidina e espermina via dcSAM); COBRE: PAs oxidadas por diamino oxidases (Cu-dependentes) → H₂O₂ → sinalização secundária. APLICAÇÕES PRÁTICAS: espermidina exógena (0.1-1 mM) foliar = documentado aumento de tolerância a seca e calor em soja (R1-R2); extrato de algas (Ascophyllum nodosum) = fonte natural de betaínas análogas a PAs; poliaminas via aminoácidos exógenos (arginina, prolina) = via indireta de suplementação. BIOSSÍNTESE DE ETILENO: PA e etileno compartilham SAM como precursor → competição entre vias (PA produção alta = inibe etileno; IAA estimula PA → auxilia em enraizamento).',
 'Alcázar, R. et al. (2010). Involvement of polyamines in plant response to abiotic stress. Biotechnol Lett 32:1857. / Kusano, T. et al. (2008). Polyamines: essential factors for growth and survival. Planta 228:367.',
 '{poliaminas, putrescina, espermidina, espermina, seca, calor, salinidade, S, K, Cu, SAM, etileno, osmoprotegente, betaína, Ascophyllum, alga}'),

('Biofertilizantes — Ácido húmico e fúlvico: mecanismos de ação em nutrição e crescimento',
 'artigo', 'all',
 'SUBSTÂNCIAS HÚMICAS (SH): produto final da decomposição da matéria orgânica; classificadas por solubilidade: ÁCIDO HÚMICO (AH) = solúvel em base (pH>2), insolúvel em ácido; ÁCIDO FÚLVICO (AF) = solúvel em toda faixa de pH; HUMINA = insolúvel; composição: núcleos aromáticos, cadeias alifáticas, grupos funcionais ácidos (-COOH, -OH) e N alifático. MECANISMOS DE AÇÃO: (1) ESTIMULAÇÃO DE H⁺-ATPase: AH e AF ativam ATPases de membrana plasmática (dose-resposta: 0.01-10 mg C/L = estimulação; > 100 mg C/L = inibição) → maior ejeção de H⁺ → acidificação apoplasto folhas → ativação de expansinas → crescimento celular; (2) PROMOÇÃO DE TRANSPORTE IÔNICO: ativação de ATPases aumenta gradiente eletroquímico → favorece absorção de NO₃⁻, K⁺, Fe²⁺; (3) QUELAÇÃO DE MICRONUTRIENTES: grupos -COOH e -OH de SH formam complexos orgânicos com Fe³⁺, Zn²⁺, Mn²⁺, Cu²⁺ → protege micronutrientes da fixação no solo e facilita absorção; pH-dependente: AH+Fe em pH 6-7 = Fe mais estável que Fe-EDTA; (4) MIMETISMO HORMONAL: AH apresentam atividade auxínica (estimulam enraizamento) e citocininica (retardam senescência); estruturas aromáticas de AH ativam receptores de hormônios; (5) MELHORIA ESTRUTURAL DO SOLO: AH formam microagregados com argilas → melhor estrutura, maior retenção de água e difusão de O₂. FONTES COMERCIAIS: leonardita = rocha sedimentar rica em SH (60-80% SH); vermicomposto; xisto retortado; extrato fermentado de algas. DOSE ÓTIMA: AH 10-30 kg/ha (solo); AF 3-5 L/ha (foliar, 100-200 mg C/L); associação AH+AF = efeito sinérgico na absorção de Fe, Zn e Ca. SOJA: AF foliar em V3-R1 = +8-12% nodulação, +5-10% produtividade em ensaios Embrapa.',
 'Canellas, L.P. et al. (2015). Humic and fulvic acids as biostimulants in horticulture. Sci Hort 196:15-27. / Nardi, S. et al. (2002). Soil organic matter and plant growth. Plant Soil 147:47.',
 '{ácido húmico, ácido fúlvico, humina, leonardita, H+-ATPase, quelação, Fe, Zn, Mn, Cu, expansina, crescimento radicular, mimetismo hormonal, substâncias húmicas, biofertilizante}');
-- ─── TAIZ & ZEIGER — FISIOLOGIA VEGETAL — ESTRESSE HÍDRICO, TÉRMICO E SALINO
-- Capítulos 22-26 da 5ª edição (2013) — respostas a estresses abióticos
-- ─────────────────────────────────────────────────────────────────────────────

insert into public.conhecimento (titulo, tipo, cultura, conteudo, fonte, tags) values

('Taiz & Zeiger — Potencial hídrico, déficit hídrico e resposta estomática ao ABA',
 'artigo', 'all',
 'RELAÇÕES HÍDRICAS (Cap. 3 & 23): POTENCIAL HÍDRICO (Ψw) = Ψs + Ψp + Ψm; Ψs = potencial osmótico (solutos rebaixam); Ψp = potencial de pressão (turgor); Ψm = potencial mátrico (forças de adsorção ao solo). DÉFICIT HÍDRICO INICIAL → cadeia de eventos: (1) Ψw foliar cai → células perdem turgor → fechamento estomático (reversível com hidratação); (2) Ψs cai por ajuste osmótico (acúmulo de prolina, betaína, solutos compatíveis, K⁺); (3) síntese de ABA: início em cloroplastos (violaxantina → xantoxina → ABA-aldeído → ABA) → exportação via xilema → células guarda → ativa canais ânion (SLAC1) e fecha K⁺-entrada (KAT1) → turgescência cai → estômato fecha. SINALIZAÇÃO DE ABA: ABA + receptor PYR/PYL → inibe PP2C → ativa SnRK2 quinases → fosforila SLAC1 (abre) e KAT1 (fecha) → K⁺ sai de célula guarda + Cl⁻ sai → água sai → turgor cai → fechamento. SENSORES DE SECA NA RAIZ: receptor OSCA1 (mecanossensitivo) detecta déficit osmótico → CaM/CMLs ativadas → MAP quinases → ABA. AJUSTE OSMÓTICO: prolina (aminoácido derivado de glutamato via P5CS, até 5% do PS em seca) → protege proteínas e membranas, scavenger de ¹O₂; GLICINA BETAÍNA (derivada de colina + oxidação por CMO/BETAINE ALDEHYDE DEHYDROGENASE) → protege estroma do cloroplasto e tilacoides; ambas são osmoprotegentes compatíveis que não inibem enzimas. INTERAÇÃO MINERAL: K⁺ (60-80% do ajuste osmótico inicial em déficit hídrico leve); Mg² e Ca²⁺ estabilizam membranas; Si (silício) reduz WUE e diminui taxa de transpiração cuticular 20-30%.',
 'Taiz, L. & Zeiger, E. (2013). Plant Physiology. 5th ed. Cap. 3, 23. Sinauer Associates.',
 '{déficit hídrico, potencial hídrico, ABA, PYR/PYL, SnRK2, SLAC1, KAT1, estômato, ajuste osmótico, prolina, betaína, seca, K, Si, silício, P5CS}'),

('Taiz & Zeiger — Estresse térmico: HSPs, chaperoninas e resposta ao calor extremo',
 'artigo', 'all',
 'ESTRESSE TÉRMICO (Cap. 26): TEMPERATURAS CRÍTICAS EM SOJA: abaixo de 10°C = inibe germinação; 15°C = crescimento lento; ótimo = 25-30°C; 35°C = redução severa da FBN (nitrogenase inativada); 38°C = inibição do tubo polínico → aborto floral; 42°C+ = desnaturação proteica generalizada. DANO MOLECULAR: membranas tilacoidais são as primeiras atingidas (fluidez excessiva → desacoplamento da fosforilação oxidativa); PSII mais sensível (dissociação de complexo de oxidação da água); rubisco ativase inibida acima de 35°C (deixa rubisco inativa); repressão de sintase de amido em endosperma → menos amido em grãos. RESPOSTA AO CHOQUE TÉRMICO: (1) SENSOR DE TEMPERATURA: membranas lipídicas (desaturação de ácidos graxos → maior fluidez = sinal); RECEPTOR DE TEMPERATURA: CNGC (canais não-seletivos de cátions) → Ca²⁺ entra; (2) HSFs (fatores de transcrição de choque térmico): HsfA2 (principal em plantas) ativado por Ca²⁺ → liga ao HSE (elemento de choque térmico, AAGAA) → ativa genes HSP; (3) HSPs (Heat Shock Proteins): HSP70 (70 kDa, ATPase-dependente) = previne desnaturação de proteínas (dobramento correto, desfazimento de agregados); HSP90 (chaperona de clientes específicos); HSP100/ClpB = redobra proteínas já desnaturadas; sHSPs (pequenas, 15-42 kDa) = formam oligômeros que protegem proteínas do estresse. TERMOTOLERÂNCIA ADQUIRIDA: aplicação de temperatura subletal (38°C/1h) → pré-adaptação para temperatura letal (45°C/2h); mediado por acúmulo de HSP, prolina e ácido salicílico; Azospirillum inoculado estimula termotolerância via produção de GABA. INTERAÇÃO MINERAL: CÁLCIO (Ca²⁺ como segundo mensageiro do choque térmico); MAGNÉSIO (ativa Rubisco ativase); POTÁSSIO (retenção de K⁺ em membranas estabilizadas pelas HSPs).',
 'Taiz, L. & Zeiger, E. (2013). Plant Physiology. 5th ed. Cap. 26. Sinauer Associates.',
 '{estresse térmico, calor, HSP, chaperonina, HsfA2, HSE, PSII, rubisco, Ca, Mg, K, termotolerância, aborto floral, FBN, soja, desnaturação, prolina, SA}'),

('Taiz & Zeiger — Estresse oxidativo: ROS, enzimas antioxidantes e neutralização',
 'artigo', 'all',
 'ESPÉCIES REATIVAS DE OXIGÊNIO (ROS): geradas em cloroplastos, mitocôndrias e peroxissomos como subproduto do metabolismo aeróbico; principais ROS: O₂•⁻ (radical superóxido), H₂O₂ (peróxido de hidrogênio), ¹O₂ (oxigênio singlete), HO• (radical hidroxil). GERAÇÃO: CLOROPLASTO: transporte de elétrons — O₂ recebe e- de ferredoxina → O₂•⁻ (reação de Mehler); PSII sob excesso de luz → ¹O₂; MITOCÔNDRIA: complexo I e III vazam e- para O₂; PEROXISSOMO: glicólato oxidase produz H₂O₂ em fotorespiration; REAÇÃO DE FENTON: Fe²⁺ + H₂O₂ → Fe³⁺ + HO• + OH⁻ (ROS mais destrutiva). SISTEMA DE DEFESA ANTIOXIDANTE: ENZIMÁTICO: SOD (dismuta O₂•⁻ → H₂O₂ + O₂; Cu/Zn-SOD no cloroplasto, Mn-SOD na mitocôndria, Fe-SOD nos plastídios); CAT (H₂O₂ → H₂O + ½O₂, peroxissomo); APX (H₂O₂ + Ascorbato → H₂O + DHA, cloroplasto); GPX (glutation peroxidase); POD (peroxidases + compostos fenólicos). CICLO ASCORBATO-GLUTATIONA (Foyer-Halliwell-Asada): APX reduz H₂O₂ → DHA → MDHAR (MDHA redutase) → ASA reduzido; DHAR (DHA redutase, usa GSH) → ASA; GR (glutation redutase, usa NADPH) → GSH; cloroplasto mantém [ASA] = 10-30 mM, [GSH] = 1-5 mM. NÃO-ENZIMÁTICO: Ascorbato (ASA), Glutationa (GSH), α-tocoferol (membranas), β-caroteno (¹O₂ quencher), flavonoides. INTERAÇÃO MINERAL: ZN (Cu/Zn-SOD), MN (Mn-SOD), FE (Fe-SOD, CAT, APX, POD), CU (Cu/Zn-SOD, POD). PROLINA: além de osmoprotegente, é scavenger direto de ¹O₂ e ativador de APX e SOD.',
 'Taiz, L. & Zeiger, E. (2013). Plant Physiology. 5th ed. Cap. 26. Sinauer Associates.',
 '{ROS, estresse oxidativo, SOD, CAT, APX, POD, ciclo ascorbato-glutationa, GSH, ascorbato, Zn, Mn, Fe, Cu, prolina, cloroplasto, Fenton, H2O2, superóxido}'),

('Taiz & Zeiger — Respostas a estresses bióticos: JA, SA e ETH na defesa vegetal',
 'artigo', 'all',
 'ESTRESSE BIÓTICO — TRIÂNGULO DA DEFESA (Cap. 13): resistência vegetal a patógenos depende de interações entre PATÓGENO, PLANTA e AMBIENTE; três categorias de reconhecimento: PTI (Pattern-Triggered Immunity = PAMPs + PRRs), ETI (Effector-Triggered Immunity = Avr + R-proteins = HR hipersensitiva), SAR (Systemic Acquired Resistance = SA). ÁCIDO JASMONICO (JA) e JASMIL-ISOLEUCINA (JA-Ile): sintetizados via ácido α-linolênico → LOX (lipooxigenase, Fe-dependente) → 13-HPOT → AOS (aleno oxidase sintase) → AOC (aleno óxido ciclase) → OPDA → 12-oxo-PDA → JA; JA + isoleucina = COI1 (receptor ubiquitina-ligase E3) + JAZ (repressores de MYC2) → JAZ degradados → MYC2 ativo → genes de defesa. JA RESPOSTAS: síntese de inibidores de protease (PI-I, PI-II = serina proteases = anti-herbívoro); tionininas e defensinas; genes de fenilpropanoide; TERPENOS VOLÁTEIS (sesquiterpenos = atraem predadores dos herbívoros = defesa indireta). ÁCIDO SALICÍLICO (SA): sintetizado via PAL (fenilalanina amônia liase) ou ICS (isochorismate synthase); receptor NPR1 (redutase TGA-TF ativada por SA) → PR-genes (PR1 = barômetro de SAR; PR2 = β-1,3-glucanase; PR3, PR4 = quitinases); NPR1 existe como monômero (no núcleo, ativo) vs oligômero (no citosol, inativo) → S-S pontes de cisteínas regulam transição; SA muda equilíbrio → redução de pontes dissulfeto → NPR1 monômero ativo. SAR vs ISR: SAR (Systemic Acquired Resistance) = SA-dependente, ativada por patógenos necrotróficos (biótrofos causam HR, liberam SA); ISR (Induced Systemic Resistance) = JA/ET-dependente, ativada por PGPR (Pseudomonas fluorescens WCS417r). ANTAGONISMO JA/SA: JA e SA frequentemente antagônicos; SA suprime COI1-JAZ → inibe JA; JA suprime NPR1 → inibe SA; estratégia do patógeno: biotrófico induz SA que inibe JA; necrótrofo induz ET+JA. INTERAÇÃO MINERAL: Mn (ativa PAL para SA); Si (estimula SA + JA); Zn (ativa LOX para JA); N (afeta síntese de PR-proteínas nitrogenadas).',
 'Taiz, L. & Zeiger, E. (2013). Plant Physiology. 5th ed. Cap. 13. Sinauer Associates.',
 '{JA, ácido jasmônico, SA, ácido salicílico, LOX, COI1, JAZ, MYC2, NPR1, PR-proteínas, SAR, ISR, ETI, PTI, PAMP, defesa biótica, patógeno, herbívoro, Mn, Si, Zn}'),

('Taiz & Zeiger — Absorção de nutrientes: mecanismos de transporte e cinética',
 'artigo', 'all',
 'ABSORÇÃO DE NUTRIENTES (Cap. 5): MECANISMOS: (1) DIFUSÃO: movimento de íons de maior → menor concentração; limitado pelo coeficiente de difusão no solo (P = 10⁻¹³ m²/s = quase imóvel; NO₃⁻ = 10⁻⁹ m²/s; K⁺ = 10⁻¹¹ m²/s); fluxo de massa vs difusão vs intercepção radicular. (2) PROTEÍNAS TRANSPORTADORAS: ALTA AFINIDADE (HAT) = funciona em baixa [íon] (< 0.5 mM), cinética Michaelis-Menten, transportadores individuais; BAIXA AFINIDADE (LAT) = funciona em alta [íon] (> 1 mM), canais e transportadores de baixa especificidade. TRANSPORTADORES CHAVE: NITRATO: NRT1.1 (dual affinity, ativo em < 0.25 mM e > 1 mM; sensor também de N); NRT2.1+NAR2 (HAT puro); AMÔNIO: AMT1.1, AMT1.2, AMT1.3 (HAT); FOSFATO: PHT1 família (14 genes em Arabidopsis); PHO1 (exporta P do xilema); POTÁSSIO: KT/HAK/KUP (HAT); AKT (canais inward K); KOR (canais outward K); FERRO: IRT1 (importa Fe²⁺ + Zn²⁺ + Mn²⁺ + Cd²⁺); FRO2 (ferri-redutase que reduz Fe³⁺→Fe²⁺ antes de IRT1); ZINCO: ZIP1-14 (importadores de Zn²⁺ e outros cátions divalentes). GRADIENTE ELETROQUÍMICO: H⁺-ATPase de membrana plasmática (consumidora de ATP) → ejeta H⁺ → Δψ negativo (-120 a -180 mV) + ΔpH (mais ácido fora) → força proton-motive force → cotransporte H⁺/íon. PELO RADICULAR: aumenta área de absorção 10-100x; 1 g de solo explorado = 10 km de pelos radiculares em trigo; pelos radiculares colonizados por AM = amplia zona de absorção para além da depleção radicular. INTERAÇÃO COM AGROQUÍMICOS: herbicidas inibidores de ALS (imazapir, imazetapir) → reduzem crescimento radicular → menor área de absorção de P e Zn; glifosato quelata Mn → reduz absorção de Mn e molibdênio.',
 'Taiz, L. & Zeiger, E. (2013). Plant Physiology. 5th ed. Cap. 5. Sinauer Associates.',
 '{absorção de nutrientes, NRT1, NRT2, AMT1, PHT1, IRT1, FRO2, ZIP, HAT, LAT, H+-ATPase, difusão, fluxo de massa, pelo radicular, AM, Mn, Mo, glifosato, imazapir}');
-- ─── BRADY & WEIL — THE NATURE AND PROPERTIES OF SOILS (14ª Ed., 2007) ──────
-- Solo: textura, estrutura, matéria orgânica, CTC, pH e disponibilidade de nutrientes
-- ─────────────────────────────────────────────────────────────────────────────

insert into public.conhecimento (titulo, tipo, cultura, conteudo, fonte, tags) values

('Brady & Weil — Textura do solo e sua influência na CTC e disponibilidade de nutrientes',
 'referencia', 'all',
 'TEXTURA DO SOLO (Cap. 4): classificação por proporção de areia (2-0.05 mm), silte (0.05-0.002 mm) e argila (< 0.002 mm). TRIÂNGULO TEXTURAL USDA: textura argilosa (> 40% argila), argilossiltosa (> 40% argila + > 40% silte), franco-argilosa, franca (20-30% argila, 25-50% silte), siltosa, arenosa (> 85% areia). CONSEQUÊNCIAS PRÁTICAS: ARGILA: maior superfície específica (1-800 m²/g, vs areia = 0.01 m²/g); maior CTC; melhor retenção de água e nutrientes; mais suscetível a compactação; drenagem mais lenta. AREIA: macro-poros dominantes, excelente drenagem, baixíssima retenção de nutrientes; lixiviação intensa de K⁺, Mg²⁺, NO₃⁻, B. SILTE: propriedades intermediárias, suscetível à formação de crosta na superfície. CTC (CAPACIDADE DE TROCA CATIÔNICA): argila minerais têm CTC permanente (substituição isomórfica de Si⁴⁺ por Al³⁺ nas esmectitas) E dependente de pH (grupos -OH de argilas 1:1 como caulinita e de SH); solos argilosos = 15-60 cmolc/dm³; solos arenosos = 1-5 cmolc/dm³; matéria orgânica contribui 150-300 cmolc/dm³ por unidade de MO. MANEJO: solos arenosos precisam de aplicações mais frequentes e parceladas de K, Mg, B, N; solos argilosos retêm mais K e Mg mas podem ter problemas de compactação; adubação em solos arenosos deve seguir diagnose de solo frequente (cada 1-2 anos).',
 'Brady, N.C. & Weil, R.R. (2007). The Nature and Properties of Soils. 14th ed. Prentice Hall, New Jersey.',
 '{textura, argila, areia, silte, CTC, capacidade de troca catiônica, superfície específica, retenção de nutrientes, lixiviação, K, Mg, B, N, compactação, solos arenosos, solos argilosos}'),

('Brady & Weil — pH do solo: tampão, efeitos na disponibilidade de nutrientes e calagem',
 'referencia', 'all',
 'pH DO SOLO (Cap. 8): escala logarítmica (pH = -log[H⁺]); variação típica em solos agrícolas = pH 4.0-8.5; CAPACIDADE TAMPÃO: resistência à mudança de pH = função da CTC e da quantidade de íons ácidos (H⁺ + Al³⁺) em solução e adsorvidos; solos argilosos = maior poder tampão = precisam de mais calcário para corrigir o pH. EFEITOS DO pH NA DISPONIBILIDADE DE NUTRIENTES (curva de Truog): MÁXIMA DISPONIBILIDADE: N (pH 6.0-8.0 via nitrificação ótima); P (pH 6.0-7.0 = mínima fixação); K, Ca, Mg, S (pH > 6.5); B (pH 6.0-7.5); Cu, Zn (pH 6.0-7.0). MÍNIMA DISPONIBILIDADE (BLOQUEIO): P: pH < 5.5 = fixação por Al³⁺ e Fe³⁺ como FePO₄ e AlPO₄; pH > 7.5 = fixação por Ca como Ca₃(PO₄)₂; Fe, Mn: pH < 5.5 = muito solúveis (toxicidade); pH > 7 = precipitados (deficiência); Zn, Cu, B: pH > 7 = insolúveis; Mo: único que aumenta com pH alcalino (molibdênio mais disponível acima de 6.5). ALUMÍNIO: Al³⁺ em pH < 5.5 = inibe divisão celular no ápice radicular (Al³⁺ inibe ATPases e enzimas); em concentrações > 1-2 μmol/L = fitotóxico para maioria das culturas; soja tolera < 10% saturação Al; milho tolera < 15-20%; arroz de terras altas mais sensível. CALAGEM PARA SOJA: elevar pH CaCl₂ para 5.8-6.2 (Embrapa) ou pH H₂O 6.0-6.5; calcário calcítico (CaCO₃) vs dolomítico (CaCO₃+MgCO₃); PRNT = poder relativo de neutralização total (corrigir pela granulometria); dose = V% desejada x CTC pH 7.0 / PRNT; incorporar 60-90 dias antes do plantio idealmente.',
 'Brady, N.C. & Weil, R.R. (2007). The Nature and Properties of Soils. 14th ed. Prentice Hall. / Embrapa Soja (2013).',
 '{pH, tamponamento, calagem, calcário, Al, alumínio, P, Fe, Mn, Zn, B, Mo, disponibilidade, PRNT, CTC, V%, saturação de Al, soja, milho}'),

('Brady & Weil — Matéria orgânica do solo (MO): funções, mineralização e sequestro de carbono',
 'referencia', 'all',
 'MATÉRIA ORGÂNICA DO SOLO (MO) (Cap. 11): composta de HÚMUS (SH + materiais humificados = 65-75% da MO estável), resíduos vegetais parcialmente decompostos (10-15%), biomassa microbiana (5-10%), raízes vivas e mortas (5-10%). FUNÇÕES DA MO: (1) NUTRICIONAL: mineralização libera N (1-3% N na MO orgânica), P (0.1-0.4%), S (0.05-0.1%), micronutrientes; taxa de mineralização = 1-3% da MO/ano em trópicos; 30 g MO/kg solo com 3% N = 90 mg N/kg solo potencial; (2) FÍSICA: melhora estrutura do solo (formação de macroagregados com argila), aumenta capacidade de retenção de água (1 g MO retém 20 g H₂O), reduz densidade do solo, diminui erosão; (3) QUÍMICA: CTC de SH = 150-300 cmolc/dm³ (10x mais que caulinita); quelação de micronutrientes; tamponamento de pH; (4) BIOLÓGICA: substrato para biomassa microbiana; regulação de doenças de solo. MINERALIZAÇÃO: processo de decomposição de MO em CO₂ + H₂O + nutrientes minerais; controlada por: temperatura (Q₁₀ = 2-3, duplica por 10°C de aumento), umidade (máximo em θ = 60% WFPS), relação C:N (< 20:1 = mineralização líquida; 20-30:1 = equilíbrio; > 30:1 = imobilização); qualidade do resíduo (lignina, taninos, polifenóis retardam decomposição). SEQUESTRO DE C: plantio direto + cobertura = input de resíduos > saída por mineralização = acúmulo; conversão de degradado em plantio direto = sequestro de 0.5-1 t C/ha/ano; objetivo: aumentar de 20-30 g MO/kg para > 35-40 g MO/kg em solos do cerrado. INTERAÇÃO COM NUTRIENTES: MO alta → maior buffer de pH → menor toxicidade de Al; MO alta → CTC alta → menor lixiviação de K, Mg, Ca; MO chelates → micronutrientes mais móveis no solo.',
 'Brady, N.C. & Weil, R.R. (2007). The Nature and Properties of Soils. 14th ed. Prentice Hall.',
 '{matéria orgânica, MO, húmus, mineralização, C:N, N, P, S, CTC, estrutura do solo, sequestro de carbono, plantio direto, lixiviação, micronutrientes, Al, biodegradação}'),

('Brady & Weil — Dinâmica do potássio no solo: formas, lixiviação e adsorção',
 'referencia', 'all',
 'POTÁSSIO NO SOLO (Cap. 16): FORMAS: (1) K solúvel (< 1% do total) = K⁺ em solução, imediatamente disponível; (2) K trocável (1-5%) = K⁺ adsorvido nos sítios de CTC, em equilíbrio com solução; (3) K não-trocável (10-50%) = K preso em espaços entrefolha de micas e argilominerais (ilita, vermiculita) = liberação lenta; (4) K mineral da rocha matriz (50-90%) = feldspatos, micas = liberação muito lenta (séculos). TAMPÃO DE K: tampão de K = capacidade do solo de manter [K⁺] na solução = função da CTC e da proporção de K nos sítios trocáveis; solos com alta CTC argilosa = maior tampão; solos arenosos = baixo tampão = K lixivia facilmente. LIXIVIAÇÃO: K⁺ = cátion monovalente = menos adsorvido que Ca²⁺ e Mg²⁺ (menor força de adsorção); em solos arenosos tropicais com alta precipitação = perda de 20-60 kg K/ha/ano por lixiviação; parcelamento da adubação potássica em solos arenosos = obrigatório para reduzir perdas. ANTAGONISMO: K⁺ x Mg²⁺ (competição no CEC e nos transportadores HKT da membrana plasmática); K⁺ x Ca²⁺ (mesmo mecanismo, menor intensidade); excesso de K na CTC (K/CTC > 5-6%) = risco de induzir carência de Mg. ADUBAÇÃO DE K: KCl (60% K₂O, mais econômico); K₂SO₄ (50% K₂O, menos Cl, melhor para Cl-sensíveis); KNO₃ (foliar, mais solúvel); K magnésio (granulado K+Mg, evita competição); dose = demanda da cultura − teor de K trocável × fator solo.',
 'Brady, N.C. & Weil, R.R. (2007). The Nature and Properties of Soils. 14th ed. Prentice Hall.',
 '{potássio, K, lixiviação, CEC, CTC, K trocável, tampão de K, Mg, Ca, KCl, K2SO4, KNO3, solos arenosos, parcelamento, adubação, soja, milho}'),

('Brady & Weil — Frações de fósforo no solo: fixação, mobilidade e estratégias de manejo',
 'referencia', 'all',
 'FÓSFORO NO SOLO (Cap. 17): FRAÇÕES (sequencial de Hedley): P prontamente disponível (H₂O + NaHCO₃); P moderadamente disponível (NaOH); P ligado ao Ca (HCl); P recalcitrante (P em ácidos húmicos + residual); SOLOS TROPICAIS (Latossolos, Oxissolos): 60-80% do P total = P inorgânico ligado a óxidos de Fe (goethita, hematita) e Al (gibbsita) = P pouco disponível; FIXAÇÃO QUÍMICA DE P: P + Fe³⁺/Al³⁺ → FePO₄ / AlPO₄ insolúveis; ou P adsorvido em grupos -OH dos óxidos de Fe/Al via troca de ligantes; Latossolo Vermelho do cerrado = capacidade de fixação de 1000-3000 mg P/dm³ solo (muito alta); IMPLICAÇÃO AGRONÔMICA: dose de P para Latossolo atingir 12 mg P/dm³ = 200-400 kg P₂O₅/ha (aplicação inicial) vs 30-60 kg P₂O₅/ha em manutenção. ESTRATÉGIAS PARA AUMENTAR EFICIÊNCIA DE P: (1) Colocação no sulco de plantio (band = reduz contato com solo, reduz fixação); (2) Acidificação localizada (acidulantes no sulco; raízes acidificam rizosfera); (3) Micorriza arbuscular (hifas exploram P não-depletado além da rizosfera); (4) PGPR solubilizadoras de P; (5) Ácidos húmicos e fúlvicos competem com P pelos sítios de fixação (bloqueio de sítios de adsorção). MOBILIDADE: P move-se no solo quase exclusivamente por difusão (10⁻¹³ m²/s); zona de depleção = 1-3 mm ao redor da raiz; por isso volume de raízes e pelos = determinante para absorção de P.',
 'Brady, N.C. & Weil, R.R. (2007). The Nature and Properties of Soils. 14th ed. Prentice Hall. / Novais, R.F. & Smyth, T.J. (1999). Fósforo em solo e planta em condições tropicais. UFV.',
 '{fósforo, P, fixação de P, Latossolo, oxissolo, cerrado, frações de Hedley, solubilização, micorriza, PGPR, ácido húmico, difusão, zona de depleção, sulco, band, goethita, gibbsita}');
-- ─── NOVAIS et al. — FERTILIDADE DO SOLO (SBCS, 2007) ───────────────────────
-- Micronutrientes, zinco, boro, manganês, ferro, molibdênio em solos tropicais
-- ─────────────────────────────────────────────────────────────────────────────

insert into public.conhecimento (titulo, tipo, cultura, conteudo, fonte, tags) values

('Novais et al. — Zinco no solo: formas, disponibilidade e calagem',
 'referencia', 'all',
 'ZINCO (Zn) NO SOLO (Cap. 11 — Novais et al.): FORMAS: Zn²⁺ em solução (< 0.1% do total); Zn adsorvido (troca de cátions e adsorção específica em óxidos Fe/Al); Zn ligado à MO (compostos orgânicos-Zn); Zn mineral (silicatos, smithsonita ZnCO₃). DISPONIBILIDADE: afetada fortemente pelo pH — cada unidade de pH acima de 6.0 reduz Zn²⁺ em solução 10-100x (reação: Zn(OH)⁺ → Zn(OH)₂ → ZnO); FIXAÇÃO: em solos com pH > 6.5 + P alto → Zn₃(PO₄)₂ insolúvel; P alto + Zn baixo = antagonismo P-Zn clássico dos Oxissolos; relação P:Zn ideal foliar = 50:1 (acima = deficiência induzida por P). DIAGNOSE: análise de solo com DTPA-TEA (pH 7.3) = extrator padrão; valores críticos: < 0.5 mg Zn/dm³ = deficiente (CQFS RS/SC); 0.5-1.0 mg/dm³ = médio; > 1.0 mg/dm³ = adequado. DIAGNOSE FOLIAR SOJA (V3-V4): < 21 mg/kg = deficiente; 21-50 mg/kg = adequado; > 50 mg/kg = alto. ADUBAÇÃO CORRETIVA: SOLO = 2-5 kg/ha Zn (sulfato de Zn, 20-22% Zn) ou óxido de Zn (50-80% Zn); aplicar ao solo a cada 2-3 anos; FOLIAR = 150-300 g/ha Zn-EDTA (quelatado = maior mobilidade) ou 300-500 g/ha ZnSO₄·7H₂O (barato mas menos eficiente em solo alcalino). INTERAÇÃO COM Mo: solos ácidos com pH < 5.5 = Zn e Mo deficientes simultaneamente; calagem corrige ambos (Zn disponível em 6.0-6.5; Mo disponível > 6.5).',
 'Novais, R.F. et al. (2007). Fertilidade do Solo. SBCS, Viçosa / CQFS RS/SC (2016). Manual de Calagem e Adubação.',
 '{Zn, zinco, pH, fixação, P, antagonismo P-Zn, DTPA, disponibilidade, diagnose foliar, sulfato de Zn, EDTA, quelatado, calagem, Mo, soja}'),

('Novais et al. — Boro no solo: calagem, chuva e deficiência em florescimento',
 'referencia', 'all',
 'BORO (B) NO SOLO: FORMAS: ácido bórico H₃BO₃ (forma predominante em pH < 7, não-iônico, muito móvel = suscetível à lixiviação); tetraborato B(OH)₄⁻ (forma em pH > 9); B adsorvido em Al/Fe óxidos e MO (ligação reversível, pH-dependente: máxima adsorção = pH 7-9; B muito disponível em pH 5.5-6.5 e muito pouco em pH > 7.5). DINÂMICA NO SOLO: B = micronutriente mais lixiviado em solos tropicais (exceção parcial = carga variável fixa B nos óxidos); em período seco, B fica retido em óxidos e MO → deficiência funcional; em chuva intensa = B lixivia novamente. CALAGEM: calagem eleva pH → aumenta adsorção de B → reduz B em solução → deficiência induzida por calagem! = fenômeno frequente em solos do cerrado após calagem para V% 70% sem correção de B. DIAGNOSE SOLO: extrator ácido clorídrico (Embrapa) ou água quente (Berger-Truog): < 0.3 mg B/dm³ = deficiente; 0.3-1.0 = adequado; > 1.0 = alto (toxicidade possível acima de 2-3 mg/dm³). DIAGNOSE FOLIAR SOJA: < 30 mg B/kg = deficiente; 30-60 = adequado; > 60-100 = risco de toxicidade. ADUBAÇÃO: SOLO = 0.5-2 kg/ha B (bórax 10.5% B, ou borogran, B+ granulado) = solo ácido ou por ocasião da calagem; FOLIAR = 100-300 g/ha B (ácido bórico 17.5% B ou octaborato de sódio) = aplicar em V5-V6 e R1 (pré e início do florescimento) OBRIGATORIAMENTE em soja; intervalo de segurança entre duas aplicações de B = 10-14 dias (toxicidade acumulativa). FUNÇÃO CRÍTICA EM FLORESCIMENTO: B essencial para germinação do grão de pólen e crescimento do tubo polínico → deficiência em R1 = queda imediata de flores e aborto de vagens jovens = perda econômica grave.',
 'Novais, R.F. et al. (2007). Fertilidade do Solo. SBCS, Viçosa. / CQFS RS/SC (2016).',
 '{boro, B, lixiviação, calagem, pH, H3BO3, adsorção, deficiência, toxicidade, florescimento, tubo polínico, V5, R1, bórax, ácido bórico, soja, foliar, cerrado}'),

('Novais et al. — Manganês e ferro: toxicidade em solos ácidos e alagados',
 'referencia', 'all',
 'MANGANÊS (Mn) NO SOLO: FORMAS: Mn²⁺ (divalente, solúvel, absorvível; pH < 5.5 = alta concentração); Mn³⁺ (intermediária); Mn⁴⁺ (MnO₂ = insolúvel, precipitado em pH > 6.5); TOXICIDADE CLÁSSICA: pH < 5.5 → Mn²⁺ aumenta em solução exponencialmente (pH 5.5 = 10 μmol/L; pH 5.0 = 100 μmol/L; pH 4.5 = 1000 μmol/L); > 300-500 μmol/L = fitotóxico para soja; sintomas = pontos marrons nas folhas velhas ("escoriose"), clorose; inibe absorção de Mg, Fe, Mo. CALAGEM CORRIGE: elevação de pH 5.5 → 6.0 = Mn disponível cai 10x; mais importante que adubação de Mn para corrigir toxicidade. FERRO (Fe) NO SOLO: Fe²⁺ (divalente, solúvel; solos reduzidos = alagados pH < 6.5, Fe²⁺ aumenta muito); Fe³⁺ (pH > 7 = hidróxidos e oxihidróxidos insolúveis); TOXICIDADE DE Fe EM SOLOS ALAGADOS: bronzeamento foliar, manchas ferrugem, clorose; rice iron toxicity = > 500 μmol Fe²⁺/L; drenagem do solo reduz Fe²⁺; Si foliar e Ca foliar reduzem absorção e dano. DIAGNOSE DE Fe E Mn SOLO: Fe (DTPA): < 4.5 mg/dm³ = deficiente; Mn (DTPA): < 1.0 mg/dm³ = deficiente; valores CQFS. DEFICIÊNCIA DE Fe EM SOJA: solos calcários (pH > 7 + alto Ca) = amarelão da soja; Fe³⁺ precipita como Fe(OH)₃; soja = estratégia I para absorção de Fe (FRO2 reduz Fe³⁺ → Fe²⁺; IRT1 absorve Fe²⁺); em pH alto, FRO2 inibida; CORREÇÃO: quelatos de Fe (EDTA-Fe, EDDHA-Fe = mais estável em pH > 6.5) foliar: 500-1000 g/ha.',
 'Novais, R.F. et al. (2007). Fertilidade do Solo. SBCS, Viçosa. / Marschner, H. (2012).',
 '{Mn, manganês, Fe, ferro, toxicidade, pH ácido, alagamento, calagem, DTPA, soja, amarelão, FRO2, IRT1, EDTA-Fe, EDDHA-Fe, Si, Ca, bronzeamento, escoriose}'),

('Novais et al. — Enxofre e molibdênio: demanda, déficit e nutrição de leguminosas',
 'referencia', 'all',
 'ENXOFRE (S) NO SOLO: FORMAS: SO₄²⁻ (sulfato, forma absorvível) = em equilíbrio com S adsorvido em óxidos (cargas positivas) e S em MO (mineralização libera SO₄²⁻); DINÂMICA: S é intermediariamente móvel; em Oxissolos com óxidos de Fe/Al = SO₄²⁻ adsorvido nos horizontes B (subsuperfície) → função de reservatório; precipitação ácida contribui com S; pastagem degradada = menor entrada de S via MO. DIAGNOSE: análise de solo Embrapa (S-SO₄ extraído com Ca(H₂PO₄)₂ 0.01 M): < 5 mg/dm³ = deficiente; 5-30 = adequado; > 30 = alto. SOJA: exige ~ 15-25 kg S/ha/ciclo; em solos com MO > 3% = provável suficiência; em MO < 2% ou solos arenosos = aplicar S. ADUBAÇÃO: gesso agrícola (CaSO₄·2H₂O, 16% S + 24% Ca) = fonte mais usada; 200-300 kg/ha de gesso = 32-48 kg S/ha; sulfonato de amônio (24% S + 21% N); sulfato de K (18% S); evitar solo úmido para gesso (muito solúvel = lixivia em chuvas intensas). MOLIBDÊNIO (Mo): FORMAS: MoO₄²⁻ (molibdato, forma absorvível, ANIÔNICO — comportamento oposto ao outros micronutrientes); pH: disponibilidade AUMENTA com pH (contrário dos outros micronutrientes); em solos ácidos (pH < 5.5) = Mo retido em óxidos de Fe e Al → deficiente; calagem = aumenta disponibilidade de Mo. DIAGNOSE SOLO (Embrapa, oxalato ácido): < 0.1 mg/dm³ = deficiente; ADUBAÇÃO: foliar 20-50 g Mo/ha (molibdato de sódio 39% Mo ou molibdato de amônio) = dose muito pequena; tratamento de sementes com Mo: 3-12 g Mo/50 kg semente = mais eficiente para soja; CO + Mo via tratamento de sementes = padrão para otimizar FBN.',
 'Novais, R.F. et al. (2007). Fertilidade do Solo. SBCS, Viçosa. / Embrapa Soja (2013).',
 '{S, enxofre, gesso, SO4, CaSO4, MO, oxidação, Mo, molibdênio, molibdato, FBN, pH, soja, tratamento de sementes, Co, diagnose, DTPA, oxalato ácido}'),

('Novais et al. — Cálcio e magnésio: relações no solo, calagem dolomítica e gessagem',
 'referencia', 'all',
 'CÁLCIO (Ca) E MAGNÉSIO (Mg) NO SOLO: FONTES: calcário calcítico (CaCO₃, 30-40% Ca, < 5% Mg); calcário dolomítico (CaCO₃·MgCO₃, 20-30% Ca + 8-12% Mg); Cal virgem (CaO); hidratada (Ca(OH)₂); gesso (CaSO₄ = Ca sem poder de neutralização de H⁺ = não corrige pH, mas fornece Ca e S). RELAÇÕES Ca:Mg NO SOLO: relação ideal = 3:1 a 6:1 (em cmolc/dm³ na CTC); excesso de Mg (Ca:Mg < 2:1) = Solo magnésiano = maior absorção de Mg reduz Ca e K; solo com >60% saturação de Ca = pode limitar Mg. SATURAÇÃO DE BASES: objetivo para soja = V% 70-75% (Embrapa); Ca deve corresponder a 70-75% das bases trocáveis; Mg deve ser 10-15%; K deve ser 2-5%; GESSAGEM: gesso agrícola = aplicado quando solo subterrâneo tem Al³⁺ alto (>0.5 cmolc/dm³) em profundidade OU quando Ca do subsolo é baixo (<0.5 cmolc/dm³); Ca² + SO₄²⁻ do gesso migram pelo perfil → Ca substitui Al no subsolo → raízes aprofundam → maior absorção de água em seca; dose: 50-60 kg gesso/t argila (solo argiloso = 3 t/ha; médio = 2 t/ha; arenoso = 1 t/ha); EFEITO EM SOJA: gessagem = maior aprofundamento radicular em 20-30 cm → +5-15% produtividade em anos de déficit hídrico. INTERAÇÃO Mg-K: Ca:Mg:K = 15:5:1 = relação ideal; excesso de K na adubação (K/CTC > 5-6%) = risco de carência de Mg; em solos arenosos = aplicar Mg via calagem dolomítica ou sulfato de Mg foliar.',
 'Novais, R.F. et al. (2007). Fertilidade do Solo. SBCS, Viçosa. / Sfredo, G.J. (2008). Soja no Brasil. Embrapa.',
 '{Ca, Mg, cálcio, magnésio, calcário calcítico, dolomítico, gesso, gessagem, CaSO4, V%, saturação de bases, Al, subsolo, enraizamento, soja, K, relação Ca:Mg:K}');
-- ─── TAIZ & ZEIGER — HORMÔNIOS VEGETAIS AVANÇADO (Cap. 19-21, 5ª Ed. 2013) ───
-- Auxinas, giberelinas, citocininas, ABA e brassinosteroides em profundidade
-- ─────────────────────────────────────────────────────────────────────────────

insert into public.conhecimento (titulo, tipo, cultura, conteudo, fonte, tags) values

('Taiz & Zeiger — Auxinas (IAA): biossíntese, transporte polar e ação celular',
 'artigo', 'all',
 'AUXINAS (Cap. 19): BIOSSÍNTESE: IAA (ácido indol-3-acético) = hormônio principal; síntese dominante = via TRIPTOFANO (precursor): ROTA IPyA = TRP → IPyA (piruvato indol-3-) → IAA (YUCCA/FMO); ROTA IAAId = TRP → IAAId (indolacetamida via bactérias ou enzimas AMIDA HIDROLASE); ROTA ISA = não-triptofano = via IPyP diretamente; LOCALIZAÇÃO: meristemas apicais, folhas jovens, embriões em desenvolvimento, frutos. TRANSPORTE POLAR (PAT): TRANSPORTADORES: AUX1/LAX = importadores de IAA (auxin influx carriers); PIN (PIN-FORMED): PIN1, PIN2, PIN3, PIN4, PIN7 = exportadores (eflux carriers), localizados assimetricamente na membrana basal → direciona IAA basipetalmente; ABP1 + TMK1 = receptores na membrana que respondem ao IAA em ms. MECANISMO MOLECULAR: TIR1 (F-box receptor) + Aux/IAA repressores (domínio II = degron) → IAA liga TIR1 → SCF^TIR1 ubiquitina Aux/IAA → degradação 26S-proteassomo → ARFs (Auxin Response Factors) libertos → ativam genes de resposta. ATIVAÇÃO DE EXPANSINAS (hipótese do crescimento ácido): IAA → ativa H⁺-ATPase → exocitose de H⁺ → pH da parede ↓ de 7→5 → expansinas XTH ativadas → clivam celulose/hemicelulose → parede relaxa → entrada de K⁺+H₂O → elongação. GRADIENTE IAA E GRAVITROPISMO: coluna de amiloplastos (estatólitos) sedimenta → PIN3 relocado → IAA migra lateralmente → elongação diferencial → curvatura para baixo. INTERAÇÃO MINERAL: ZN (cofator de triptofano sintase = enzima da síntese de IAA; deficiência de Zn → reduz IAA → roseta); B (integridade de PIN via borato-pectina complexo); N (triptofano é N-aminoácido).',
 'Taiz, L. & Zeiger, E. (2013). Plant Physiology. 5th ed. Cap. 19. Sinauer.',
 '{auxina, IAA, TRP, triptofano, PIN, AUX1, TIR1, SCF, ARF, expansina, transporte polar, PAT, gravitropismo, Zn, B, N, H+-ATPase, crescimento ácido, meristema}'),

('Taiz & Zeiger — Giberelinas: biossíntese, deactivação e respostas fisiológicas em soja',
 'artigo', 'all',
 'GIBERELINAS (Cap. 20): mais de 136 giberelinas (GA) identificadas; bioativas em plantas superiores = GA₁, GA₃, GA₄, GA₇; síntese no retículo endoplasmático + plastidios. BIOSSÍNTESE: GGPP (géranilgéranilpirofosfato) → ent-copalil difosfato (ent-CDP) via ent-CPPS (COPALIL DIPHOSPHATE SYNTHASE) → ent-caureno via KS (ENTE-KAURENE SYNTHASE) → ent-caurenol → GA₁₂ via P450 + Fe/Mn-oxidases → GA₂₀ → GA₁ (ativo); DEACTIVAÇÃO: GA 2-OXIDASE = inativa GA₁ → GA₈; CONTROLE MODULADO POR FEEDBACK: GA₁ ativa DELLA proteínas → DELLA ativa 2-oxidase → degrada mais GA₁ (auto-regulação). MODO DE AÇÃO: DELLA (motivo DELLA = Asp-Glu-Leu-Leu-Ala) = repressores globais de crescimento; GA + GID1 (receptor solúvel) → GID1-GA-DELLA = SCF^SLY1 → ubiquitinação DELLA → degradação → MYC, MYBs liberados → genes de crescimento. RESPOSTAS FISIOLÓGICAS: elongação do caule (GAs estimulam células subapicais, não o meristema); germinação de sementes (GA activa α-amilases via GAMYB); florescimento de plantas de dia longo (GA integra sinal de fotoperíodo → CO → FT → flor); desenvolvimento de frutos; quebra de dormência; RELAÇÃO COM BRASSINOSTEROIDES: BR e GA cooperam → BR aumenta elongação celular, GA aumenta elongação do nodo; ambos ativam expansinas e XTHs. INTERAÇÃO MINERAL: Mn (cofator de ent-caureno sintase e GA-oxidases; Mn-deficiência = internódios curtos); Fe (Fe-2-oxoglutarato dioxigenases nas últimas etapas da síntese de GA).',
 'Taiz, L. & Zeiger, E. (2013). Plant Physiology. 5th ed. Cap. 20. Sinauer.',
 '{giberelina, GA, DELLA, GID1, SCF, SLY1, biossíntese, ent-caureno, GAMYB, elongação, florescimento, germinação, brassinosteroide, Mn, Fe, dormência, soja}'),

('Taiz & Zeiger — Citocininas: biossíntese, sinal de nitrogênio e senescência',
 'artigo', 'all',
 'CITOCININAS (Cap. 21): CLASSES: adenina-isopenteniladenina (iP, tZP = trans-zeatina = mais ativo em soja); dihidrozeatina (DHZ); ciszeatin; SÍNTESE: isopentenil difosfato (IPP, via MEP no plastídio) + AMP → iPRMP via ADENILATO ISOPENTILTRANSFERASE (IPT); iPRMP → tZRMP via CYP735A (P450-oxidase, Fe-dependente) → exportação via xilema. RECEPTORES: AHK (Arabidopsis Histidine Kinase) = AHK2, AHK3, AHK4/CRE1 = receptores de membrana com domínio CHASE; CK + AHK → phosphorylation AHP → B-ARRs (ativadores de resposta) + A-ARRs (repressores). FUNÇÕES FISIOLÓGICAS: (1) DIVISÃO CELULAR: CDK (cyclin-dependent kinase) requerida; CK ativa ciclina D (CYCD3;1) → progresso G1/S; (2) SINAL DE N: raízes ricas em N produzem mais CK → transportadas para parte aérea → inibem senescência foliar, ativam genes de assimilação de N; (3) ATRASO DE SENESCÊNCIA: CK inibem proteases, clorofilases; senescência acelerada por queda de CK (estresse, envelhecimento); (4) SINK DE DRENO: CK produzidas em sementes → atraem assimilados para grãos em enchimento; (5) ABERTURA ESTOMATAL: CK ativa KAT1 → K⁺ entra na célula guarda → turgor sobe → abertura (oposto ao ABA). INTERAÇÃO MINERAL: N (síntese de CK depende de NO₃⁻ disponível — AHK4 no meristema radicular sente N via CK); Mg (ativa adenilato quinase → síntese de AMP para CK); K (na célula guarda). BIOESTIMULANTES: kinetin, BAP (6-benzilaminopurina) usados comercialmente; extrato de algas ≈ CK; aplicação foliar R1-R2 = retém flores, reduz aborto.',
 'Taiz, L. & Zeiger, E. (2013). Plant Physiology. 5th ed. Cap. 21. Sinauer.',
 '{citocinina, CK, AHK, ARR, IPT, tZP, zeatin, N, Mg, K, sinal de N, divisão celular, senescência, abertura estomatal, sink, grãos, florescimento, BAP, kinetin, extrato de algas}'),

('Taiz & Zeiger — Etileno e ABA: síntese, sinalização e papéis no amadurecimento e estresse',
 'artigo', 'all',
 'ETILENO (Cap. 22): GÁS SIMPLES mais potente em pg/g (1 nL/L = ativo); precursor = MET (metionina) → SAM (S-adenosilmetionina) via SAM sintetase → ACC (ácido 1-aminociclopropano-1-carboxílico) via ACC sintase (ACS, inibida por Co²⁺, análogos de piridoxal) → ETILENO via ACC oxidase (ACO, requer O₂ e ASA como cofatores; Fe-dependente); REGULAÇÃO: IAA e MeJA aumentam ACS; SINALIZAÇÃO: ETR1+ETR2 (receptores de membrana com domínio histidina-kinase; quando ET se liga → inativação → CTR1 inativado → EIN2 e EIN3 ativados → genes de resposta ERF). RESPOSTAS: amadurecimento de frutos (clímax ETH → ativa genes da biossíntese de antocianinas, suavização, aroma); abscisão (ETH + IAA baixo → ativa poligalacturonases e celulases na zona de abscisão → folhas caem); tripla resposta etileno (escuridão + ETH → elongação reduzida + engrossamento + curvatura gravitrópica = sinal de obstáculo); senescência foliar (ETH + CK-deficiência). ÁCIDO ABSCÍSICO (ABA) (Cap. 23): síntese = zeaxantina → violaxantina → xantoxina → ABA-aldeído → ABA (NCED = 9-cis-epoxycarotenoid dioxygenase = enzima-chave; Mo-dependente para a etapa final: aldeído oxidase); SINALIZAÇÃO: PYR/PYL + ABA → inibe PP2C → SnRK2 ativa OST2 (H+-ATPase = fecha) + SLAC1 (ânion = fecha) + ativa síntese de AOS2 (JA coopera em estresse); FUNÇÕES: dormência de sementes (catabolismo de GA + ativação de inibidores de germinação); tolerância ao estresse (acumula compatible solutes); fechamento estomático; controle de desenvolvimento de sementes. INTERAÇÃO MINERAL: Ca²⁺ como segundo mensageiro de ABA (Ca²⁺ ativa CDPK que fosforila SLAC1); S (SAM = S-aminoácido para síntese de etileno); Cu e S para ACO.',
 'Taiz, L. & Zeiger, E. (2013). Plant Physiology. 5th ed. Cap. 22-23. Sinauer.',
 '{etileno, ET, ACS, ACO, ACC, ETR1, EIN3, amadurecimento, abscisão, ABA, PYR/PYL, PP2C, SnRK2, SLAC1, NCED, Mo, Ca, S, Cu, senescência, dormência, estômato, IAA}'),

('Taiz & Zeiger — Brassinosteroides e Jasmonatos: papel no desenvolvimento e defesa',
 'artigo', 'all',
 'BRASSINOSTEROIDES (BR) (Cap. 24 suplement): esteroides vegetais; brassinolídeo (BL) = mais ativo; síntese = campesterol → brassinolídeo via CYP90 (citocromo P450 + O₂, Fe-dependente); RECEPTOR: BRI1 (leucine-rich receptor kinase) + BAK1 (co-receptor) → fosforilação em cascata → inativa BIN2 (GSK3-like quinase = repressor) → BES1/BZR1 (fatores de transcrição) ativados → genes de elongação e resposta a estresse. FUNÇÕES: elongação celular (sinergismo com IAA + GA); estresse: BR melhora tolerância a seca, frio, salinidade, metais pesados (induz antioxidantes SOD+CAT+APX); florescimento e desenvolvimento de grãos; fotomorfogênese; APLICAÇÕES: 24-epibrassinolídeo exógeno (0.01-1 μM) foliar ou na semente = aumento de rendimento em soja, milho e arroz; efeito especialmente em estresse de calor+seca (R1-R4); Brassinolídeo aumenta fertilidade do pólen em alta temperatura. JASMONATOS (JA) (Cap. 13): ácido jasmônico + MeJA (volátil) + JA-Ile (bioativo); síntese = ácido linolênico (liberado de membranas por fosfolipase A = ativada por ferimento ou elicitores) → LOX (Fe-dependente) → 13-HPOT → AOS → AOC → OPDA → JA (beta-oxidação peroxissomal); JA-Ile = COI1 (receptor) → degrada JAZ repressores → MYC2, MYC3 ativos → síntese PI-II, VSP2, PAL (fenilpropanoide), terpenoides. CROSSTALK: JA+ETH (cooperam contra necrotrofos); JA+SA (antagonismo); BR+JA (BR reduz JA em tecidos jovens = evita autoimunidade); ETH+JA (sinergia em defesa).',
 'Taiz, L. & Zeiger, E. (2013). Plant Physiology. 5th ed. Cap. 13, 24. Sinauer.',
 '{brassinosteroide, BR, BRI1, BES1, BZR1, BIN2, elongação, jasmato, JA, LOX, COI1, JAZ, MYC2, SA, ETH, Fe, defesa, florescimento, seca, calor, soja, milho}');
-- ─── BIOFERTILIZANTES / FISIOLOGIA — PROLINA, ANTIOXIDANTES E ESTRESSE SOJA ──
-- Osmoprotetores, enzimas antioxidantes e respostas fisiológicas a estresses
-- ─────────────────────────────────────────────────────────────────────────────

insert into public.conhecimento (titulo, tipo, cultura, conteudo, fonte, tags) values

('Prolina vegetal: biossíntese, função e acúmulo em estresse hídrico e térmico em soja',
 'artigo', 'all',
 'PROLINA: aminoácido imino, derivado do glutamato; em condições de estresse, é o principal osmoprotegente acumulado em plantas (pode chegar a 80-100 mM em células de folhas estressadas vs. 0.5 mM no controle); BIOSSÍNTESE DE PROLINA: GLUTAMATO → γ-semialdehído glutâmico (GSA) via P5CS (delta-1-pirrolina-5-carboxilato sintetase, NADPH-dependente) → P5C → Prolina via P5CR (prolina redutase); via alternativa de ornitina → OAT → GSA → P5C → Prolina (predomina em raízes). DEGRADAÇÃO: Prolina → P5C → Glutamato via ProDH (prolina desidrogenase, mitocondrial; O₂-dependente; produz H₂O₂); quando estresse aliviado = prolina degrada → glutamato reutilizado. FUNÇÕES MÚLTIPLAS: (1) Osmorregulação: acumulação ajusta Ψs sem toxicidade; (2) Proteção de proteínas e membranas: forma coluna de moléculas de água ao redor de proteínas (chaperonas químicas), estabiliza membranas em dessecação; (3) Scavenger de ROS: prolina + ¹O₂ → produtos não-tóxicos; ativa POD, APX, CAT indiretamente; (4) Fonte de C e N na recuperação: ProDH libera C e N ao glutamato após o estresse; (5) Sinalização: P5C produto = sinal de redox para resposta ao estresse. REGULAÇÃO: ABA ativa P5CS1 e P5CS2 (genes de P5CS têm ABA-responsive elements); luz azul + seca = co-reguladores; P5CS mRNA aumenta em 2-6h após déficit hídrico em folhas de soja. APLICAÇÃO PRÁTICA: prolina exógena (1-5 mM foliar) = aumenta tolerância a seca, calor e salinidade em soja; aminoácidos hidrolisados contendo prolina = via indireta eficiente; mais eficiente aplicado em V5-R1 (pré-estresse). INTERAÇÃO: K (K melhora produção de prolina via P5CS); Mg (ativa P5CS como enzima ATPase-like); N (glutamato = precursor de N).',
 'Szabados, L. & Savoure, A. (2010). Proline: a multifunctional amino acid. Trends Plant Sci 15:89-97. / Verbruggen, N. & Hermans, C. (2008). Proline accumulation in plants: a review. Amino Acids 35:753-759.',
 '{prolina, P5CS, osmorregulação, estresse hídrico, calor, seca, ABA, ROS, scavenger, chaperonas químicas, aminoácido, K, Mg, N, glutamato, soja, bioestimulante, foliar}'),

('Glicina betaína: biossíntese, proteção de cloroplastos e aplicação foliar em soja',
 'artigo', 'all',
 'GLICINA BETAÍNA (GB): quaternário de amônio, compatível com enzimas em altas concentrações; derivado da oxidação de colina (Ch) via CMO (colina monooxigenase) + BADH (betaína aldeído desidrogenase). LOCALIZAÇÃO: estroma dos cloroplastos = principal sítio de acúmulo; GB é NATURALMENTE ABUNDANTE em espinafre, beterraba, trigo, cevada; em soja e milho = PEQUENA CAPACIDADE de síntese endógena = deficiência funcional em estresse severo. FUNÇÕES: (1) Proteção do estroma: estabiliza Rubisco e proteínas do estroma em dessecação (Rubisco é menos inativada em presença de GB 100 mM); (2) Proteção de tilacoides: estabiliza proteínas PSII em calor (GB mantém OEC funcional acima de 40°C por mais tempo); (3) Regulação da atividade de enzimas: GB em 0.5-2 M não inibe enzimas (diferente de NaCl ou sorbitol); (4) Osmorregulação: efetiva em ajustar potencial osmótico; (5) Proteção de membranas: GB interage com cabeças polares de fosfolipídios → estabiliza bicamada em congelamento e desidratação. APLICAÇÃO EXÓGENA: GB foliar em soja (R1-R3) = 5-10 mM = melhora pegamento de flores em calor + seca; mistura GB + PEG ou GB + K = efeito aditivo; formulações comerciais de extrato de algas contém GB + betaínas análogas. INTERAÇÃO MINERAL: N (colina é N-betaína, consome N); S (BADH enzima precisa de S para grupo -SH); Mg (estabiliza ribossomas que sintetizam BADH); Mn (PSII-OEC protegido pela GB). DIFERENÇA DE PROLINA: prolina = citoplasmática, proteção geral; GB = cloroplasto, proteção fotossintética específica.',
 'Chen, T.H.H. & Murata, N. (2011). Glycinebetaine protects plants against abiotic stress. Plant Cell Environ 34:1-20.',
 '{glicina betaína, GB, colina, CMO, BADH, Rubisco, cloroplasto, PSII, OEC, estresse térmico, seca, salinidade, extrato de algas, N, S, Mg, Mn, soja, foliar, R1, R2}'),

('Manejo do estresse oxidativo em soja: ROS, antioxidantes e momento de aplicação',
 'artigo', 'soja',
 'PROTOCOLO ANTIOXIDANTE EM SOJA (abordagem integrativa): DIAGNOSE DE ESTRESSE OXIDATIVO: sintomas visuais = clorose internerval (Fe-SOD ou Cu/Zn-SOD comprometida) + manchas bronzeadas + necroses em folhas velhas + murcha diurna + retardo de crescimento; CAUSA NUTRICIONAL: verificar Zn, Cu, Mn, Fe (cofatores de SOD, CAT, POD) + N, S, Mg (cofatores de enzimas de síntese de clorofila e proteínas antioxidantes). ESTÁDIOS CRÍTICOS DE ESTRESSE: V3-V4 (crescimento vegetativo rápido + maior produção de ROS por fotossíntese ativa); R1-R2 (florescimento + temperatura alta = maior produção de ¹O₂ em PSII); R4-R5 (enchimento + senescência acelerada = maior etileno + ROS). PROTOCOLO DE REDUÇÃO DE ESTRESSE OXIDATIVO: (1) Pré-florescimento V4-V5: Zn (300 g/ha) + Cu (150 g/ha) + Mn (400 g/ha) = ativa enzimas SOD; (2) Florescimento R1-R2: prolina (500 mL/ha aminoácidos) + GB (extrato de algas 1 L/ha) + Ca (1 kg/ha nitrato de Ca) + B (200 g/ha) = proteção do PSII + pegamento; (3) Enchimento R4-R5: K (1.5 kg/ha KNO₃) + N (ureia 0.5% = 2 kg/ha) + Mg (0.5 kg/ha) + fungicida (para manter área foliar saudável) = manutenção fotossintética. INTERAÇÃO ROS × DEFICIÊNCIAS: deficiência de Fe = APX comprometida → H₂O₂ acumula → foto-inibição do PSII; deficiência de Zn = SOD comprometida → O₂•⁻ não neutralizado → Fenton → HO• → oxidação de lipídios de membranas; TRATAMENTO URGENTE (seco/calor severo): GB + prolina + Ca foliar + Si foliar + K foliar = protocolo de emergência para proteger o florescimento em R1-R2 sob seca + calor extremo.',
 'Mittler, R. (2002). Oxidative stress, antioxidants and stress tolerance. Trends Plant Sci 7:405-410. / Embrapa Soja (2013). Tecnologias de produção.',
 '{estresse oxidativo, ROS, SOD, CAT, APX, POD, Zn, Cu, Mn, Fe, N, Mg, prolina, glicina betaína, Ca, B, K, Si, florescimento, soja, R1, R2, V4, V5, protocolo, emergência}'),

('Manejo fisiológico integrado em soja: cronograma de aplicações por estádio',
 'referencia', 'soja',
 'CRONOGRAMA DE MANIPULAÇÕES FISIOLÓGICAS EM SOJA: TRATAMENTO DE SEMENTES (TS): Bradyrhizobium (100 mL/50 kg) + Azospirillum (100 mL/50 kg, último) + Mo+Co (3-12 g Mo/50 kg) + EDDHA-Fe (se solo calcário) = base FBN e arranque; V1-V2 (30-40 DAP): Solo ou foliar de P (se deficiente) + Zn (300 g/ha foliar ou 3 kg/ha solo) + Mn (400 g/ha foliar) + Mo (30 g/ha foliar) = estabelecimento de raízes e FBN; OPTIONAL: auxinas exógenas (AIB 50 mg/L foliar) para enraizamento adicional. V3-V4 (40-50 DAP): N foliar (0.5% ureia se amarelecimento) + K (1 kg/ha KNO₃) + Mg (500 g/ha sulfato Mg) + B (150 g/ha ácido bórico) PREVENTIVO + Zn + Mn = nutrição vegetativa plena; bioestimulante: ácidos húmicos/fúlvicos (3-5 L/ha) + extrato algas (1 L/ha). V5-V6 (50-60 DAP): B (200 g/ha OBRIGATÓRIO) + Ca (1 kg/ha nitrato Ca) + K (1 kg/ha) + Zn (200 g/ha) = PRÉ-FLORESCIMENTO = sinalização para flores; aminoácidos (300 mL/ha) + extrato algas 1 L/ha; corrigir pH foliar da calda 5.5-6.5 para melhor absorção. R1 (florescimento início): B (200 g/ha) + Ca (1 kg/ha) + Zn (200 g/ha) + Mo (30 g/ha) = CRÍTICO para pegamento; GB foliar (extrato algas 1.5-2 L/ha) se calor/seca. R2-R3 (florescimento pleno-vagens): K (1.5 kg/ha) + Ca (1 kg/ha) + S (1 kg/ha tiosulfato) + N (aminoácidos 300 mL/ha) = formação de vagens; fungicida sistêmico na sequência. R4-R5 (enchimento): K (1.5-2 kg/ha) + N foliar + Mg (500 g/ha) + S (1 kg/ha) = enchimento de proteína e óleo; manter folhas saudáveis com fungicida.',
 'Sfredo, G.J. (2008). Soja no Brasil: Calagem e Adubação. Embrapa Soja. / Hungria et al. (2013). Co-inoculação. Embrapa.',
 '{cronograma, aplicação foliar, soja, V1, V2, V3, V4, V5, V6, R1, R2, R3, R4, R5, B, Ca, Zn, K, N, Mo, Co, Mg, S, FBN, florescimento, enchimento, tratamento de sementes, bioestimulante}');
-- ─── NOVAIS / EMBRAPA — NUTRIÇÃO DE MILHO E FEIJÃO: tabelas e critérios ──────
-- Diagnose, adubação e fisiologia específica para milho e feijão
-- ─────────────────────────────────────────────────────────────────────────────

insert into public.conhecimento (titulo, tipo, cultura, conteudo, fonte, tags) values

('Embrapa Milho — Nutrição e adubação do milho: macronutrientes e micronutrientes',
 'referencia', 'milho',
 'EXTRAÇÃO E EXPORTAÇÃO DE NUTRIENTES (milho grão, 8 t/ha): N=144 kg/ha extraído (exporta 128 kg), P₂O₅=65 kg (exporta 55 kg), K₂O=180 kg (exporta 48 kg), Ca=32 kg, Mg=22 kg, S=16 kg, Zn=280 g, Mn=200 g, Fe=600 g, Cu=70 g, B=100 g. DIAGNOSE FOLIAR (folha bandeira em V6-VT, limbo da folha média): N=27-35 g/kg; P=2-4 g/kg; K=15-25 g/kg; Ca=3-8 g/kg; Mg=2-6 g/kg; S=2-3.5 g/kg; B=15-40 mg/kg; Zn=15-60 mg/kg; Cu=4-12 mg/kg; Mn=15-150 mg/kg; Fe=50-300 mg/kg; Mo=0.1-1.0 mg/kg. ESTÁDIOS CRÍTICOS MILHO: N (V4-R1 = panícula); P (germinação-V4); K (VT-R2); Ca, B (VT-R1 = polinização = CRÍTICO). ADUBAÇÃO BASE: NPK no sulco = 300-600 kg/ha (formulação 05-20-20 ou 10-15-20 dependendo do solo); topdressing N = 40-60 kg N/ha em cobertura em V4-V6 (ureia 45% ou sulfato de amônio 21% N); parcelamento = maior eficiência do N. ZINCO EM MILHO: Zn é o micronutriente mais limitante no milho em solos do cerrado; "mancha branca" ou "stripe" do milho = Zn deficiência em V2-V4; diagnose = < 15 mg Zn/kg na folha; correção foliar = 300 g ZnSO₄/ha em V2-V4. NITROGÊNIO E MILHO: N é o nutriente mais limitante para o rendimento; resposta esperada ao N = +5-15 sc/ha por 30 kg N/ha adicionais até máximo de 150-200 kg N/ha; fonte N influencia: ureia (volatilização de NH₃ em solo aquecido = perda de 20-40%); ureia+NBPT (inibidor de urease) = reduz perda 50%; sulfato de amônio = mais eficiente em pH alto, mas acidifica o solo (-0.2 pH/100 kg).',
 'Embrapa Milho e Sorgo (2010). Tecnologias de Produção de Milho. Embrapa. / Novais, R.F. et al. (2007). Fertilidade do Solo. SBCS.',
 '{milho, N, P, K, Ca, Mg, S, Zn, Mn, Fe, Cu, B, Mo, diagnose foliar, adubação, topdressing, ureia, NBPT, sulfato de amônio, mancha branca, cerrado, V4, V6, VT, R1}'),

('Embrapa Feijão — Nutrição e adubação do feijoeiro: nutrientes críticos e déficits comuns',
 'referencia', 'feijao',
 'FEIJOEIRO COMUM (Phaseolus vulgaris): ciclo curto (65-110 dias) = alta demanda nutricional por unidade de tempo. EXTRAÇÃO DE NUTRIENTES (2.5 t grãos/ha): N=130 kg (exporta 85 kg), P₂O₅=55 kg (exporta 48 kg), K₂O=120 kg (exporta 80 kg), Ca=30 kg, Mg=15 kg, S=12 kg, Zn=210 g, B=80 g. FBN NO FEIJÃO: MENOS eficiente que soja (< 40 kg N/ha fixado na maioria das condições vs 100+ na soja); inoculação com Rhizobium tropici SEMIA 4080 + SEMIA 4088 = padrão MAPA para feijão; FBN no feijão = fortemente limitada por pH < 6.0, Al alto, P baixo, Mo baixo. ADUBAÇÃO DE PLANTIO: 250-400 kg/ha NPK (04-20-20 ou 05-25-15 dependendo análise solo); NITROGÊNIO: 0-30 kg N no plantio (inoculado = mínimo; sem inoculação = 30-60 kg N); cobertura = 20-40 kg N em V3-V4 (pré-florescimento); excesso de N antes do florescimento = crescimento vegetativo excessivo e aborto floral. ESTÁDIOS CRÍTICOS FEIJÃO: V4-R1 (pré-florescimento = estádio de manipulação = B+Ca+Zn para evitar aborto floral); R7-R8 (enchimento de grãos = K máxima demanda). DIAGNOSE FOLIAR (3ª folha trifoliolada em V4): N=40-55 g/kg; P=3-5.5 g/kg; K=18-28 g/kg; Ca=8-20 g/kg; Mg=3-8 g/kg; S=2.5-4 g/kg; B=25-70 mg/kg; Zn=20-60 mg/kg; Cu=5-15 mg/kg; Mn=40-200 mg/kg; Fe=70-400 mg/kg; Mo=0.5-5 mg/kg. CARÊNCIAS MAIS COMUNS EM FEIJÃO: Zn (solos ácidos com P alto), Mn (toxicidade em pH < 5.5), Mo (FBN comprometida em pH ácido), B (antes do florescimento = aborto), N (plantas pálidas se FBN falhou).',
 'Embrapa Arroz e Feijão (2012). Cultivo do Feijoeiro Comum. Embrapa / Novais, R.F. et al. (2007). Fertilidade do Solo. SBCS.',
 '{feijão, feijoeiro, N, P, K, Ca, Mg, S, Zn, B, Mo, Mn, Fe, Rhizobium, FBN, diagnose foliar, adubação, V4, R1, R7, florescimento, aborto floral, inoculação, SEMIA 4080}'),

('Antagonismos e sinergismos nutricionais em soja: tabela de relações práticas',
 'referencia', 'soja',
 'TABELA DE ANTAGONISMOS NUTRICIONAIS EM SOJA (impacto agronômico): K↓Mg: K alto (K/CTC > 5%) → Mg abaixo de 0.6 cmolc/dm³ = clorose internerval velhas + folhas velhas com amarelamento internerval; correção = calcário dolomítico + Mg foliar. Ca↓Mn: calagem elevada (pH > 6.5) → Mn precipita → Mn < 0.3 mg/dm³ solo = deficiência de Mn mesmo sem histórico; correção = Mn foliar 400 g/ha. P↓Zn: P alto (> 40 mg/dm³) + pH 5.5-6.5 → Zn-fosfato insolúvel; Zn foliar < 21 mg/kg = deficiência induzida por P; correção = Zn foliar 300-500 g/ha. S↓Mo: SO₄²⁻ alto + SO₄ do gesso = compete com MoO₄²⁻; Mo < 0.5 mg/kg foliar = FBN comprometida; correção = Mo foliar 30 g/ha separado do gesso. Ca↑B: B adequado = melhora distribuição de Ca; sem B = Ca mal distribuído mesmo com Ca no solo (B-pectina-Ca complexo). Mn↑Fe (antagonismo): pH ácido (< 5.5) = ambos em excesso simultâneo = toxicidade de Mn + Fe; pH 5.5-6.0 = ambos adequados. pH↓Mo (ÚNICO POSITIVO): solo ácido = Mo indisponível; calagem = corrige Mo naturalmente; em pH 6.5 = Mo adequado mesmo sem adubação. TABELA DE SINERGISMOS: N×S (N:S ideal = 17:1 em g/g; sem S = proteínas incompletas, FBN comprometida). P×Mo (P apoia síntese de ATP para nitrogenase que usa Mo). B×Ca (B mobiliza Ca e estrutura Ca-pectina da parede celular). Zn×IAA (Zn → síntese de IAA → mais raízes → maior absorção de outros nutrientes). Mo×FBN (Mo é cofator da nitrogenase = OBRIGATÓRIO para FBN eficiente).',
 'Malavolta, E. et al. (1997). Avaliação do Estado Nutricional das Plantas. Potafos. / Marschner, H. (2012). Mineral Nutrition. Academic Press.',
 '{antagonismo, sinergismo, K, Mg, Ca, Mn, P, Zn, S, Mo, B, N, Fe, soja, FBN, relações nutricionais, tabela, diagnose, pH, calagem}');
